package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG._BASICS;

import panter.gmbh.Echo2.bibE2;

public enum FZ_BASE_QUERYS {

	 ALLE_STARTBESITZER_IN_BEWEGUNG_VEKTOR("SELECT DISTINCT BS.ID_ADRESSE_BESITZER FROM "+bibE2.cTO()+".JT_BEWEGUNG_VEKTOR BV "
												+ " LEFT OUTER JOIN "+bibE2.cTO()+".JT_BEWEGUNG_ATOM ATO ON (ATO.ID_BEWEGUNG_ATOM=BV.ID_BEWEGUNG_ATOM_TRIGSTART) "
												+ " LEFT OUTER JOIN "+bibE2.cTO()+".JT_BEWEGUNG_STATION BS ON (BS.ID_BEWEGUNG_ATOM=ATO.ID_BEWEGUNG_ATOM AND BS.MENGENVORZEICHEN=-1)")
	
	,ALLE_ZIELBESITZER_IN_BEWEGUNG_VEKTOR("SELECT DISTINCT BS.ID_ADRESSE_BESITZER FROM "+bibE2.cTO()+".JT_BEWEGUNG_VEKTOR BV "
												+ " LEFT OUTER JOIN "+bibE2.cTO()+".JT_BEWEGUNG_ATOM ATO ON (ATO.ID_BEWEGUNG_ATOM=BV.ID_BEWEGUNG_ATOM_TRIGSTART) "
												+ " LEFT OUTER JOIN "+bibE2.cTO()+".JT_BEWEGUNG_STATION BS ON (BS.ID_BEWEGUNG_ATOM=ATO.ID_BEWEGUNG_ATOM AND BS.MENGENVORZEICHEN=1)")

	,ERZEUGEN_BASISADRESSE_AUS_LIEFERADRESSE("SELECT NVL(LA.ID_ADRESSE_BASIS,A.ID_ADRESSE) AS ID_ADRESSE_BASIS  FROM "+bibE2.cTO()+".JT_ADRESSE A "
												+ " LEFT OUTER JOIN "+bibE2.cTO()+".JT_LIEFERADRESSE  LA ON (LA.ID_ADRESSE_LIEFER=A.ID_ADRESSE) WHERE A.ADRESSTYP IN (1,5) AND  A.SONDERLAGER IS NULL") 
	
	
    ;

	
	;
	
	private String  SQL_Statement = null;
	
	private FZ_BASE_QUERYS(String p_SQL_Statement) {
		
	}
}
