package rohstoff.Echo2BusinessLogic.BAM_FUHREN;

import panter.gmbh.basics4project.DB_RECORDS._DB;

public class BAMF__CONST
{

	public static final String FIELDNAME_CROSSREFERENCE_BAM_USER = 						"FIELDNAME_CROSSREFERENCE_BAM_USER";
	public static final String FIELDNAME_DAUGHTERTABLE_PRINTPROTOKOLL = 				"FIELDNAME_DAUGHTERTABLE_PRINTPROTOKOLL";
	public static final String FIELDNAME_DEL_BUTTON_DAUGHTERTABLE_PRINTPROTOKOLL = 		"FIELDNAME_DEL_BUTTON_DAUGHTERTABLE_PRINTPROTOKOLL";
	public static final String FIELDNAME_FBAM_SENDE_MAILS_TO_VERTEILER = 				"FIELDNAME_FBAM_SENDE_MAILS_TO_VERTEILER";
	public static final String FIELDNAME_BUTTON_COMPOSE_FEHLERBESCHREIBUNG = 			"FIELDNAME_BUTTON_COMPOSE_FEHLERBESCHREIBUNG";
	
	public static final String FIELDNAME_FBAM_RESET_WEIGERMELDUNGSZAEHLER = 			"FIELDNAME_FBAM_RESET_WEIGERMELDUNGSZAEHLER";

	public static final String FIELDNAME_FBAM_MASK_INFO_LINE1 = 							"FIELDNAME_FBAM_MASK_INFO_LINE1";
	public static final String FIELDNAME_FBAM_MASK_INFO_LINE2 = 							"FIELDNAME_FBAM_MASK_INFO_LINE2";
	public static final String FIELDNAME_FBAM_MASK_INFO_LINE3 = 							"FIELDNAME_FBAM_MASK_INFO_LINE3";
	public static final String FIELDNAME_FBAM_MASK_INFO_LINE4 = 							"FIELDNAME_FBAM_MASK_INFO_LINE4";
	public static final String FIELDNAME_FBAM_MASK_INFO_LINE5 = 							"FIELDNAME_FBAM_MASK_INFO_LINE5";
	public static final String FIELDNAME_FBAM_MASK_INFO_LINE6 = 							"FIELDNAME_FBAM_MASK_INFO_LINE6";
	
	public static final String FBAM_DRUCK_VERMERK_BAM = 								"Beanstandungsmeldung";
	public static final String FBAM_DRUCK_VERMERK_WEIGER = 								"Weigermeldung";

	
	

	/*
	 * sperrliste fuer felder aus der maske, wird im masken-setter benutzt
	 * WEIGERMELDUNG
	 * und alles andere
	 */
	public static final String FBAM_LOCKLIST_WEIGERMELDUNG=":WM_UEBERNAHMEVORSCHLAG:WM_DATUM:WM_ANSPRECHPARTNER_INHOUSE:WM_ABNEHMER:::" +
															":WM_ORT:WM_UHRZEIT:WM_ANSPRECHPARTNER_LIEFERANT:WM_FAXNUMMER::" +
															":WM_ANLIEFERDATUM:WM_LETZTERDRUCK_DATUM:WM_LETZTERDRUCK_UHRZEIT:WM_GESPERRT::" +
															":WM_ZAEHLER_ENTSPERRUNG:WM_ARTBEZ1:WM_ABHOLDATUM:WM_MENGE_ABLADEN:"+
															BAMF__CONST.FIELDNAME_FBAM_RESET_WEIGERMELDUNGSZAEHLER+":"+
															_DB.FBAM$FEHLERINFO_EXTERN+":";

	public static final String FBAM_LOCKLIST_BAM=			":BAM_GRUND:BAM_DATUM:BAM_ORT:ID_VPOS_TPA_FUHRE:FESTSTELLUNG_BAM:BETREFF_BAM:" +
															":FEHLERURSACHE:FEHLERBESCHREIBUNG:AUSWIRKUNGEN:BEHEB_VORSCHLAG:BEHEB_VERMERK:" +
															":DATUM_AUSSTELLUNG:ID_USER_AUSSTELLUNG:DATUM_BEHEBUNG:ID_USER_BEHEBUNG:DATUM_KONTROLLE:" +
															":ID_USER_KONTROLLE:ABGESCHLOSSEN_BEHEBUNG:ABGESCHLOSSEN_KONTROLLE:"+
															BAMF__CONST.FIELDNAME_CROSSREFERENCE_BAM_USER+":"+
															BAMF__CONST.FIELDNAME_BUTTON_COMPOSE_FEHLERBESCHREIBUNG+":";

	
}
