package rohstoff.Echo2BusinessLogic.MAIL_INBOX;

public class MAIL_INBOX_Const {
	public static String BUTTON_SHOW_ANHANG_LISTE = "BUTTON_SHOW_ANHANG_LISTE";
	public static String ROW_SHOW_ANHANG_LISTE    = "ROW_SHOW_ANHANG_LISTE";
	public static String COLUMN_SHOW_ANHANG_LISTE = "COLUMN_SHOW_ANHANG_LISTE";
	
	public static String BUTTON_CONNECT_ADRESSE = "BUTTON_CONNECT_ADRESSE";
	public static String BUTTON_DISCONNECT_ADRESSE = "BUTTON_DISCONNECT_ADRESSE";
	
	public static String BUTTON_SET_CONFIRMATION = "BUTTON_SET_CONFIRMATION";
	public static String BUTTON_CLEAR_CONFIRMATION = "BUTTON_CLEAR_CONFIRMATION";
	
	public static String DAUGHTER_PAGE_ARCHIVE_CONTENTS = "DAUGHTER_PAGE_ARCHIVE_CONTENTS";	
	
}
