package rohstoff.Echo2BusinessLogic.FIBU_KONTEN.REGELN;

public class FIBU_KONTEN_REGELN__CONST {
	public static String MASK_COMPONENT_CONDITION_DAUGHTER = "MASK_COMPONENT_CONDITION_DAUGHTER";

	public static String LIST_COMPONENT_QUELLEN_LAND_TABLE = "LIST_COMPONENT_QUELLEN_LAND_TABLE";
	public static String LIST_COMPONENT_ZIEL_LAND_TABLE = "LIST_COMPONENT_ZIEL_LAND_TABLE";
	
	
}
