package panter.gmbh.Echo2;

public class E2_CONSTANTS_AND_NAMES 
{
	
	public static final String NAME_MODUL_UPLOAD_AND_IMPORT_DATA =			"NAME_MODUL_UPLOAD_AND_IMPORT_DATA";
	public static final String NAME_MODUL_CODEGENERATOR =					"MODUL_CODEGENERATOR";
	public static final String NAME_SHOW_ALL_XML_DEFS_TO_CALL =				"NAME_SHOW_ALL_XML_DEFS_TO_CALL";
	public static final String NAME_MODUL_DBTOOLS = 						"NAME_MODUL_DBTOOLS";
	public static final String NAME_MODUL_SHOW_SESSION_MANAGEMENT = 		"NAME_MODUL_SHOW_SESSION_MANAGEMENT";
	public static final String NAME_MODUL_MAILARCHIV =						"MODUL_MAILARCHIV";

	public static final String NAME_MODUL_CALENDAR_POPUP =					"NAME_MODUL_CALENDAR_POPUP";
	public static final String NAME_MODUL_REPORTS_POPUP =					"NAME_MODUL_REPORTS_POPUP";

	public static final String NAME_MODUL_TODO_LIST =						"NAME_MODUL_TODO_LIST";
	public static final String NAME_MODUL_TODO_MASK =						"NAME_MODUL_TODO_MASK";

	public static final String NAME_MODUL_DEFINEQUERYS_LIST =				"NAME_MODUL_DEFINEQUERYS_LIST";
	public static final String NAME_MODUL_DEFINEQUERYS_MASK =				"NAME_MODUL_DEFINEQUERYS_MASK";

	public static final String NAME_MODUL_MASSMAILER =						"MODUL_MASSMAILER";
	
	//public static final String NAME_MODUL_MANDANTENVERWALTUNG_LISTE =		"NAME_MODUL_MANDANTENVERWALTUNG_LISTE";
	//public static final String NAME_MODUL_MANDANTENVERWALTUNG_MASKE =		"NAME_MODUL_MANDANTENVERWALTUNG_MASKE";

//	public static final String NAME_MODUL_USERVERWALTUNG_LISTE =			"NAME_MODUL_USERVERWALTUNG_LISTE";
//	public static final String NAME_MODUL_USERVERWALTUNG_MASKE =			"NAME_MODUL_USERVERWALTUNG_MASKE";
//	public static final String NAME_MODUL_USERVERWALTUNG_LISTE_POPUP_USERSETTINGS =			"NAME_MODUL_USERVERWALTUNG_LISTE_POPUP_USERSETTINGS";
	
	
	public static final String NAME_MODUL_MODUL_MANAGER_LISTE =				"MODUL_MODUL_MANAGER_LISTE";
	public static final String NAME_MODUL_MODUL_MANAGER_MASKE =				"MODUL_MODUL_MANAGER_MASKE";
	
	public static final String NAME_MODUL_XMLDEFTESTER = 					"MODUL_XMLDEFTESTER";

	public static final String NAME_MODUL_MODULVERWALTUNG = 				"MODUL_MODULVERWALTUNG";
	
	public static final String NAME_MODUL_MANDANTENZUSATZFELDER = 			"MODUL_MANDANTENZUSATZFELDER";
	
	
	public static final String NAME_MODUL_REPORTPIPELINE = 					"MODUL_REPORTPIPELINE";



}
