package panter.gmbh.basics4project.specialViews;

import panter.gmbh.Echo2.MyE2_String;
import panter.gmbh.Echo2.bibE2;
import panter.gmbh.Echo2.Messaging.MyE2_Alarm_Message;
import panter.gmbh.Echo2.Messaging.MyE2_Info_Message;
import panter.gmbh.Echo2.Messaging.bibMSG;
import panter.gmbh.Echo2.__BASIC_MODULS.DBTOOLS.XXX_ViewBuilder;
import panter.gmbh.basics4project.DB_RECORDS.RECLIST_MANDANT;
import panter.gmbh.indep.bibALL;
import panter.gmbh.indep.dataTools.bibDB;
import panter.gmbh.indep.exceptions.myException;

public class build_view_lager_in_out_mengen_preis_vergleich extends XXX_ViewBuilder
{
	
	/*
	 * view fuer die einfache auswertung der mengen einer sorte die mit einem Preis (Zehnerschritte) ins lager oder aus dem Lager
	 * geht 
	 * 
	 */
	
	@Override
	public boolean build_View_forAll_Mandants() throws myException
	{
		
		RECLIST_MANDANT  oRecList = new RECLIST_MANDANT("SELECT * FROM "+bibE2.cTO()+".JD_MANDANT");
		
		String cID_ADRESSE_MANDANT= bibALL.get_RECORD_MANDANT().get_EIGENE_ADRESS_ID_cUF_NN("-1");

		
		//String cID_Mandant = bibALL.get_RECORD_MANDANT().get_ID_MANDANT_cUF();
		
		String c_SQL =  	

			"CREATE OR REPLACE VIEW A#MANDANT#_LAGER_IN_OUT_VERGLEICH AS "+
			" ( "+
			" SELECT "+
			" EK_VK, ROUND(SUM(NVL(MENGE_NETTO,0)),0) AS MENGE_MONAT, "+
			" ZEIT,ADRESSE,ANR1,ARTBEZ1, EINHEIT,EPREIS_10*10 AS PREIS_GERUNDED_AUF_10 "+
            "  "+
			" FROM "+
			" ( "+
			" SELECT "+
			" 'EK' AS EK_VK, "+
			" NVL(JT_VPOS_RG.ANZAHL,0)-NVL(JT_VPOS_RG.ANZAHL_ABZUG_LAGER,0)  AS MENGE_NETTO, "+
			" TO_CHAR(JT_VPOS_RG.AUSFUEHRUNGSDATUM,'YYYY-MM') AS ZEIT, "+
			" JT_ADRESSE.NAME1||' '||JT_ADRESSE.ORT   AS ADRESSE, "+
			" JT_ARTIKEL.ANR1   AS ANR1, "+
			" JT_ARTIKEL.ARTBEZ1   AS ARTBEZ1, "+
			" ROUND(JT_VPOS_RG.EPREIS_RESULT_NETTO_MGE/10,0) AS EPREIS_10, "+
			" NVL(JT_VPOS_RG.EINHEITKURZ,'<EH>') AS EINHEIT, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_START="+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_EIGENLAGER_START_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE="+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N' AND FO1.DEF_QUELLE_ZIEL='EK'  AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_EIGENLAGER_START_FO, "+
            " "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_ZIEL="+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_EIGENLAGER_ZIEL_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE="+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N'  AND FO1.DEF_QUELLE_ZIEL='VK'  AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_EIGENLAGER_ZIEL_FO, "+
            " "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_START<>"+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_FREMDLAGER_START_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE<>"+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N'   AND FO1.DEF_QUELLE_ZIEL='EK'   AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_FREMDLAGER_START_FO, "+
            " "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_ZIEL<>"+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_FREMDLAGER_ZIEL_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE<>"+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N'   AND FO1.DEF_QUELLE_ZIEL='VK'   AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_FREMDLAGER_ZIEL_FO "+
            " "+
			" FROM JT_VPOS_RG "+
			" LEFT OUTER JOIN JT_ADRESSE ON (JT_VPOS_RG.ID_ADRESSE=JT_ADRESSE.ID_ADRESSE) "+
			" LEFT OUTER JOIN JT_ARTIKEL    ON (JT_VPOS_RG.ID_ARTIKEL =JT_ARTIKEL.ID_ARTIKEL) "+
			" WHERE JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD IS NOT NULL "+ 
			" AND JT_VPOS_RG.LAGER_VORZEICHEN=1 "+
			" AND   NVL(JT_VPOS_RG.DELETED,'N')='N' "+
			" AND   JT_VPOS_RG.ID_VPOS_RG_STORNO_VORGAENGER IS NULL "+
			" AND   JT_VPOS_RG.ID_VPOS_RG_STORNO_NACHFOLGER IS NULL "+
			"  "+ 
			" ) "+
			" WHERE (ANZAHL_EIGENLAGER_START_HF+ANZAHL_EIGENLAGER_START_FO)=0 "+ 
			" AND (ANZAHL_FREMDLAGER_START_HF+ANZAHL_FREMDLAGER_START_FO)>0  "+
			" AND (ANZAHL_EIGENLAGER_ZIEL_HF + ANZAHL_EIGENLAGER_ZIEL_FO)=1 "+
			" AND (ANZAHL_FREMDLAGER_ZIEL_HF + ANZAHL_FREMDLAGER_ZIEL_FO)=0 "+
            " "+
			" GROUP BY "+
			" EK_VK,EINHEIT,ZEIT,ADRESSE,ANR1,ARTBEZ1,EINHEIT,EPREIS_10 "+
            " "+
			" UNION "+
            " "+
			" SELECT "+
			" EK_VK, ROUND(SUM(NVL(MENGE_NETTO,0)),0) AS SUM1, "+
			" ZEIT,ADRESSE,ANR1,ARTBEZ1,EINHEIT,EPREIS_10*10 "+
            " "+
			" FROM "+
			" ( "+
			" SELECT "+
			" 'VK' AS EK_VK, "+
			" NVL(JT_VPOS_RG.ANZAHL,0)-NVL(JT_VPOS_RG.ANZAHL_ABZUG_LAGER,0)  AS MENGE_NETTO, "+
			" TO_CHAR(JT_VPOS_RG.AUSFUEHRUNGSDATUM,'YYYY-MM') AS ZEIT, "+
			" JT_ADRESSE.NAME1||' '||JT_ADRESSE.ORT   AS ADRESSE, "+
			" JT_ARTIKEL.ANR1   AS ANR1, "+
			" JT_ARTIKEL.ARTBEZ1   AS ARTBEZ1, "+
			" ROUND(JT_VPOS_RG.EPREIS_RESULT_NETTO_MGE/10,0) AS EPREIS_10, "+
			" NVL(JT_VPOS_RG.EINHEITKURZ,'<EH>') AS EINHEIT, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_START="+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_EIGENLAGER_START_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE="+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N' AND FO1.DEF_QUELLE_ZIEL='EK'  AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_EIGENLAGER_START_FO, "+
            " "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_ZIEL="+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_EIGENLAGER_ZIEL_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE="+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N'  AND FO1.DEF_QUELLE_ZIEL='VK'  AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_EIGENLAGER_ZIEL_FO, "+
            "  "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_START<>"+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_FREMDLAGER_START_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE<>"+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N'   AND FO1.DEF_QUELLE_ZIEL='EK'   AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_FREMDLAGER_START_FO, "+
            "  "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE F1 WHERE F1.ID_ADRESSE_ZIEL<>"+cID_ADRESSE_MANDANT+"  AND F1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD ) AS ANZAHL_FREMDLAGER_ZIEL_HF, "+
			" (SELECT COUNT(*) FROM JT_VPOS_TPA_FUHRE_ORT FO1 WHERE FO1.ID_ADRESSE<>"+cID_ADRESSE_MANDANT+" AND NVL(FO1.DELETED,'N')='N'   AND FO1.DEF_QUELLE_ZIEL='VK'   AND FO1.ID_VPOS_TPA_FUHRE=JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD)  AS ANZAHL_FREMDLAGER_ZIEL_FO "+
            "  "+
			" FROM JT_VPOS_RG "+
			" LEFT OUTER JOIN JT_ADRESSE ON (JT_VPOS_RG.ID_ADRESSE=JT_ADRESSE.ID_ADRESSE) "+
			" LEFT OUTER JOIN JT_ARTIKEL    ON (JT_VPOS_RG.ID_ARTIKEL =JT_ARTIKEL.ID_ARTIKEL) "+
			" WHERE JT_VPOS_RG.ID_VPOS_TPA_FUHRE_ZUGEORD IS NOT NULL "+ 
			" AND JT_VPOS_RG.LAGER_VORZEICHEN=-1 "+
			" AND   NVL(JT_VPOS_RG.DELETED,'N')='N' "+
			" AND   JT_VPOS_RG.ID_VPOS_RG_STORNO_VORGAENGER IS NULL "+
			" AND   JT_VPOS_RG.ID_VPOS_RG_STORNO_NACHFOLGER IS NULL "+
			"  "+
			" ) "+
			" WHERE (ANZAHL_EIGENLAGER_START_HF+ANZAHL_EIGENLAGER_START_FO)=1 "+ 
			" AND (ANZAHL_FREMDLAGER_START_HF+ANZAHL_FREMDLAGER_START_FO)=0 "+ 
			" AND (ANZAHL_EIGENLAGER_ZIEL_HF + ANZAHL_EIGENLAGER_ZIEL_FO)=0 "+
			" AND (ANZAHL_FREMDLAGER_ZIEL_HF + ANZAHL_FREMDLAGER_ZIEL_FO)>0 "+
			" GROUP BY "+
			" EK_VK,EINHEIT,ZEIT,ADRESSE,ANR1,ARTBEZ1,EINHEIT,EPREIS_10 "+
			" ) ";


									

		for (int i=0;i<oRecList.get_vKeyValues().size();i++)
		{
			
			String cSQL = bibALL.ReplaceTeilString(c_SQL,"#MANDANT#",oRecList.get(i).get_ID_MANDANT_cUF());
			
			
			if (bibDB.ExecSQL(cSQL, true))
			{
				MyE2_String cInfo = new MyE2_String("LAGER_IN_OUT_VERGLEICH fuer Mandant: <",true,oRecList.get(i).get_NAME1_cF_NN(""),false, "> erfolgreich erstellt !",true);
				bibMSG.add_MESSAGE(new MyE2_Info_Message(cInfo));
			}
			else
			{
				MyE2_String cInfo = new MyE2_String("LAGER_IN_OUT_VERGLEICH fuer Mandant: <",true,oRecList.get(i).get_NAME1_cF_NN(""),false, "> KONNTE NICHT ERSTELLT WERDEN !",true);
				bibMSG.add_MESSAGE(new MyE2_Alarm_Message(cInfo));
			}
		}
		
		
		return false;
	}

	
	
	
	
	
}
