package panter.gmbh.basics4project.specialViews;

import panter.gmbh.Echo2.MyE2_String;
import panter.gmbh.Echo2.bibE2;
import panter.gmbh.Echo2.Messaging.MyE2_Alarm_Message;
import panter.gmbh.Echo2.Messaging.MyE2_Info_Message;
import panter.gmbh.Echo2.Messaging.bibMSG;
import panter.gmbh.Echo2.__BASIC_MODULS.DBTOOLS.XXX_ViewBuilder;
import panter.gmbh.basics4project.DB_RECORDS.RECLIST_MANDANT;
import panter.gmbh.indep.bibALL;
import panter.gmbh.indep.dataTools.bibDB;
import panter.gmbh.indep.exceptions.myException;

public class build_view_FuhrenEinfacherBewegungssatz extends XXX_ViewBuilder
{
	
	/*
	 * view fuer die einfache auswertung der bewegungen nach den verschiedenen lagern /
	 * Strecke / unbestimmt (gemischt) 
	 * 
	 */
	
	@Override
	public boolean build_View_forAll_Mandants() throws myException
	{
		
		RECLIST_MANDANT  oRecList = new RECLIST_MANDANT("SELECT * FROM "+bibE2.cTO()+".JD_MANDANT");
		
		String cID_ADRESSE_MANDANT= bibALL.get_RECORD_MANDANT().get_EIGENE_ADRESS_ID_cUF_NN("-1");
		
		String cID_Mandant = bibALL.get_RECORD_MANDANT().get_ID_MANDANT_cUF();
		
		String c_SQL =  	" CREATE OR REPLACE VIEW A#MANDANT#_BEWEGUNGSSATZ AS ("+	
			" SELECT FU.ID_VPOS_TPA_FUHRE, NULL AS ID_VPOS_TPA_FUHRE_ORT, FU.STATUS_BUCHUNG , FU.ID_ARTIKEL_BEZ_EK AS ID_ARTIKEL_BEZ, FU.ANTEIL_LADEMENGE_LIEF AS MENGE, FU.ID_ADRESSE_LAGER_ZIEL AS EIGEN_LAGER, 'WE' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"  FROM "+
			"  JT_VPOS_TPA_FUHRE FU "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FP.ID_VPOS_TPA_FUHRE_ORT IS NULL AND FP.EK_VK='EK') "+
			" WHERE FK.TYPUS='IN_LAGER' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, FUO.ID_VPOS_TPA_FUHRE_ORT, FU.STATUS_BUCHUNG ,  FUO.ID_ARTIKEL_BEZ AS ID_ARTIKEL_BEZ, FUO.ANTEIL_LADEMENGE AS MENGE, FU.ID_ADRESSE_LAGER_ZIEL AS EIGEN_LAGER, 'WE' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"   FROM "+
			"  JT_VPOS_TPA_FUHRE_ORT FUO "+
			" INNER JOIN JT_VPOS_TPA_FUHRE FU ON (FU.ID_VPOS_TPA_FUHRE=FUO.ID_VPOS_TPA_FUHRE) "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FUO.ID_VPOS_TPA_FUHRE_ORT = FP.ID_VPOS_TPA_FUHRE_ORT  AND FP.EK_VK='EK') "+
			" WHERE  FK.TYPUS='IN_LAGER' "+
			" AND      FUO.DEF_QUELLE_ZIEL='EK' "+
			"  "+
			" UNION "+
			"  "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, NULL AS ID_VPOS_TPA_FUHRE_ORT,FU.STATUS_BUCHUNG , FU.ID_ARTIKEL_BEZ_VK AS ID_ARTIKEL_BEZ, FU.ANTEIL_ABLADEMENGE_ABN AS MENGE, FU.ID_ADRESSE_LAGER_START AS EIGEN_LAGER, 'WA' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"  FROM "+
			"  JT_VPOS_TPA_FUHRE FU "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FP.ID_VPOS_TPA_FUHRE_ORT IS NULL  AND FP.EK_VK='VK') "+
			" WHERE FK.TYPUS='EX_LAGER' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, FUO.ID_VPOS_TPA_FUHRE_ORT, FU.STATUS_BUCHUNG , FUO.ID_ARTIKEL_BEZ AS ID_ARTIKEL_BEZ, FUO.ANTEIL_ABLADEMENGE AS MENGE, FU.ID_ADRESSE_LAGER_START  AS EIGEN_LAGER, 'WA' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"   FROM "+
			"  JT_VPOS_TPA_FUHRE_ORT FUO "+
			" INNER JOIN JT_VPOS_TPA_FUHRE FU ON (FU.ID_VPOS_TPA_FUHRE=FUO.ID_VPOS_TPA_FUHRE) "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FUO.ID_VPOS_TPA_FUHRE_ORT = FP.ID_VPOS_TPA_FUHRE_ORT  AND FP.EK_VK='VK') "+
			" WHERE  FK.TYPUS='EX_LAGER' "+
			" AND      FUO.DEF_QUELLE_ZIEL='VK' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, NULL AS ID_VPOS_TPA_FUHRE_ORT,FU.STATUS_BUCHUNG ,FU.ID_ARTIKEL_BEZ_EK AS ID_ARTIKEL_BEZ,  FU.ANTEIL_LADEMENGE_LIEF AS MENGE, 0 AS EIGEN_LAGER, 'WE' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"  FROM "+
			"  JT_VPOS_TPA_FUHRE FU "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FP.ID_VPOS_TPA_FUHRE_ORT IS NULL  AND FP.EK_VK='EK') "+
			" WHERE FK.TYPUS='STRECKE' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, FUO.ID_VPOS_TPA_FUHRE_ORT,FU.STATUS_BUCHUNG , FUO.ID_ARTIKEL_BEZ AS ID_ARTIKEL_BEZ,  FUO.ANTEIL_LADEMENGE AS MENGE, 0 AS EIGEN_LAGER, 'WE' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"   FROM "+
			"  JT_VPOS_TPA_FUHRE_ORT FUO "+
			" INNER JOIN JT_VPOS_TPA_FUHRE FU ON (FU.ID_VPOS_TPA_FUHRE=FUO.ID_VPOS_TPA_FUHRE) "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FUO.ID_VPOS_TPA_FUHRE_ORT = FP.ID_VPOS_TPA_FUHRE_ORT   AND FP.EK_VK='EK') "+
			" WHERE  FK.TYPUS='STRECKE' "+
			" AND      FUO.DEF_QUELLE_ZIEL='EK' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, NULL AS ID_VPOS_TPA_FUHRE_ORT,FU.STATUS_BUCHUNG , FU.ID_ARTIKEL_BEZ_VK AS ID_ARTIKEL_BEZ,  FU.ANTEIL_ABLADEMENGE_ABN AS MENGE, 0 AS EIGEN_LAGER, 'WA' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"  FROM "+
			"  JT_VPOS_TPA_FUHRE FU "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FP.ID_VPOS_TPA_FUHRE_ORT IS NULL   AND FP.EK_VK='VK') "+
			" WHERE FK.TYPUS='STRECKE' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, FUO.ID_VPOS_TPA_FUHRE_ORT, FU.STATUS_BUCHUNG , FUO.ID_ARTIKEL_BEZ AS ID_ARTIKEL_BEZ, FUO.ANTEIL_ABLADEMENGE AS MENGE, 0 AS EIGEN_LAGER, 'WA' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"   FROM "+
			"  JT_VPOS_TPA_FUHRE_ORT FUO "+
			" INNER JOIN JT_VPOS_TPA_FUHRE FU ON (FU.ID_VPOS_TPA_FUHRE=FUO.ID_VPOS_TPA_FUHRE) "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FUO.ID_VPOS_TPA_FUHRE_ORT = FP.ID_VPOS_TPA_FUHRE_ORT  AND FP.EK_VK='VK') "+
			" WHERE  FK.TYPUS='STRECKE' "+
			" AND      FUO.DEF_QUELLE_ZIEL='VK' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, NULL AS ID_VPOS_TPA_FUHRE_ORT, FU.STATUS_BUCHUNG ,FU.ID_ARTIKEL_BEZ_EK AS ID_ARTIKEL_BEZ, FU.ANTEIL_LADEMENGE_LIEF AS MENGE, -1 AS EIGEN_LAGER, 'WE' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"  FROM "+
			"  JT_VPOS_TPA_FUHRE FU "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FP.ID_VPOS_TPA_FUHRE_ORT IS NULL   AND FP.EK_VK='EK') "+
			" WHERE FU.ID_ADRESSE_START<>"+cID_ADRESSE_MANDANT+""+
			" AND FK.TYPUS='GEMISCHT' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, FUO.ID_VPOS_TPA_FUHRE_ORT, FU.STATUS_BUCHUNG , FUO.ID_ARTIKEL_BEZ AS ID_ARTIKEL_BEZ,  FUO.ANTEIL_LADEMENGE AS MENGE, -1 AS EIGEN_LAGER, 'WE' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"   FROM "+
			"  JT_VPOS_TPA_FUHRE_ORT FUO "+
			" INNER JOIN JT_VPOS_TPA_FUHRE FU ON (FU.ID_VPOS_TPA_FUHRE=FUO.ID_VPOS_TPA_FUHRE) "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FUO.ID_VPOS_TPA_FUHRE_ORT = FP.ID_VPOS_TPA_FUHRE_ORT   AND FP.EK_VK='EK') "+
			" WHERE  FUO.ID_ADRESSE <> "+cID_ADRESSE_MANDANT+" "+
			" AND      FK.TYPUS='GEMISCHT' "+
			" AND      FUO.DEF_QUELLE_ZIEL='EK' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, NULL AS ID_VPOS_TPA_FUHRE_ORT,FU.STATUS_BUCHUNG , FU.ID_ARTIKEL_BEZ_VK AS ID_ARTIKEL_BEZ,  FU.ANTEIL_ABLADEMENGE_ABN AS MENGE, -1 AS EIGEN_LAGER, 'WA' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"  FROM "+
			"  JT_VPOS_TPA_FUHRE FU "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FP.ID_VPOS_TPA_FUHRE_ORT IS NULL   AND FP.EK_VK='VK') "+
			" WHERE FU.ID_ADRESSE_ZIEL<>"+cID_ADRESSE_MANDANT+" "+
			" AND FK.TYPUS='GEMISCHT' "+
			"  "+
			" UNION "+
			"  "+
			" SELECT FU.ID_VPOS_TPA_FUHRE, FUO.ID_VPOS_TPA_FUHRE_ORT,  FU.STATUS_BUCHUNG , FUO.ID_ARTIKEL_BEZ AS ID_ARTIKEL_BEZ, FUO.ANTEIL_ABLADEMENGE AS MENGE, -1 AS EIGEN_LAGER, 'WA' AS TYP, "+
			" FP.PREIS_AUS_RG,FP.PREIS_RESULT_AUS_RG "+
			"   FROM "+
			"  JT_VPOS_TPA_FUHRE_ORT FUO "+
			" INNER JOIN JT_VPOS_TPA_FUHRE FU ON (FU.ID_VPOS_TPA_FUHRE=FUO.ID_VPOS_TPA_FUHRE) "+ 
			" INNER JOIN A"+cID_Mandant+"_FUHRENKLASSEN FK ON (FU.ID_VPOS_TPA_FUHRE=FK.ID_VPOS_TPA_FUHRE) "+
			" LEFT OUTER  JOIN A"+cID_Mandant+"_FUHRENPREISE  FP ON (FU.ID_VPOS_TPA_FUHRE = FP.ID_VPOS_TPA_FUHRE AND FUO.ID_VPOS_TPA_FUHRE_ORT = FP.ID_VPOS_TPA_FUHRE_ORT   AND FP.EK_VK='VK') "+
			" WHERE  FUO.ID_ADRESSE <> "+cID_ADRESSE_MANDANT+" "+
			" AND      FK.TYPUS='GEMISCHT' "+
			" AND      FUO.DEF_QUELLE_ZIEL='VK' "+
			")";

									

		for (int i=0;i<oRecList.get_vKeyValues().size();i++)
		{
			
			String cSQL = bibALL.ReplaceTeilString(c_SQL,"#MANDANT#",oRecList.get(i).get_ID_MANDANT_cUF());
			
			
			if (bibDB.ExecSQL(cSQL, true))
			{
				MyE2_String cInfo = new MyE2_String("Fuhrenbewegungssatz-View fuer Mandant: <",true,oRecList.get(i).get_NAME1_cF_NN(""),false, "> erfolgreich erstellt !",true);
				bibMSG.add_MESSAGE(new MyE2_Info_Message(cInfo));
			}
			else
			{
				MyE2_String cInfo = new MyE2_String("Fuhrenbewegungssatz-View fuer Mandant: <",true,oRecList.get(i).get_NAME1_cF_NN(""),false, "> KONNTE NICHT ERSTELLT WERDEN !",true);
				bibMSG.add_MESSAGE(new MyE2_Alarm_Message(cInfo));
			}
		}
		
		
		return false;
	}

	
	
	
	
	
}
