package rohstoff.Echo2BusinessLogic.WORKFLOW.LAUFZETTEL;

public enum EnumDisplayOptions {
	SHOW_UNDELETED,
	SHOW_DELETED,
	SHOW_OPEN,
	SHOW_FINISHED,
	SHOW_BESITZER_JA,
	SHOW_BESITZER_NEIN,
	SHOW_BEARBEITER_JA,
	SHOW_BEARBEITER_NEIN,
	
	// nur für SELEKTOR_1
	SHOW_OWN_ONLY,
}
