package rohstoff.Echo2BusinessLogic.REPORT_VERLAUF;

import panter.gmbh.indep.enumtools.IF_enum_4_db;
import panter.gmbh.indep.enumtools.bibENUM;
import panter.gmbh.indep.exceptions.myException;

public enum ENUM_REPORT_CONSTANT implements IF_enum_4_db{
	HM_JASPERREPORT_BASE_NAME		("HM_JASPERREPORT_BASE_NAME")
	,HM_JASPERREPORT_REPORT_PATH	("HM_JASPERREPORT_REPORT_PATH")
	,HM_JASPERREPORT_NAME_WITH_PATH	("HM_JASPERREPORT_NAME_WITH_PATH")
	,JASPERREPORT_REPORT_TARGET_PRINT("JASPERREPORT_REPORT_TARGET_PRINT")
	,JASPERREPORT_REPORT_TARGET_MAIL("JASPERREPORT_REPORT_TARGET_MAIL")
	,LIST_TARGET_TYPE				("LIST_TARGET_TYPE")
	,___TYPE						("___TYPE")
	,VALUE_PRINT					("PRINT")
	,VALUE_MAIL						("MAIL")
	,VALUE_PREVIEW 					("PREVIEW")
	,PRINT_ADDONS					("PRINT_ADDONS")
	,PREVIEW_YN						("PREVIEW_YN")
	,SYS_USERNAME					("SYS_USERNAME")
	,SYS_KUERZEL					("SYS_KUERZEL")
	,SYS_USERID						("SYS_USERID")
	,SYS_MANDANT_ID					("SYS_MANDANT_ID")
	,SYS_ID_ADRESSE_MANDANT			("SYS_ID_ADRESSE_MANDANT")
	,SYS_REPORTDATE					("SYS_REPORTDATE")
	,SYS_REPORTTARGET				("SYS_REPORTTARGET")
	,SYS_COPYNUMBER					("SYS_COPYNUMBER")
	,SYS_ACTUAL_COPY				("SYS_ACTUAL_COPY")
	,SYS_ACTUAL_COPY_TEXT			("SYS_ACTUAL_COPY_TEXT")
	,SYS_HASHMAP_4_RETURN			("SYS_HASHMAP_4_RETURN")
	,SYS_USER_IS_ADMIN				("SYS_USER_IS_ADMIN")
	,SYS_USER_IS_GESCHAEFTSFUEHRER	("SYS_USER_IS_GESCHAEFTSFUEHRER")
	,SYS_ARCHIVBASEPATH				("SYS_ARCHIVBASEPATH")
	,SYS_KENNSTRING_BATCHDRUCK		("SYS_KENNSTRING_BATCHDRUCK")
	,SYS_MANDANT_ID_4_REPORTPATH	("SYS_MANDANT_ID_4_REPORTPATH")	
	,SYS_REPORTBASEPATH				("SYS_REPORTBASEPATH") 	
	,SYS_REPORTPATH_ALL				("SYS_REPORTPATH_ALL") 		
	,SYS_REPORTNAME					("SYS_REPORTNAME") 		
	,SYS_REPORTPATH					("SYS_REPORTPATH") 		
	,SYS_REPORTADDONPATH			("SYS_REPORTADDONPATH") 
	,SYS_REPORTIMAGEPATH			("SYS_REPORTIMAGEPATH") 
	,SYS_REPORTFILE					("SYS_REPORTFILE") 		
	,SYS_MANDANT_TELEFON			("SYS_MANDANT_TELEFON") 		
	,SYS_MANDANT_TELEFAX			("SYS_MANDANT_TELEFAX") 		
	,SYS_MANDANT_EMAIL				("SYS_MANDANT_EMAIL") 			
	,SYS_MANDANT_WWW				("SYS_MANDANT_WWW") 			
	,SYS_MANDANT_BANK				("SYS_MANDANT_BANK") 			
	,SYS_MANDANT_BLZ				("SYS_MANDANT_BLZ") 			
	,SYS_MANDANT_KONTO				("SYS_MANDANT_KONTO") 			
	,SYS_MANDANT_REGISTERGERICHT	("SYS_MANDANT_REGISTERGERICHT")
	,SYS_MANDANT_HANDELSREG_NR		("SYS_MANDANT_HANDELSREG_NR") 	
	,SYS_MANDANT_USTID				("SYS_MANDANT_USTID") 			
	,SYS_MANDANT_STEUERNR			("SYS_MANDANT_STEUERNR")		
	,SYS_HASHMAP_MANDANT_ZUSAETZE	("SYS_HASHMAP_MANDANT_ZUSAETZE")
	,SYS_REPORTPATH_MANDANT			("SYS_REPORTPATH_MANDANT")
	,__HM_TEMP_FILE_CREATED			("__HM_TEMP_FILE_CREATED")
	;
	
	private String parameter = "";
	private ENUM_REPORT_CONSTANT(String oParamater) {
		this.parameter =oParamater;
	}

	@Override
	public String db_val() {
		return name();
	}

	@Override
	public String user_text() {
		return parameter;
	}

	@Override
	public String[][] get_dd_Array(boolean emptyPairInFront) throws myException {
		return bibENUM.dd_array(ENUM_REPORT_CONSTANT.values(), emptyPairInFront);
	}

}
