package panter.gmbh.basics4project.validation;

import java.util.Vector;

import panter.gmbh.Echo2.MyE2_String;
import panter.gmbh.Echo2.AgentsAndValidators.E2_ButtonAUTHValidator;
import panter.gmbh.Echo2.Messaging.MyE2_Info_Message;
import panter.gmbh.Echo2.Messaging.MyE2_MessageVector;
import panter.gmbh.Echo2.Messaging.bibMSG;
import panter.gmbh.Echo2.RB.COMP.RB_lab;
import panter.gmbh.basics4project.E2_MODULNAME_ENUM;
import panter.gmbh.basics4project.DB_ENUMS.BUTTON;
import panter.gmbh.basics4project.DB_ENUMS._TAB;
import panter.gmbh.indep.S;
import panter.gmbh.indep.dataTools.RECORD2.Rec20;
import panter.gmbh.indep.dataTools.RECORD2.RecList20;
import panter.gmbh.indep.dataTools.TERM._TermCONST.COMP;
import panter.gmbh.indep.dataTools.TERM.vgl;
import panter.gmbh.indep.dataTools.TERM.SELECT.SEL;
import panter.gmbh.indep.enumtools.IF_enum_4_db;
import panter.gmbh.indep.exceptions.myException;

public enum ENUM_VALIDATION implements IF_enum_validation{

	
	VKOPF_KON_EK_NEW(		ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.NEW)
	,VKOPF_KON_EK_EDIT(		ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.EDIT)
	,VKOPF_KON_EK_VIEW(		ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.VIEW)
	,VKOPF_KON_EK_DELETE(	ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.DELETE)
	,VKOPF_KON_EK_ATTACH(	ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	,VKOPF_KON_VK_NEW(		ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.NEW)
	,VKOPF_KON_VK_EDIT(		ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.EDIT)
	,VKOPF_KON_VK_VIEW(		ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.VIEW)
	,VKOPF_KON_VK_DELETE(	ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.DELETE)
	,VKOPF_KON_VK_ATTACH(	ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.KOPFSATZ, ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	,VPOS_KON_EK_NEW(		ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.NEW)
	,VPOS_KON_EK_EDIT(		ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.EDIT)
	,VPOS_KON_EK_VIEW(		ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.VIEW)
	,VPOS_KON_EK_DELETE(	ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.DELETE)
	,VPOS_KON_EK_ATTACH(	ENUM_VALID_THEME.KONTRAKT_EINKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	,VPOS_KON_VK_NEW(		ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.NEW)
	,VPOS_KON_VK_EDIT(		ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.EDIT)
	,VPOS_KON_VK_VIEW(		ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.VIEW)
	,VPOS_KON_VK_DELETE(	ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.DELETE)
	,VPOS_KON_VK_ATTACH(	ENUM_VALID_THEME.KONTRAKT_VERKAUF, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	
	,AH7_PROFIL_EDIT( 		ENUM_VALID_THEME.AH7_PROFIL, ENUM_VALID_BASICFUNCTION.EDIT)
	,AH7_PROFIL_VIEW( 		ENUM_VALID_THEME.AH7_PROFIL, ENUM_VALID_BASICFUNCTION.VIEW)
	,AH7_PROFIL_NEW( 		ENUM_VALID_THEME.AH7_PROFIL, ENUM_VALID_BASICFUNCTION.NEW)
	,AH7_PROFIL_DELETE( 	ENUM_VALID_THEME.AH7_PROFIL, ENUM_VALID_BASICFUNCTION.DELETE)
	,AH7_PROFIL_EXPORT_SQL(	ENUM_VALID_THEME.AH7_PROFIL, ENUM_VALID_BASICFUNCTION.EXPORT_SQL)
	
	
	,AH7_STEUER_REFRESHLIST( ENUM_VALID_THEME.AH7_STEUERDATEI, ENUM_VALID_BASICFUNCTION.REQUERYLIST)
	,AH7_STEUER_AUTOMATIC_SETTING( ENUM_VALID_THEME.AH7_STEUERDATEI, ENUM_VALID_BASICFUNCTION.REQUERYLIST)
	,AH7_STEUERDATEI_EDIT( 		ENUM_VALID_THEME.AH7_STEUERDATEI, ENUM_VALID_BASICFUNCTION.EDIT)
	,AH7_STEUERDATEI_VIEW( 		ENUM_VALID_THEME.AH7_STEUERDATEI, ENUM_VALID_BASICFUNCTION.VIEW)
	,AH7_STEUERDATEI_NEW( 		ENUM_VALID_THEME.AH7_STEUERDATEI, ENUM_VALID_BASICFUNCTION.NEW)
	,AH7_STEUERDATEI_DELETE( 	ENUM_VALID_THEME.AH7_STEUERDATEI, ENUM_VALID_BASICFUNCTION.DELETE)
	
	
	//2017-11-13: @sebastien maskdefinition und maskdefinitioncell werkzeug
	,MASK_DEF_EDIT( 		ENUM_VALID_THEME.MASK_DEFINITION, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,MASK_DEF_VIEW( 		ENUM_VALID_THEME.MASK_DEFINITION, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,MASK_DEF_NEW( 			ENUM_VALID_THEME.MASK_DEFINITION, 		ENUM_VALID_BASICFUNCTION.NEW)
	,MASK_DEF_DELETE( 		ENUM_VALID_THEME.MASK_DEFINITION, 		ENUM_VALID_BASICFUNCTION.DELETE)
	
	,MASK_DEF_CELL_EDIT( 	ENUM_VALID_THEME.MASK_DEFINITION_CELL, ENUM_VALID_BASICFUNCTION.EDIT)
	,MASK_DEF_CELL_VIEW( 	ENUM_VALID_THEME.MASK_DEFINITION_CELL, ENUM_VALID_BASICFUNCTION.VIEW)
	,MASK_DEF_CELL_NEW( 	ENUM_VALID_THEME.MASK_DEFINITION_CELL, ENUM_VALID_BASICFUNCTION.NEW)
	,MASK_DEF_CELL_DELETE( 	ENUM_VALID_THEME.MASK_DEFINITION_CELL, ENUM_VALID_BASICFUNCTION.DELETE)
	
	,MENUECALL_AH7_PROFILE(		E2_MODULNAME_ENUM.MODUL.AH7_PROFIL_LIST)
	,MENUECALL_AH7_STEUERDATEI(	E2_MODULNAME_ENUM.MODUL.AH7_STEUERDATEI_LISTE)
	
	,MESSAGE_PROVIDER_EDIT( 	ENUM_VALID_THEME.MESSAGE_PROVIDER, ENUM_VALID_BASICFUNCTION.EDIT)
	,MESSAGE_PROVIDER_VIEW( 	ENUM_VALID_THEME.MESSAGE_PROVIDER, ENUM_VALID_BASICFUNCTION.VIEW)
	,MESSAGE_PROVIDER_NEW( 		ENUM_VALID_THEME.MESSAGE_PROVIDER, ENUM_VALID_BASICFUNCTION.NEW)
	,MESSAGE_PROVIDER_DELETE( 	ENUM_VALID_THEME.MESSAGE_PROVIDER, ENUM_VALID_BASICFUNCTION.DELETE)
	
	,CONTAINER_NEW ( ENUM_VALID_THEME.CONTAINER, ENUM_VALID_BASICFUNCTION.NEW)
	,CONTAINER_VIEW ( ENUM_VALID_THEME.CONTAINER, ENUM_VALID_BASICFUNCTION.VIEW)
	,CONTAINER_EDIT ( ENUM_VALID_THEME.CONTAINER, ENUM_VALID_BASICFUNCTION.EDIT)
	,CONTAINER_DELETE ( ENUM_VALID_THEME.CONTAINER, ENUM_VALID_BASICFUNCTION.DELETE)
	
	,CONTAINERTYP_EDIT( 	ENUM_VALID_THEME.CONTAINERTYP, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,CONTAINERTYP_VIEW( 	ENUM_VALID_THEME.CONTAINERTYP, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,CONTAINERTYP_NEW( 		ENUM_VALID_THEME.CONTAINERTYP, 	ENUM_VALID_BASICFUNCTION.NEW)
	,CONTAINERTYP_DELETE( 	ENUM_VALID_THEME.CONTAINERTYP, 	ENUM_VALID_BASICFUNCTION.DELETE)
	
	,BG_LAGER_BEWEGUNG_EDIT (ENUM_VALID_THEME.BG_LAGER_BEWEGUNG, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,BG_LAGER_BEWEGUNG_VIEW (ENUM_VALID_THEME.BG_LAGER_BEWEGUNG, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,BG_LAGER_BEWEGUNG_NEW (ENUM_VALID_THEME.BG_LAGER_BEWEGUNG, 			ENUM_VALID_BASICFUNCTION.NEW)
	,BG_LAGER_BEWEGUNG_DELETE (ENUM_VALID_THEME.BG_LAGER_BEWEGUNG, 		ENUM_VALID_BASICFUNCTION.DELETE)
	
	
 	,FUHREN_KOSTEN_TYP_EDIT( 	ENUM_VALID_THEME.FUHREN_KOSTEN_TYP, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,FUHREN_KOSTEN_TYP_VIEW( 	ENUM_VALID_THEME.FUHREN_KOSTEN_TYP, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,FUHREN_KOSTEN_TYP_NEW( 	ENUM_VALID_THEME.FUHREN_KOSTEN_TYP, 	ENUM_VALID_BASICFUNCTION.NEW)
	,FUHREN_KOSTEN_TYP_DELETE( 	ENUM_VALID_THEME.FUHREN_KOSTEN_TYP, 	ENUM_VALID_BASICFUNCTION.DELETE)

	,BG_LAGER_SALDO_NEW (ENUM_VALID_THEME.BG_LAGER_SALDO, 			ENUM_VALID_BASICFUNCTION.NEW)
	,BG_LAGER_SALDO_SPLIT (ENUM_VALID_THEME.BG_LAGER_SALDO, 		ENUM_VALID_BASICFUNCTION.NEW)

	,SANKTION_ADRESSENSCHLEIFE(ENUM_VALID_THEME.SANKTION_TABELLE,  	ENUM_VALID_BASICFUNCTION.LIST_ITERATION)
	
	,BORDERCROSSING_ARTIKEL_NEW( ENUM_VALID_THEME.BORDERCROSSING_ARTIKEL, ENUM_VALID_BASICFUNCTION.NEW)
	,BORDERCROSSING_ARTIKEL_EDIT( ENUM_VALID_THEME.BORDERCROSSING_ARTIKEL, ENUM_VALID_BASICFUNCTION.EDIT)
	,BORDERCROSSING_ARTIKEL_VIEW( ENUM_VALID_THEME.BORDERCROSSING_ARTIKEL, ENUM_VALID_BASICFUNCTION.VIEW)
	,BORDERCROSSING_ARTIKEL_DELETE( ENUM_VALID_THEME.BORDERCROSSING_ARTIKEL, ENUM_VALID_BASICFUNCTION.DELETE)
	
  	,TAX_GROUP_EDIT( 	ENUM_VALID_THEME.TAX_GROUP, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,TAX_GROUP_VIEW( 	ENUM_VALID_THEME.TAX_GROUP, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,TAX_GROUP_NEW( 	ENUM_VALID_THEME.TAX_GROUP, 	ENUM_VALID_BASICFUNCTION.NEW)
	,TAX_GROUP_DELETE( 	ENUM_VALID_THEME.TAX_GROUP, 	ENUM_VALID_BASICFUNCTION.DELETE)

	//2018-06-25: report verlauf nur bearbeitung und anzeige
	,REPORT_LOG_EDIT( 	ENUM_VALID_THEME.REPORT_LOG, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,REPORT_LOG_VIEW( 	ENUM_VALID_THEME.REPORT_LOG, 		ENUM_VALID_BASICFUNCTION.VIEW)
	
	
	//2018-07-12: neuer block fuer die Handelsdefinitionen
	,HANDELSDEFINITIONEN_NEW( ENUM_VALID_THEME.HANDELSDEFINITIONEN, 	ENUM_VALID_BASICFUNCTION.NEW)
	,HANDELSDEFINITIONEN_EDIT( ENUM_VALID_THEME.HANDELSDEFINITIONEN, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,HANDELSDEFINITIONEN_VIEW( ENUM_VALID_THEME.HANDELSDEFINITIONEN, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,HANDELSDEFINITIONEN_DELETE( ENUM_VALID_THEME.HANDELSDEFINITIONEN, 	ENUM_VALID_BASICFUNCTION.DELETE)

	//2018-07-20: reports auf sql-basis
 	,REPORTING_QUERY_EDIT( 	ENUM_VALID_THEME.REPORTING_QUERY, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,REPORTING_QUERY_VIEW( 	ENUM_VALID_THEME.REPORTING_QUERY, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,REPORTING_QUERY_NEW( 		ENUM_VALID_THEME.REPORTING_QUERY, 	ENUM_VALID_BASICFUNCTION.NEW)
	,REPORTING_QUERY_DELETE( 	ENUM_VALID_THEME.REPORTING_QUERY, 	ENUM_VALID_BASICFUNCTION.DELETE)

	//2018-07-20: reports auf sql-basis
 	,BANKEN_STAMM_EDIT( 	ENUM_VALID_THEME.BANKEN_STAMM, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,BANKEN_STAMM_VIEW( 	ENUM_VALID_THEME.BANKEN_STAMM, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,BANKEN_STAMM_NEW( 		ENUM_VALID_THEME.BANKEN_STAMM, 	ENUM_VALID_BASICFUNCTION.NEW)
	,BANKEN_STAMM_DELETE( 	ENUM_VALID_THEME.BANKEN_STAMM, 	ENUM_VALID_BASICFUNCTION.DELETE)
	
	
	
    //2018-08-28: neues Hilfemodul
	,HILFETEXT_EDIT( 	ENUM_VALID_THEME.HILFETEXT, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,HILFETEXT_VIEW( 	ENUM_VALID_THEME.HILFETEXT, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,HILFETEXT_NEW( 	ENUM_VALID_THEME.HILFETEXT, 		ENUM_VALID_BASICFUNCTION.NEW)
	,HILFETEXT_DELETE( 	ENUM_VALID_THEME.HILFETEXT, 		ENUM_VALID_BASICFUNCTION.DELETE)
	,HILFETEXT_ATTACHMENT( 	ENUM_VALID_THEME.HILFETEXT, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	//2018-11-08: neues Lagerhaltungsmodul
	,LAGER_BOX_EDIT( 				ENUM_VALID_THEME.LAGER_BOX, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,LAGER_BOX_VIEW( 				ENUM_VALID_THEME.LAGER_BOX, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,LAGER_BOX_NEW( 				ENUM_VALID_THEME.LAGER_BOX, 		ENUM_VALID_BASICFUNCTION.NEW)
	,LAGER_BOX_DELETE( 				ENUM_VALID_THEME.LAGER_BOX, 		ENUM_VALID_BASICFUNCTION.DELETE)
	,LAGER_BOX_ATTACHMENT( 			ENUM_VALID_THEME.LAGER_BOX, 		ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	,LAGER_PALETTE_EDIT( 			ENUM_VALID_THEME.LAGER_PALETTE, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,LAGER_PALETTE_VIEW( 			ENUM_VALID_THEME.LAGER_PALETTE, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,LAGER_PALETTE_NEW( 			ENUM_VALID_THEME.LAGER_PALETTE, 	ENUM_VALID_BASICFUNCTION.NEW)
	,LAGER_PALETTE_DELETE( 			ENUM_VALID_THEME.LAGER_PALETTE, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,LAGER_PALETTE_ATTACHMENT( 		ENUM_VALID_THEME.LAGER_PALETTE, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	,LAGER_PALETTE_BOX_EDIT( 		ENUM_VALID_THEME.LAGER_PALETTE_BOX,	ENUM_VALID_BASICFUNCTION.EDIT)
	,LAGER_PALETTE_BOX_VIEW( 		ENUM_VALID_THEME.LAGER_PALETTE_BOX, ENUM_VALID_BASICFUNCTION.VIEW)
	,LAGER_PALETTE_BOX_NEW( 		ENUM_VALID_THEME.LAGER_PALETTE_BOX, ENUM_VALID_BASICFUNCTION.NEW)
	,LAGER_PALETTE_BOX_DELETE( 		ENUM_VALID_THEME.LAGER_PALETTE_BOX, ENUM_VALID_BASICFUNCTION.DELETE)
	,LAGER_PALETTE_BOX_ATTACHMENT( 	ENUM_VALID_THEME.LAGER_PALETTE_BOX, ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
 	,BG_TRANSPORT_EDIT( 	ENUM_VALID_THEME.BG_TRANSPORT, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,BG_TRANSPORT_VIEW( 	ENUM_VALID_THEME.BG_TRANSPORT, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,BG_TRANSPORT_NEW( 		ENUM_VALID_THEME.BG_TRANSPORT, 		ENUM_VALID_BASICFUNCTION.NEW)
	,BG_TRANSPORT_DELETE( 	ENUM_VALID_THEME.BG_TRANSPORT, 		ENUM_VALID_BASICFUNCTION.DELETE)
	,BG_TRANSPORT_STORNO( 	ENUM_VALID_THEME.BG_TRANSPORT, 		ENUM_VALID_BASICFUNCTION.STORNO)
	,BG_TRANSPORT_ATTACHMENT( 	ENUM_VALID_THEME.BG_TRANSPORT, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	
 	,ADRESSE_INFO_EDIT( 	ENUM_VALID_THEME.ADRESSE_INFO, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,ADRESSE_INFO_VIEW( 	ENUM_VALID_THEME.ADRESSE_INFO, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,ADRESSE_INFO_NEW( 		ENUM_VALID_THEME.ADRESSE_INFO, 		ENUM_VALID_BASICFUNCTION.NEW)
	,ADRESSE_INFO_DELETE( 	ENUM_VALID_THEME.ADRESSE_INFO, 		ENUM_VALID_BASICFUNCTION.DELETE)
	,ADRESSE_INFO_ATTACHMENT( 	ENUM_VALID_THEME.ADRESSE_INFO, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

 	,ADRESSE_MELDUNG_EDIT( 		ENUM_VALID_THEME.ADRESSE_MELDUNG, ENUM_VALID_BASICFUNCTION.EDIT)
	,ADRESSE_MELDUNG_VIEW( 		ENUM_VALID_THEME.ADRESSE_MELDUNG, ENUM_VALID_BASICFUNCTION.VIEW)
	,ADRESSE_MELDUNG_NEW( 		ENUM_VALID_THEME.ADRESSE_MELDUNG, ENUM_VALID_BASICFUNCTION.NEW)
	,ADRESSE_MELDUNG_DELETE( 	ENUM_VALID_THEME.ADRESSE_MELDUNG, ENUM_VALID_BASICFUNCTION.DELETE)
	,ADRESSE_MELDUNG_ATTACHMENT(ENUM_VALID_THEME.ADRESSE_MELDUNG, ENUM_VALID_BASICFUNCTION.ATTACHMENT)

 	,ADRESSE_EDIT( 				ENUM_VALID_THEME.ADRESSE, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,ADRESSE_VIEW( 				ENUM_VALID_THEME.ADRESSE, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,ADRESSE_NEW( 				ENUM_VALID_THEME.ADRESSE, 		ENUM_VALID_BASICFUNCTION.NEW)
	,ADRESSE_DELETE( 			ENUM_VALID_THEME.ADRESSE, 		ENUM_VALID_BASICFUNCTION.DELETE)
	,ADRESSE_ATTACHMENT(		ENUM_VALID_THEME.ADRESSE, 		ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	,ADRESSE_INFOBUTTON(		ENUM_VALID_THEME.ADRESSE, 		ENUM_VALID_BASICFUNCTION.ZEIGE_ADDONS)

 	,ARTIKEL_EDIT( 				ENUM_VALID_THEME.ARTIKEL, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,ARTIKEL_VIEW( 				ENUM_VALID_THEME.ARTIKEL, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,ARTIKEL_NEW( 				ENUM_VALID_THEME.ARTIKEL, 		ENUM_VALID_BASICFUNCTION.NEW)
	,ARTIKEL_DELETE( 			ENUM_VALID_THEME.ARTIKEL, 		ENUM_VALID_BASICFUNCTION.DELETE)
	,ARTIKEL_ATTACHMENT(		ENUM_VALID_THEME.ARTIKEL, 		ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	,ARTIKEL_INFOBUTTON(		ENUM_VALID_THEME.ARTIKEL, 		ENUM_VALID_BASICFUNCTION.ZEIGE_ADDONS)
	,ARTIKEL_LAENDER_ZOLLTARIF( ENUM_VALID_THEME.ARTIKEL, 		"LAENDERZOLLTARIFE", "Änderung der Länderzolltarif-Strukturen")
	
	,LAUFZETTEL_EINTRAG_EDIT(   ENUM_VALID_THEME.LAUFZETTE_SIMPLE, ENUM_VALID_BASICFUNCTION.EDIT)
	,LAUFZETTEL_EINTRAG_VIEW(   ENUM_VALID_THEME.LAUFZETTE_SIMPLE, ENUM_VALID_BASICFUNCTION.VIEW)
	,LAUFZETTEL_EINTRAG_NEW(   ENUM_VALID_THEME.LAUFZETTE_SIMPLE, ENUM_VALID_BASICFUNCTION.NEW)
	,LAUFZETTEL_EINTRAG_DELETE(   ENUM_VALID_THEME.LAUFZETTE_SIMPLE, ENUM_VALID_BASICFUNCTION.DELETE)
	,LAUFZETTEL_EINTRAG_ATTACHMENT(   ENUM_VALID_THEME.LAUFZETTE_SIMPLE, ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	,VPOS_STD_EK_NEW(		ENUM_VALID_THEME.ABNAHMEANGEBOT, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.NEW)
	,VPOS_STD_EK_EDIT(		ENUM_VALID_THEME.ABNAHMEANGEBOT, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.EDIT)
	,VPOS_STD_EK_VIEW(		ENUM_VALID_THEME.ABNAHMEANGEBOT, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.VIEW)
	,VPOS_STD_EK_DELETE(	ENUM_VALID_THEME.ABNAHMEANGEBOT, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.DELETE)
	,VPOS_STD_EK_ATTACH(	ENUM_VALID_THEME.ABNAHMEANGEBOT, ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	,VPOS_STD_VK_NEW(		ENUM_VALID_THEME.ANGEBOT, 		ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.NEW)
	,VPOS_STD_VK_EDIT(		ENUM_VALID_THEME.ANGEBOT, 		ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.EDIT)
	,VPOS_STD_VK_VIEW(		ENUM_VALID_THEME.ANGEBOT, 		ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.VIEW)
	,VPOS_STD_VK_DELETE(	ENUM_VALID_THEME.ANGEBOT, 		ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.DELETE)
	,VPOS_STD_VK_ATTACH(	ENUM_VALID_THEME.ANGEBOT, 		ENUM_VALID_SUBTHEME.POSITIONSSATZ, ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	,BG_ATOM_EDIT( 			ENUM_VALID_THEME.BG_ATOM, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,BG_ATOM_VIEW( 			ENUM_VALID_THEME.BG_ATOM, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,BG_ATOM_NEW( 			ENUM_VALID_THEME.BG_ATOM, 	ENUM_VALID_BASICFUNCTION.NEW)
	,BG_ATOM_DELETE( 		ENUM_VALID_THEME.BG_ATOM, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,BG_ATOM_ATTACHMENT( 	ENUM_VALID_THEME.BG_ATOM, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
 	,DIENSTLEISTUNG_PROFIL_EDIT( 		ENUM_VALID_THEME.DIENSTLEISTUNG_PROFIL, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,DIENSTLEISTUNG_PROFIL_VIEW( 		ENUM_VALID_THEME.DIENSTLEISTUNG_PROFIL, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,DIENSTLEISTUNG_PROFIL_NEW( 		ENUM_VALID_THEME.DIENSTLEISTUNG_PROFIL, 	ENUM_VALID_BASICFUNCTION.NEW)
	,DIENSTLEISTUNG_PROFIL_DELETE( 		ENUM_VALID_THEME.DIENSTLEISTUNG_PROFIL, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,DIENSTLEISTUNG_PROFIL_ATTACHMENT( 	ENUM_VALID_THEME.DIENSTLEISTUNG_PROFIL, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	,RECHNUNGSDRUCK_DATUM(ENUM_VALID_THEME.RECHUNGSDRUCK_DATUMSWERTE,"Rechnungsdruck/Datumsänderung","Erlaubnis, beim Rechnungsdruck Datumsfelder zu öffnen")
	
	,WARENBEWEGUNGEN_ENTFERNUNGEN_BERECHNEN(ENUM_VALID_THEME.WARENBEWEGUNGEN,"Warenbewegungsfunktionen","Entfernungsberechnung im Batch durchführen")
	
	
	//2020-01-27
 	,REP_VARIANTEN_LISTE_EDIT( 	ENUM_VALID_THEME.REP_VARIANTEN, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,REP_VARIANTEN_LISTE_VIEW( 	ENUM_VALID_THEME.REP_VARIANTEN, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,REP_VARIANTEN_LISTE_NEW( 		ENUM_VALID_THEME.REP_VARIANTEN, 	ENUM_VALID_BASICFUNCTION.NEW)
	,REP_VARIANTEN_LISTE_DELETE( 	ENUM_VALID_THEME.REP_VARIANTEN, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,REP_VARIANTEN_LISTE_ATTACHMENT( 	ENUM_VALID_THEME.REP_VARIANTEN, ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	
 	,WK_RB_LIST_EDIT( 		ENUM_VALID_THEME.WIEGEKARTE_RB, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,WK_RB_LIST_VIEW( 		ENUM_VALID_THEME.WIEGEKARTE_RB, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,WK_RB_LIST_NEW( 		ENUM_VALID_THEME.WIEGEKARTE_RB, 	ENUM_VALID_BASICFUNCTION.NEW)
	,WK_RB_LIST_DELETE( 	ENUM_VALID_THEME.WIEGEKARTE_RB, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,WK_RB_LIST_ATTACHMENT( ENUM_VALID_THEME.WIEGEKARTE_RB, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	,WK_RB_LIST_STORNO     (ENUM_VALID_THEME.WIEGEKARTE_RB,     ENUM_VALID_BASICFUNCTION.STORNO)
	
	
 	,TEXT_LISTE_VORLAGE_EDIT( 	ENUM_VALID_THEME.TEXT_LISTE_VORLAGE, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,TEXT_LISTE_VORLAGE_VIEW( 	ENUM_VALID_THEME.TEXT_LISTE_VORLAGE, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,TEXT_LISTE_VORLAGE_NEW( 		ENUM_VALID_THEME.TEXT_LISTE_VORLAGE, 	ENUM_VALID_BASICFUNCTION.NEW)
	,TEXT_LISTE_VORLAGE_DELETE( 	ENUM_VALID_THEME.TEXT_LISTE_VORLAGE, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,TEXT_LISTE_VORLAGE_ATTACHMENT( 	ENUM_VALID_THEME.TEXT_LISTE_VORLAGE, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

 	,WK_RB_CHILD_ABZUG_GEBINDE_EDIT( 	ENUM_VALID_THEME.WIEGEKARTE_RB_CHILD_ABZUG, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,WK_RB_CHILD_ABZUG_GEBINDE_VIEW( 	ENUM_VALID_THEME.WIEGEKARTE_RB_CHILD_ABZUG, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,WK_RB_CHILD_ABZUG_GEBINDE_NEW( 		ENUM_VALID_THEME.WIEGEKARTE_RB_CHILD_ABZUG, 	ENUM_VALID_BASICFUNCTION.NEW)
	,WK_RB_CHILD_ABZUG_GEBINDE_DELETE( 	ENUM_VALID_THEME.WIEGEKARTE_RB_CHILD_ABZUG, 	 ENUM_VALID_BASICFUNCTION.DELETE)
	,WK_RB_CHILD_ABZUG_GEBINDE_ATTACHMENT( 	ENUM_VALID_THEME.WIEGEKARTE_RB_CHILD_ABZUG, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	,MWSTSCHLUESSEL_OLD_EDIT( 				ENUM_VALID_THEME.MWSTSCHLUESSEL_OLD, 	ENUM_VALID_BASICFUNCTION.EDIT)
	,MWSTSCHLUESSEL_OLD_VIEW( 				ENUM_VALID_THEME.MWSTSCHLUESSEL_OLD, 	ENUM_VALID_BASICFUNCTION.VIEW)
	,MWSTSCHLUESSEL_OLD_NEW( 				ENUM_VALID_THEME.MWSTSCHLUESSEL_OLD, 	ENUM_VALID_BASICFUNCTION.NEW)
	,MWSTSCHLUESSEL_OLD_DELETE( 			ENUM_VALID_THEME.MWSTSCHLUESSEL_OLD, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,MWSTSCHLUESSEL_OLD_ATTACHMENT( 		ENUM_VALID_THEME.MWSTSCHLUESSEL_OLD, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

 	,WK_RB_CHILD_MGE_ABZ_EDIT( 			ENUM_VALID_THEME.WIEGEKARTE_RB_MGE_ABZ, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,WK_RB_CHILD_MGE_ABZ_VIEW( 			ENUM_VALID_THEME.WIEGEKARTE_RB_MGE_ABZ, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,WK_RB_CHILD_MGE_ABZ_NEW( 			ENUM_VALID_THEME.WIEGEKARTE_RB_MGE_ABZ, 	ENUM_VALID_BASICFUNCTION.NEW)
	,WK_RB_CHILD_MGE_ABZ_DELETE( 		ENUM_VALID_THEME.WIEGEKARTE_RB_MGE_ABZ, 	 ENUM_VALID_BASICFUNCTION.DELETE)
	,WK_RB_CHILD_MGE_ABZ_ATTACHMENT( 	ENUM_VALID_THEME.WIEGEKARTE_RB_MGE_ABZ, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	
	,ZOLLTARIFNUMMER_EDIT( 				ENUM_VALID_THEME.ZOLLTARIFNUMMER, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,ZOLLTARIFNUMMER_VIEW( 				ENUM_VALID_THEME.ZOLLTARIFNUMMER, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,ZOLLTARIFNUMMER_NEW( 				ENUM_VALID_THEME.ZOLLTARIFNUMMER, 	ENUM_VALID_BASICFUNCTION.NEW)
	,ZOLLTARIFNUMMER_DELETE( 			ENUM_VALID_THEME.ZOLLTARIFNUMMER, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,ZOLLTARIFNUMMER_ATTACHMENT( 		ENUM_VALID_THEME.ZOLLTARIFNUMMER, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

	//2020-11-05: tax-modul neu
 	,TAX_EDIT( 	ENUM_VALID_THEME.TAX, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,TAX_VIEW( 	ENUM_VALID_THEME.TAX, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,TAX_NEW( 		ENUM_VALID_THEME.TAX, 	ENUM_VALID_BASICFUNCTION.NEW)
	,TAX_DELETE( 	ENUM_VALID_THEME.TAX, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,TAX_ATTACHMENT( 	ENUM_VALID_THEME.TAX, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)

 	,EMAIL_SEND_EDIT( 	ENUM_VALID_THEME.EMAIL_SEND, 		ENUM_VALID_BASICFUNCTION.EDIT)
	,EMAIL_SEND_VIEW( 	ENUM_VALID_THEME.EMAIL_SEND, 		ENUM_VALID_BASICFUNCTION.VIEW)
	,EMAIL_SEND_NEW( 		ENUM_VALID_THEME.EMAIL_SEND, 	ENUM_VALID_BASICFUNCTION.NEW)
	,EMAIL_SEND_DELETE( 	ENUM_VALID_THEME.EMAIL_SEND, 	ENUM_VALID_BASICFUNCTION.DELETE)
	,EMAIL_SEND_ATTACHMENT( 	ENUM_VALID_THEME.EMAIL_SEND, 	ENUM_VALID_BASICFUNCTION.ATTACHMENT)
	
	
	;
	

	private ENUM_VALID_THEME 	mainTheme = null;
	
	//fuer die freie variante
	private String      		code4Function = null;
	private String    			info4user = null;
	
	//fuer die strukturierte variante
	private ENUM_VALID_SUBTHEME 				subTheme = null;
	private ENUM_VALID_BASICFUNCTION 			function = null;
	
	private E2_MODULNAME_ENUM.MODUL              modul = null;
	
	/**
	 * variante frei definiert
	 * @param mainTheme
	 * @param subTheme
	 * @param function
	 */
	private ENUM_VALIDATION(ENUM_VALID_THEME mainTheme, String  p_code4Function, String  info4user) {
		this.mainTheme = mainTheme;
		this.code4Function = p_code4Function;
		this.info4user = info4user;
	}

	
	/**
	 * variante aus mainTheme und function
	 * @param mainTheme
	 * @param function
	 */
	private ENUM_VALIDATION(ENUM_VALID_THEME mainTheme, ENUM_VALID_BASICFUNCTION p_function) {
		this.mainTheme = mainTheme;
		this.function = p_function;
	}
	
	
	
	/**
	 * @param mainTheme
	 * @param subTheme
	 * @param function
	 */
	private ENUM_VALIDATION(ENUM_VALID_THEME mainTheme, ENUM_VALID_SUBTHEME subTheme, ENUM_VALID_BASICFUNCTION function) {
		this.mainTheme = mainTheme;
		this.subTheme = subTheme;
		this.function = function;
	}


	/**
	 * spezieller eintrag fuer hauptmenueaufrufe
	 * @param modul
	 * @throws myException
	 */
	private ENUM_VALIDATION(E2_MODULNAME_ENUM.MODUL p_modul) {
		this.mainTheme=ENUM_VALID_THEME.MENUE_CALL;
		this.modul = p_modul;
	}
	
	
	
	public String getButtonKey() {
		String buttonkenner = null;

		//201711124: validierung von menuecalls
		if (this.modul!=null) {
			buttonkenner = this.genDbVal(this.mainTheme,true)+this.modul.get_callKey();
		} else {
		
			if (this.code4Function!=null) {		  //freie variante
				buttonkenner = this.mainTheme.db_val()+"#"+this.code4Function;
			} else {
				buttonkenner = this.genDbVal(this.mainTheme,true)+this.genDbVal(this.subTheme,true)+this.genDbVal(this.function,false);
			}
		}
		return buttonkenner;
	}
	
	
	private String genDbVal(IF_enum_4_db en, boolean addHashTag) {
		String cRet = "";
		if (en != null) {
			cRet = en.db_val()+(addHashTag?"#":"");
		}
		return cRet;
	}
	
	
	private String getUserText(IF_enum_4_db en, String separator) {
		String ret = "";
		if (en != null) {
			ret = en.user_text();
			if (S.isFull(separator)) {
				ret = ret+separator;
			}
		}
		return ret;
	}
	
	private String getUserText(E2_MODULNAME_ENUM.MODUL en, String separator) {
		String ret = "";
		if (en != null) {
			ret = en.get_userInfo().COrig();
			if (S.isFull(separator)) {
				ret = ret+separator;
			}
		}
		return ret;
	}

	
	@Override
	public E2_ButtonAUTHValidator getValidator() {
		//validierer wird global eingesetzt
		return new E2_ButtonAUTHValidator(E2_MODULNAME_ENUM.MODUL.MODUL_KENNER_PROGRAMM_WIDE.get_callKey(), this.getButtonKey());
	}



	@Override
	/**
	 * hier hat nur ein user GESCHAEFTSFUEHRER oder die angelegten benutzer zugriff
	 */
	public E2_ButtonAUTHValidator getValidatorWithoutSupervisorPersilschein() {
		return new E2_ButtonAUTHValidator(E2_MODULNAME_ENUM.MODUL.MODUL_KENNER_PROGRAMM_WIDE.get_callKey(), this.getButtonKey(),false);
	}

	
	
	

	@Override
	public String getRange() {
		return this.mainTheme.db_val();
	}



	@Override
	public String getReadableText() {
		String cRet = "";
		
		cRet = cRet + this.getUserText(this.mainTheme,":");
		cRet = cRet + this.getUserText(this.modul,":");
		cRet = cRet + this.getUserText(this.subTheme,":");
		cRet = cRet + this.getUserText(this.function,":");
		
		if (cRet.endsWith(":")) {
			cRet = cRet.substring(0,cRet.length()-1);
		}
		
//		if (this.mainTheme != null)
//		
//		if (this.subTheme==null) {
//			return S.NN(info4user);
//		} else {
//			return S.NN(this.mainTheme.user_text()+" "+this.subTheme.user_text()+" "+this.function.user_text());
//		}
		
		return cRet;
	}
	
	
	
	public static void writeMissungButtons2DB(MyE2_MessageVector  p_mv) throws myException {
		MyE2_MessageVector  mv = null; 
		if (p_mv==null) {
			mv = new MyE2_MessageVector();
		} else {
			mv = p_mv;
		}
		
		RecList20 rlButtons = new RecList20(_TAB.button)._fill(new SEL("*").FROM(_TAB.button)
																			.WHERE(new vgl(BUTTON.modulkenner, COMP.EQ, E2_MODULNAME_ENUM.MODUL.MODUL_KENNER_PROGRAMM_WIDE.get_callKey())).s());
		
		Vector<ENUM_VALIDATION>  vMissing = new Vector<>();
		ENUM_VALIDATION[]  vals = ENUM_VALIDATION.values();
		
		
		for (ENUM_VALIDATION v: vals) {
			boolean found = false;
			for (Rec20 r: rlButtons) {
				if (r.get_ufs_dbVal(BUTTON.buttonkenner).equals(v.getButtonKey())) {
					found = true;
					break;
				}
			}
			if (!found) {
				vMissing.add(v);
			}
		}
		
		//jetzt die fehlenden buttons schreiben
		for (ENUM_VALIDATION v: vMissing) {
			Rec20 recNew = new Rec20(_TAB.button);
			
			recNew._nv(BUTTON.modulkenner, E2_MODULNAME_ENUM.MODUL.MODUL_KENNER_PROGRAMM_WIDE.get_callKey(), mv);
			recNew._nv(BUTTON.buttonkenner, v.getButtonKey(), mv);
			
			recNew._SAVE(true, mv);
		}

		
		if (mv.get_bIsOK()) {
			mv.add_MESSAGE(new MyE2_Info_Message(new MyE2_String("Anzahl Buttonscode dazugefügt: ").ut(""+vMissing.size())));
		}
		
		//wenn kein messagevektor uebergeben wurde, dann wird werden die messages veroeffentlicht
		if (p_mv == null) {
			bibMSG.add_MESSAGE(mv);
		}
		
	}
	
	
	
	public static String getBeschreibung(String buttonCode) {
		String cRet = buttonCode;
		
		ENUM_VALIDATION[] allValid = ENUM_VALIDATION.values();
		
		for (ENUM_VALIDATION v: allValid) {
			if (v.getButtonKey().equals(buttonCode)) {
				cRet = v.getReadableText();
				if (S.isEmpty(cRet)) {
					cRet=buttonCode;
				}
			}
		}
		
		return cRet;
	}
	

	
	
	/**
	 * die validierung wird nur durchgefuehrt, wenn der menuekey in dieser enum steht
	 * @param menueKey
	 * @return
	 */
	public static MyE2_MessageVector validateMenueCall(E2_MODULNAME_ENUM.MODUL modul2check) {
		
		ENUM_VALIDATION[] allValid = ENUM_VALIDATION.values();
		
		for (ENUM_VALIDATION v: allValid) {
			if (v.modul!=null && v.modul==modul2check) {
				E2_ButtonAUTHValidator val = new E2_ButtonAUTHValidator(E2_MODULNAME_ENUM.MODUL.MODUL_KENNER_PROGRAMM_WIDE.get_callKey(), v.getButtonKey(),false);
				return val.isValid(new RB_lab());
			}
		}
		return new MyE2_MessageVector();
	}

	
}
