package rohstoff.Echo2BusinessLogic.KUNDENSTATUS;

public enum ENUM_Values {
	FIBU_FORDERUNG,
	RECHNUNG_FORDERUNG,
	FREIE_POSITIONEN_FORDERUNG,
	FUHRE_FORDERUNG,
	FUHRE_ORT_FORDERUNG,
	FUHRE_FORDERUNG_GEPLANT,
	FUHRE_ORT_FORDERUNG_GEPLANT,
	

	FIBU_VERBINDLICHKEIT,
	RECHNUNG_VERBINDLICHKEIT,
	FREIE_POSITIONEN_VERBINDLICHKEIT,
	FUHRE_VERBINDLICHKEIT,
	FUHRE_ORT_VERBINDLICHKEIT,
	FUHRE_VERBINDLICHKEIT_GEPLANT,
	FUHRE_ORT_VERBINDLICHKEIT_GEPLANT

}
