package panter.gmbh.indep.dataTools.tempTables;

public class myCONST_TEMP_TABLES {

	/**
	 * hier wird eine globale enum gefuehrt, die alle im System benutzbaren 
	 * Global-Temp-Tables auflistet und vor dem drop-table gegenprueft
	 */
	public static enum TEMP_TABLES 
	{
		TT_SORT_TABLE,
		ST_WA_ATOM,
		ST_WA_MONATS_SUM,
		ST_WE_ATOM,
		ST_WE_MONATS_SUM,
		ST_WE_RECHPOS_MONAT_SUM,
		ST_WA_RECHPOS_MONAT_SUM,
		ST_KOSTEN_AUS_FUHREN,
		ST_STATISTIK_LIEFERBED,
	}
	
	/**
	 * ein paar hilfreiche scripte zum erstellen / loeschen der daten beim reporting
	 * 
	  
DROP TABLE ST_EINKAUF_ATOM;
DROP TABLE ST_EK_MONATS_SUM;
DROP TABLE ST_VERKAUF_ATOM;
DROP TABLE ST_VK_MONATS_SUM;
DROP TABLE ST_EK_RECHPOS_MONAT_SUM;
DROP TABLE ST_VK_RECHPOS_MONAT_SUM;


DELETE FROM ST_EINKAUF_ATOM;
DELETE FROM ST_EK_MONATS_SUM;
DELETE FROM ST_VERKAUF_ATOM;
DELETE FROM ST_VK_MONATS_SUM;
DELETE FROM ST_EK_RECHPOS_MONAT_SUM;
DELETE FROM ST_VK_RECHPOS_MONAT_SUM;


INSERT INTO ST_EINKAUF_ATOM (SELECT * FROM S1_EINKAUF_ATOM);
INSERT INTO ST_EK_MONATS_SUM (SELECT * FROM S1_EK_MONATS_SUM);
INSERT INTO ST_VERKAUF_ATOM (SELECT * FROM S1_VERKAUF_ATOM);
INSERT INTO ST_VK_MONATS_SUM (SELECT * FROM S1_VK_MONATS_SUM);
INSERT INTO ST_EK_RECHPOS_MONAT_SUM (SELECT * FROM S1_EK_RECHPOS_MONAT_SUM);
INSERT INTO ST_VK_RECHPOS_MONAT_SUM (SELECT * FROM S1_VK_RECHPOS_MONAT_SUM);

	 
	 */
	
	
	
}
