package rohstoff.Echo2BusinessLogic.BEWEGUNG.TPA;

import panter.gmbh.Echo2.E2_ResourceIcon;


public class BST__CONST 
{
	 
	// felder in allen datenbanktabellen, die global eingetragen werden
	public static String[] DATENBANK_EXCLUDES_IN_KOPF = 	{"ID_MANDANT","GEAENDERT_VON","LETZTE_AENDERUNG","BEMERKUNGEN_INTERN","FORMULARTEXT_ANFANG","FORMULARTEXT_ENDE"};
	public static String[] DATENBANK_EXCLUDES_IN_POS  = 	{"ID_MANDANT","GEAENDERT_VON","LETZTE_AENDERUNG","ARTBEZ2","EUNOTIZ","BASEL_NOTIZ"};
	public static String[] DATENBANK_EXCLUDES_IN_POSTPA  = 	{"ID_MANDANT","GEAENDERT_VON","LETZTE_AENDERUNG","BEMERKUNGEN_INTERN"};
	
	
	public static final String HASH_KEY_DATUM_VON_BIS = 							"HASH_KEY_DATUM_VON_BIS";
	public static final String HASH_KEY_ANZEIGE_LOCKED = 							"HASH_KEY_ANZEIGE_LOCKED";
	public static final String HASH_KEY_ANZEIGE_POSITIONS = 						"HASH_KEY_ANZEIGE_POSITIONS";
	public static final String HASH_KEY_ANZEIGE_LADESTAUS = 						"HASH_KEY_ANZEIGE_LADESTAUS";   //NEU10

	
	public static final String HASH_KEY_BUTTON_MASK_OPEN_EDITADRESS =				"HASH_KEY_BUTTON_MASK_OPEN_EDITADRESS";
	public static final String HASH_KEY_BUTTON_MASK_OPEN_NEWADRESS =				"HASH_KEY_BUTTON_MASK_OPEN_NEWADRESS";
	
	
	public static E2_ResourceIcon LABEL_EMPTY = 									E2_ResourceIcon.get_RI("empty20.png")	;
	public static E2_ResourceIcon LABEL_KOPF_LOCKED  = 								E2_ResourceIcon.get_RI("locked.png")	;

	public static final String HASH_KEY_DAUGHTERTABLE_PRINTPROTOKOLL = 				"HASH_KEY_DAUGHTERTABLE_PRINTPROTOKOLL";

	public static final String HASH_KEY_DEL_BUTTON_DAUGHTERTABLE_PRINTPROTOKOLL = 	"HASH_KEY_DEL_BUTTON_DAUGHTERTABLE_PRINTPROTOKOLL";

	public static final String HASH_KEY_DEL_BUTTON_DAUGHTERTABLE_LIEFERTERMIN = 	"HASH_KEY_DEL_BUTTON_DAUGHTERTABLE_LIEFERTERMIN";
	public static final String HASH_KEY_DEL_BUTTON_DAUGHTERTABLE_LAGERLIEFERUNG = 	"HASH_KEY_DEL_BUTTON_DAUGHTERTABLE_LAGERLIEFERUNG";

	
	public static final String HASH_KEY_DAUGHTERTABLE_POSITIONS = 					"HASH_KEY_DAUGHTERTABLE_POSITIONS";
	

	public static final String HASH_KEY_DAUGHTERTABLE_LAGERLIEFERUNG = 				"HASH_KEY_DAUGHTERTABLE_LAGERLIEFERUNG";
	public static final String HASH_KEY_DAUGHTERTABLE_LIEFERTERMINE = 				"HASH_KEY_DAUGHTERTABLE_LIEFERTERMINE";
	
	public static final String HASH_KEY_POSITION_MASK_SET_ACTUAL_MONTH = 			"HASH_KEY_POSITION_MASK_SET_ACTUAL_MONTH";
	public static final String HASH_KEY_POSITION_MASK_SET_NEXT_MONTH = 				"HASH_KEY_POSITION_MASK_SET_NEXT_MONTH";
	
	public static final String HASH_KEY_POSITION_STORNO_INFO = 						"HASH_KEY_POSITION_STORNO_INFO";
	
	public static final String HASH_KEY_LIST_BT_JUMP_TPA_TO_FUHRE = 				"HASH_KEY_LIST_BT_JUMP_TPA_TO_FUHRE";
	
	
}
