package rohstoff.Echo2BusinessLogic.FIBU_KONTEN.STAMM;

public class FKR__CONST {
	
	public static String MASK_COMPONENT_CROSSTABLE_LAENDER_EK = "MASK_COMPONENT_CROSSTABLE_LAENDER_EK";
	public static String MASK_COMPONENT_CROSSTABLE_LAENDER_VK = "MASK_COMPONENT_CROSSTABLE_LAENDER_VK";
	
	public static String LIST_COMPONENT_QUELLEN_LAND_TABLE = "LIST_COMPONENT_QUELLEN_LAND_TABLE";
	public static String LIST_COMPONENT_ZIEL_LAND_TABLE = "LIST_COMPONENT_ZIEL_LAND_TABLE";
	
	
}
