package rohstoff.Echo2BusinessLogic.FIRMENSTAMM.LIEFERADRESSEN;


public class FSL__CONST {

	public static String 	MASK_FIELD_DAUGHTER_AVV_CODES_ZERTIFIZIERT_LA = 		"FIELD_DAUGHTER_AVV_CODES_ZERTIFIZIERT_LA";

	public static String MASK_FIELD_DAUGHTER_AVV_CODES_ZERTIFIZIERT_EXPORT_LA=		"FIELD_DAUGHTER_AVV_CODES_ZERTIFIZIERT_EXPORT_LA";
	public static String MASK_FIELD_DAUGHTER_AVV_CODES_ZERTIFIZIERT_IMPORT_LA=		"FIELD_DAUGHTER_AVV_CODES_ZERTIFIZIERT_IMPORT_LA";

	public static String MASK_FIELD_DAUGHTER_TRANSPORTKOSTEN				   =     "FIELD_DAUGHTER_TRANSPORTKOSTEN";
	
	//20180206: geocoding
	public static String LIST_GEOCODE_LIEF = 										"LIST_GEOCODE_LIEF";
	public static String LIST_GEOCODE_LIEF_OSM = 									"LIST_GEOCODE_LIEF_OSM";
	
	
	public static String LABEL_ID_ADRESSE_FREMDWARE = "LABEL_ID_ADRESSE_FREMDWARE";
	public static String LABEL_ID_ADRESSE_BESITZER_WARE = "LABEL_ADRESSE_BESITZER_WARE";
	public static String LABEL_ID_ADRESSE_BESITZER_WARE_LAGER = "LABEL_ADRESSE_BESITZER_WARE_LAGER";
	public static String LABEL_ID_ADRESSE_BESITZ_LAGER = "LABEL_ID_ADRESSE_BESITZ_LAGER";

}
