package panter.gmbh.basics4project;


public class FELDNAMEN_MANDANTEN_ZUSATZFELDER {
//	public static String ANHANG7_VARIANTE_FUER_KONTROLLE_DRUCKEN = "ANHANG7_VARIANTE_FUER_KONTROLLE_DRUCKEN";
//	public static String DRUCKE_ZWEITES_EUBLATT = "DRUCKE_ZWEITES_EUBLATT";
//	public static String FARBE_UMA_BUTTON_IN_LISTE = "FARBE_UMA_BUTTON_IN_LISTE";
//	public static String LIEFERSCHEIN_BESITZTEXT = "LIEFERSCHEIN_BESITZTEXT";
//	public static String LIEFERSCHEIN_FUSSTEXT = "LIEFERSCHEIN_FUSSTEXT";
//	public static String MAHNUNG_1_UEBERSCHRIFT_EN = "MAHNUNG_1_UEBERSCHRIFT_EN";
//	public static String MAHNUNG_2_UEBERSCHRIFT_EN = "MAHNUNG_2_UEBERSCHRIFT_EN";
//	public static String MAHNUNG_3_UEBERSCHRIFT_DE = "MAHNUNG_3_UEBERSCHRIFT_DE";
//	public static String MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE3 = "MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE3";
//	public static String MAHNUNG_SEITENFUSS_BLOCK_RECHTS = "MAHNUNG_SEITENFUSS_BLOCK_RECHTS";
//	public static String WAAGE_HOFSCHEIN_DRUCKEN_WA = "WAAGE_HOFSCHEIN_DRUCKEN_WA";
//	public static String BELEGTEXT_DUPLIKAT = "BELEGTEXT_DUPLIKAT";
//	public static String BEWEGUNGSSATZ_KEINE_SONDERLAGER_ERZEUGEN = "BEWEGUNGSSATZ_KEINE_SONDERLAGER_ERZEUGEN";
//	public static String ERLAUBE_FEHLENDE_AUSWEISNUMMER_IN_GUTSCHRIFTEN_BARKUNDEN = "ERLAUBE_FEHLENDE_AUSWEISNUMMER_IN_GUTSCHRIFTEN_BARKUNDEN";
//	public static String FORMULARFUSSBILDUNTERSCHRIFT = "FORMULARFUSSBILDUNTERSCHRIFT";
//	public static String FORMULARFUSSTEXT_RECHTS = "FORMULARFUSSTEXT_RECHTS";
//	public static String FREMDWARE_ZU_FREMDWARENLAGER_INAKTIV = "FREMDWARE_ZU_FREMDWARENLAGER_INAKTIV";
//	public static String LIEFERSCHEIN_GELANGENTEXT = "LIEFERSCHEIN_GELANGENTEXT";
//	public static String MAHNUNG_2_UEBERSCHRIFT_DE = "MAHNUNG_2_UEBERSCHRIFT_DE";
//	public static String MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE1 = "MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE1";
//	public static String MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE4 = "MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE4";
//	public static String ANHANG7_VARIANTE_FUER_ABHNEHMER_DRUCKEN = "ANHANG7_VARIANTE_FUER_ABHNEHMER_DRUCKEN";
//	public static String FORMULARFUSSTEXT_LINKS = "FORMULARFUSSTEXT_LINKS";
//	public static String JT_VPOS_TPA_FUHRE_KENNZEICHEN_IST_MUSSFELD = "JT_VPOS_TPA_FUHRE_KENNZEICHEN_IST_MUSSFELD";
//	public static String JT_VPOS_TPA_FUHRE_VORGABE_TRANSPORTMITTEL = "JT_VPOS_TPA_FUHRE_VORGABE_TRANSPORTMITTEL";
//	public static String MAHNUNG_3_UEBERSCHRIFT_EN = "MAHNUNG_3_UEBERSCHRIFT_EN";
//	public static String ORDNUNGSNUMMER_CMR = "ORDNUNGSNUMMER_CMR";
//	public static String RECHNUNG_PER_FAX_EINDRUCK = "RECHNUNG_PER_FAX_EINDRUCK";
//	public static String FORMULARFUSSTEXT_MITTE = "FORMULARFUSSTEXT_MITTE";
//	public static String WAAGE_HOFSCHEIN_DRUCKEN_ANZEIGE_BUTTON = "WAAGE_HOFSCHEIN_DRUCKEN_ANZEIGE_BUTTON";
//	public static String ADRESS_EK_SORTE_AVV_AUTOMATISCH = "ADRESS_EK_SORTE_AVV_AUTOMATISCH";
//	public static String HINWEIS_INTERNER_BELEG = "HINWEIS_INTERNER_BELEG";
//	public static String MAHNUNG_1_UEBERSCHRIFT_DE = "MAHNUNG_1_UEBERSCHRIFT_DE";
//	public static String MAHNUNG_1_UEBERSCHRIFT_FR = "MAHNUNG_1_UEBERSCHRIFT_FR";
//	public static String MAHNUNG_SEITENFUSS_BLOCK_MITTE = "MAHNUNG_SEITENFUSS_BLOCK_MITTE";
//	public static String WAAGE_HOFSCHEIN_DRUCKEN_WE = "WAAGE_HOFSCHEIN_DRUCKEN_WE";
//	public static String ABHOLNACHRICHTEIGENTUMSHINWEIS = "ABHOLNACHRICHTEIGENTUMSHINWEIS";
//	public static String BROWSER_OPEN_WINDOW_COMMAND = "BROWSER_OPEN_WINDOW_COMMAND";
//	public static String HANDELSDEF_ERLAUBE_VARIANTE_EGAL_IN_DROPDOWN = "HANDELSDEF_ERLAUBE_VARIANTE_EGAL_IN_DROPDOWN";
//	public static String LAGER_WA_GEWICHT_NETTO = "LAGER_WA_GEWICHT_NETTO";
//	public static String LIEFERAVIS_EIGENTUMSVORBEHALT = "LIEFERAVIS_EIGENTUMSVORBEHALT";
//	public static String MAHNUNG_2_UEBERSCHRIFT_FR = "MAHNUNG_2_UEBERSCHRIFT_FR";
//	public static String MAHNUNG_3_UEBERSCHRIFT_FR = "MAHNUNG_3_UEBERSCHRIFT_FR";
//	public static String RECHNUNGSPOSITION_MANUELL_SCHROTTSORTE_VERBIETEN = "RECHNUNGSPOSITION_MANUELL_SCHROTTSORTE_VERBIETEN";
//	public static String STEUERERMITTLUNG_MIT_HANDELSDEF = "STEUERERMITTLUNG_MIT_HANDELSDEF";
//	public static String VK_KONTRAKT_ENDTEXT_STD = "VK_KONTRAKT_ENDTEXT_STD";
//	public static String WIEGEGEWICHTE_BEIDSEITIG_EINTRAGEN = "WIEGEGEWICHTE_BEIDSEITIG_EINTRAGEN";
//	public static String ANHANG7_FELDCHECK_NUR_WARN = "ANHANG7_FELDCHECK_NUR_WARN";
//	public static String EK_KONTRAKT_ENDTEXT_STD = "EK_KONTRAKT_ENDTEXT_STD";
//	public static String ERLAUBE_FEHLENDE_UST_KENNZEICHEN_IN_EU_RECHNUNG = "ERLAUBE_FEHLENDE_UST_KENNZEICHEN_IN_EU_RECHNUNG";
//	public static String FELDLISTE_KONTRAKT_LIEFERORT = "FELDLISTE_KONTRAKT_LIEFERORT";
//	public static String FORMULARFUSSTEXT = "FORMULARFUSSTEXT";
//	public static String LAGER_WA_PREIS_KORREKTUR = "LAGER_WA_PREIS_KORREKTUR";
//	public static String MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE2 = "MAHNUNG_MANDANTEN_ANSCHRIFTBLOCK_ZEILE2";
//	public static String FREMDWARE_ZU_FREMDWARENLAGER_WENN_AKTIV_NUR_WARNUNG = "FREMDWARE_ZU_FREMDWARENLAGER_WENN_AKTIV_NUR_WARNUNG";
//	public static String LAGER_UMBUCHUNGEN_ERLAUBEN = "LAGER_UMBUCHUNGEN_ERLAUBEN";
//	public static String MAHNUNG_SEITENFUSS_BLOCK_LINKS = "MAHNUNG_SEITENFUSS_BLOCK_LINKS";
//	public static String VORGABEWERT_MITARBEITERGESCHENK = "VORGABEWERT_MITARBEITERGESCHENK";
//   
//	public static String VERBIETE_UEBERSTIMMEN_FEHLENDEN_HANDELSVERTRAG = "VERBIETE_UEBERSTIMMEN_FEHLENDEN_HANDELSVERTRAG";
//	public static String HANDELSVERTRAG_PRUEFE_AN_JUR_ORT = "HANDELSVERTRAG_PRUEFE_AN_JUR_ORT";
//	public static String HANDELSVERTRAG_PRUEFE_AN_GEO_ORT = "HANDELSVERTRAG_PRUEFE_AN_GEO_ORT";
//	
//	public static String KREDITVERSICHERUNG_WARNUNG_BEI_ABLAUF = "KREDITVERSICHERUNG_WARNUNG_BEI_ABLAUF";
//	public static String KREDITVERSICHERUNG_WARNUNG_BEI_ABLAUF_KADENZZEIT = "KREDITVERSICHERUNG_WARNUNG_BEI_ABLAUF_KADENZZEIT";

	
	
}
