package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.LOGIC.CONVERT_FROM_FUHRE;

// Generated 27.07.2012 10:12:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Vector;

import panter.gmbh.Echo2.bibE2;
import panter.gmbh.basics4project.DEBUG;
import panter.gmbh.indep.dataTools.MySqlStatementBuilder;
import panter.gmbh.indep.exceptions.myException;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOBigDecimal;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DODate;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOLong;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOString;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DataObject;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.LOGIC.KOSTEN.REC_Bewegung_Atom_Kosten;

/**
 * JtBewegungsatom generated by hbm2java
 */
public class JtBewegung_Atom implements java.io.Serializable {

	private JtBewegung_Vektor_Pos 	jtBewegung_vektor_pos = null;
	private DOString 		  		idBewegung_vektor_pos = new DOString("ID_BEWEGUNG_VEKTOR_POS",null,"");
	
	private JtBewegung_Vektor jtBewegung_vektor = null;
	private DOString 		  idBewegung_vektor = new DOString("ID_BEWEGUNG_VEKTOR",null,"");
	
	private JtBewegung		  jtBewegung = null;
	private DOString 		  idBewegung = new DOString("ID_BEWEGUNG",null,"");
	
	private DOString idBewegung_atom = new DOString("ID_BEWEGUNG_ATOM",null,"");

	private Vector<JtBewegung_Station> jtBewegungStations = new Vector<JtBewegung_Station>(0);
	
	private DOLong idMandant = new DOLong("ID_MANDANT");
	private DODate letzteAenderung = new DODate("LETZTE_AENDERUNG");
	private DOString geaendertVon = new DOString("GEAENDERT_VON");
	
	
	private DOLong idArtikelBez = new DOLong("ID_ARTIKEL_BEZ");
	private DOLong idArtikel = new DOLong("ID_ARTIKEL");
	
	private DOBigDecimal planmenge = new DOBigDecimal("PLANMENGE");
	private DOBigDecimal menge = new DOBigDecimal("MENGE");
	private DOBigDecimal abzugMenge = new DOBigDecimal("ABZUG_MENGE");
	
	// 2013-09-10
	private DOBigDecimal Gesamtpreis 				= new DOBigDecimal("GESAMTPREIS");
	private DOBigDecimal GPreisAbzMenge 			= new DOBigDecimal("GPREIS_ABZ_MGE");
	private DOBigDecimal GPreisAbzAufNettomenge 	= new DOBigDecimal("GPREIS_ABZ_AUF_NETTOMGE");
	private DOBigDecimal GPreisAbzVorauszahlung 	= new DOBigDecimal("GPREIS_ABZ_VORAUSZAHLUNG");
	private DOBigDecimal EPreisResultBruttoMenge 	= new DOBigDecimal("E_PREIS_RESULT_BRUTTO_MGE");
	private DOBigDecimal mengeNetto 				= new DOBigDecimal("MENGE_NETTO");
	// end 2013-09-10
	
	private DOBigDecimal EPreis = new DOBigDecimal("E_PREIS");
	private DOBigDecimal EPreisResultNettoMge = new DOBigDecimal("E_PREIS_RESULT_NETTO_MGE");
	
	private DOLong   idVposKon = new DOLong("ID_VPOS_KON");
	private DOLong   idVposStd = new DOLong("ID_VPOS_STD");
	private DOString abrechenbar = new DOString("ABRECHENBAR");
	private DOString abgerechnet = new DOString("ABGERECHNET");
	private DOString kontraktzwang = new DOString("KONTRAKTZWANG");
	private DOString kontraktzwangAusVon = new DOString("KONTRAKTZWANG_AUS_VON");
	private DOString kontraktzwangAusGrund = new DOString("KONTRAKTZWANG_AUS_GRUND");
	private DODate   kontraktzwangAusAm = new DODate("KONTRAKTZWANG_AUS_AM") ;
	private DODate   leistungsdatum = new DODate("LEISTUNGSDATUM");
	private DOString postennummer = new DOString("POSTENNUMMER");
	private DOBigDecimal steuersatz = new DOBigDecimal("STEUERSATZ");
	private DOString euSteuerVermerk = new DOString("EU_STEUER_VERMERK");
	private DOString bemerkung = new DOString("BEMERKUNG");
	private DOString bemerkungSachbearbeiter = new DOString("BEMERKUNG_SACHBEARBEITER");

	private DOString buchungsnummer = new DOString("BUCHUNGSNUMMER");
	private DOString notifikationNr = new DOString("NOTIFIKATION_NR");
	private DOString pruefungMenge = new DOString("PRUEFUNG_MENGE");
	private DODate   pruefungMengeAm = new DODate("PRUEFUNG_MENGE_AM") ;
	private DOString pruefungMengeVon = new DOString("PRUEFUNG_MENGE_VON");

	private DOString artbez1 = new DOString("ARTBEZ1");
	private DOString artbez2 = new DOString("ARTBEZ2");
	private DOString deleted = new DOString("DELETED");
	private DODate   delDate = new DODate("DEL_DATE");
	private DOString delGrund = new DOString("DEL_GRUND");
	private DOString delKuerzel = new DOString("DEL_KUERZEL");
	private DOString lieferinfoTpa = new DOString("LIEFERINFO_TPA");
	private DOString preisermittlung = new DOString("PREISERMITTLUNG");
	private DOString nationalerAbfallCode = new DOString("NATIONALER_ABFALL_CODE");
	private DOString ordnungsnummerCmr = new DOString("ORDNUNGSNUMMER_CMR");
	private DOString zeitstempel = new DOString("ZEITSTEMPEL");
	private DOString setzkastenKomplett = new DOString("SETZKASTEN_KOMPLETT");
	private DOString storniert = new DOString("STORNIERT");
	private DODate   storniertAm = new DODate("STORNIERT_AM");
	private DOString storniertVon = new DOString("STORNIERT_VON");
	private DOString storniertGrund = new DOString("STORNIERT_GRUND");
	
	private DOLong posnr = new DOLong("POSNR");
	
	private DOString erzeugtvon = new DOString("ERZEUGT_VON");
	private DODate erzeugtam = new DODate("ERZEUGT_AM");

	// 2013-09-13 ID_LAGER_KONTO 
	private DOLong idLagerKonto = new DOLong("ID_LAGER_KONTO");
	
	private DOLong idZahlungsbedingungen = new DOLong("ID_ZAHLUNGSBEDINGUNGEN");
	private DOString lieferbedingungen = new DOString("LIEFERBEDINGUNGEN");
	private DOLong idLieferbedingungen = new DOLong("ID_LIEFERBEDINGUNGEN");

	private DOLong idVposTpaFuhre = new DOLong("ID_VPOS_TPA_FUHRE");

	// Kosten-Struktur einbauen fuer die Kostenbehafteten Umbuchungen
	private Vector<REC_Bewegung_Atom_Kosten> vRecKosten = new Vector<REC_Bewegung_Atom_Kosten>();
	
	

	public JtBewegung_Atom() {
	}

	
	
	
	
	public JtBewegung_Atom(String idBewegungsatom, Long idMandant,	Long posnr) {
		this.idBewegung_atom.setValue( idBewegungsatom );
		this.idMandant.setValue( idMandant );
		this.posnr.setValue( posnr );
	}

	
	
	public JtBewegung_Atom get_copy(){
		JtBewegung_Atom c = new JtBewegung_Atom();
		
		JtBewegung_Atom a = this;
		
		c.jtBewegung_vektor_pos= a.jtBewegung_vektor_pos;
		c.idBewegung_vektor_pos.CopyFrom(a.idBewegung_vektor_pos);
		
		c.jtBewegung_vektor = a.jtBewegung_vektor;
		c.idBewegung_vektor.CopyFrom(a.idBewegung_vektor);
		
		
		c.jtBewegung = a.jtBewegung;
		c.idBewegung.CopyFrom(a.idBewegung);
		
		c.idBewegung_atom.CopyFrom(a.idBewegung_atom );

		c.jtBewegungStations = new Vector<JtBewegung_Station>(0);
		
		c.idMandant.CopyFrom( a.idMandant);
		c.letzteAenderung.CopyFrom(a.letzteAenderung);
		c.geaendertVon.CopyFrom(a.geaendertVon);
		
		c.idArtikelBez.CopyFrom( a.idArtikelBez);
		c.idArtikel.CopyFrom(a.idArtikel );
		
		c.planmenge.CopyFrom( a.planmenge);
		c.menge.CopyFrom(a.menge);
		c.abzugMenge .CopyFrom(a.abzugMenge );
		
		c.Gesamtpreis .CopyFrom(a.Gesamtpreis );
		c.GPreisAbzMenge.CopyFrom(a.GPreisAbzMenge );
		c.GPreisAbzAufNettomenge .CopyFrom(a.GPreisAbzAufNettomenge );
		c.GPreisAbzVorauszahlung .CopyFrom( a.GPreisAbzVorauszahlung);
		c.EPreisResultBruttoMenge .CopyFrom(a.EPreisResultBruttoMenge );
		c.mengeNetto .CopyFrom(a.mengeNetto );
		
		c.EPreis.CopyFrom(a.EPreis );
		c.EPreisResultNettoMge.CopyFrom(a.EPreisResultNettoMge );
		
		c.idVposKon.CopyFrom(a.idVposKon );
		c.idVposStd.CopyFrom(a.idVposStd );
		c.abrechenbar.CopyFrom( a.abrechenbar);
		c.abgerechnet.CopyFrom(a.abgerechnet );
		c.kontraktzwang.CopyFrom(a.kontraktzwang );
		c.kontraktzwangAusVon.CopyFrom(a.kontraktzwangAusVon );
		c.kontraktzwangAusGrund.CopyFrom(a.kontraktzwangAusGrund );
		c.kontraktzwangAusAm .CopyFrom(a.kontraktzwangAusAm );
		c.leistungsdatum.CopyFrom(a.leistungsdatum);
		c.postennummer.CopyFrom(a. postennummer);
		c.steuersatz .CopyFrom(a.steuersatz );
		c.euSteuerVermerk.CopyFrom(a.euSteuerVermerk);
		c.bemerkung .CopyFrom(a.bemerkung );
		c.bemerkungSachbearbeiter.CopyFrom(a.bemerkungSachbearbeiter );

		c.buchungsnummer.CopyFrom(a.buchungsnummer );
		c.notifikationNr.CopyFrom(a.notifikationNr );
		c.pruefungMenge.CopyFrom(a.pruefungMenge );
		c.pruefungMengeAm.CopyFrom(a.pruefungMengeAm );
		c.pruefungMengeVon.CopyFrom(a.pruefungMengeVon );

		c.artbez1.CopyFrom(a.artbez1 );
		c.artbez2.CopyFrom(a.artbez2 );
		c.deleted .CopyFrom( a.deleted);
		c.delDate.CopyFrom(a.delDate );
		c.delGrund .CopyFrom(a.delGrund);
		c.delKuerzel .CopyFrom(a.delKuerzel );
		c.lieferinfoTpa.CopyFrom(a.lieferinfoTpa );
		c.preisermittlung.CopyFrom( a.preisermittlung);
		c.nationalerAbfallCode .CopyFrom(a.nationalerAbfallCode );
		c.ordnungsnummerCmr.CopyFrom( a.ordnungsnummerCmr);
		c.zeitstempel.CopyFrom(a.zeitstempel );
		c.setzkastenKomplett.CopyFrom(a.setzkastenKomplett );
		c.storniert.CopyFrom(a. storniert);
		c.storniertAm .CopyFrom( a.storniertAm);
		c.storniertVon.CopyFrom(a.storniertVon );
		c.storniertGrund .CopyFrom(a.storniertGrund );
		c.posnr.CopyFrom(a.posnr );
		c.erzeugtvon .CopyFrom( a.erzeugtvon);
		c.erzeugtam .CopyFrom(a.erzeugtam );
		c.idLagerKonto.CopyFrom(a.idLagerKonto );
		c.idZahlungsbedingungen.CopyFrom(a.idZahlungsbedingungen );
		c.lieferbedingungen .CopyFrom(a. lieferbedingungen);
		c.idLieferbedingungen.CopyFrom(a.idLieferbedingungen );
		c.idVposTpaFuhre .CopyFrom(a. idVposTpaFuhre);

		// Kosten-Struktur einbauen fuer die Kostenbehafteten Umbuchungen
		c.vRecKosten = new Vector<REC_Bewegung_Atom_Kosten>();

		return c;
		
	}
	
	
	
	
	
	
	
	
	public DOString getIdBewegungsatom() {
		return this.idBewegung_atom;
	}

	public void setIdBewegungsatom(String idBewegungsatom) {
		this.idBewegung_atom.setValue( idBewegungsatom) ;
	}

	
	public DOString getIdBewegungsvektor() {
		return this.idBewegung_vektor;
	}

	public void setIdBewegungsvektor(String idBewegungsvektor) {
		this.idBewegung_vektor.setValue( idBewegungsvektor) ;
	}
	
	
	public DOString getIdBewegungsvektorPos() {
		return this.idBewegung_vektor_pos;
	}

	public void setIdBewegungsvektorPos(String idBewegungsvektorPos) {
		this.idBewegung_vektor_pos.setValue( idBewegungsvektorPos) ;
	}
	
	
	public DOString getIdBewegung() {
		return this.idBewegung;
	}

	public void setIdBewegung(String idBewegung) {
		this.idBewegung.setValue( idBewegung) ;
	}
	
	
	public JtBewegung getJtBewegung() {
		return this.jtBewegung;
	}

	public void setJtBewegung(JtBewegung Bewegung) {
		this.jtBewegung = Bewegung ;
	}
	
	
	public JtBewegung_Vektor getJtBewegungsvektor() {
		return this.jtBewegung_vektor;
	}

	public void setJtBewegungsvektor(JtBewegung_Vektor jtBewegungsvektor) {
		this.jtBewegung_vektor = jtBewegungsvektor ;
	}
	
	
	public JtBewegung_Vektor_Pos getJtBewegungsvektorPos() {
		return this.jtBewegung_vektor_pos;
	}

	public void setJtBewegungsvektorPos(JtBewegung_Vektor_Pos jtBewegungsvektorPos) {
		this.jtBewegung_vektor_pos = jtBewegungsvektorPos ;
	}

	
	
	public Vector<JtBewegung_Station> getJtBewegungstations() {
		return this.jtBewegungStations;
	}

	public void setJtBewegungstations(Vector<JtBewegung_Station> jtBewegung_Stations) {
		this.jtBewegungStations = jtBewegung_Stations;
	}

	public void addJtBewegungstation( JtBewegung_Station station){
		this.jtBewegungStations.add(station);
	}
	
	/**
	 * gibt die Bewegungsstation mit dem Vorzeichen -1 zurück
	 * @author manfred
	 * @date   22.05.2013
	 * @return
	 */
	public JtBewegung_Station getBewegungsstationStart(){
		JtBewegung_Station o = null;
		if (jtBewegungStations != null){
			for (JtBewegung_Station stat : jtBewegungStations){
				if (stat.getMengenvorzeichen().lValue.equals((long)-1)){
					o = stat;
					break;
				}
			}
		}
		return o;
	}
	
	/**
	 * gibt die Bewegungsstation mit dem Vorzeichen +1 zurück
	 * @author manfred
	 * @date   22.05.2013
	 * @return
	 */
	public JtBewegung_Station getBewegungsstationZiel(){
		JtBewegung_Station o = null;
		if (jtBewegungStations != null){
			for (JtBewegung_Station stat : jtBewegungStations){
				if (stat.getMengenvorzeichen().lValue.equals((long)1)){
					o = stat;
					break;
				}
			}
		}
		return o;
	}
	
	
	
	public DOLong getIdMandant() {
		return this.idMandant;
	}

	public void setIdMandant(Long idMandant) {
		this.idMandant.setValue( idMandant) ;
	}

	public DODate getLetzteAenderung() {
		return this.letzteAenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung.setValue( letzteAenderung) ;
	}

	public DOString getGeaendertVon() {
		return this.geaendertVon;
	}

	public void setGeaendertVon(String geaendertVon) {
		this.geaendertVon.setValue( geaendertVon) ;
	}

	public DOLong getIdArtikelBez() {
		return this.idArtikelBez;
	}

	public void setIdArtikelBez(Long idArtikelBez) {
		this.idArtikelBez.setValue( idArtikelBez) ;
	}


	public DOLong getIdArtikel() {
		return this.idArtikel;
	}

	public void setIdArtikel(Long idArtikel) {
		this.idArtikel.setValue( idArtikel) ;
	}

	
	public DOBigDecimal getPlanmenge() {
		return this.planmenge;
	}

	public void setPlanmenge(BigDecimal planmenge) {
		this.planmenge.setValue( planmenge) ;
	}

	public DOBigDecimal getMenge() {
		return this.menge;
	}

	public void setMenge(BigDecimal menge) {
		this.menge.setValue( menge) ;
	}


	public DOBigDecimal getAbzugMenge() {
		return this.abzugMenge;
	}

	public void setAbzugMenge(BigDecimal abzugMenge) {
		this.abzugMenge.setValue( abzugMenge) ;
	}

	public DOBigDecimal getEPreis() {
		return this.EPreis;
	}

	public void setEPreis(BigDecimal EPreis) {
		this.EPreis.setValue( EPreis) ;
	}

	public DOBigDecimal getEPreisResultNettoMge() {
		return this.EPreisResultNettoMge;
	}

	public void setEPreisResultNettoMge(BigDecimal EPreisResultNettoMge) {
		this.EPreisResultNettoMge.setValue( EPreisResultNettoMge) ;
	}


	
	
	public void setGesamtpreis(BigDecimal gesamtpreis) {
		this.Gesamtpreis.setValue(gesamtpreis);
	}

	public DOBigDecimal getGesamtpreis() {
		return Gesamtpreis;
	}

	public void setGPreisAbzMenge(BigDecimal gPreisAbzMenge) {
		this.GPreisAbzMenge.setValue(gPreisAbzMenge);
	}

	public DOBigDecimal getGPreisAbzMenge() {
		return GPreisAbzMenge;
	}

	public void setGPreisAbzAufNettomenge(BigDecimal gPreisAbzAufNettomenge) {
		this.GPreisAbzAufNettomenge.setValue(gPreisAbzAufNettomenge);
	}

	public DOBigDecimal getGPreisAbzAufNettomenge() {
		return GPreisAbzAufNettomenge;
	}

	public void setGPreisAbzVorauszahlung(BigDecimal gPreisAbzVorauszahlung) {
		this.GPreisAbzVorauszahlung.setValue( gPreisAbzVorauszahlung);
	}

	public DOBigDecimal getGPreisAbzVorauszahlung() {
		return GPreisAbzVorauszahlung;
	}

	public void setEPreisResultBruttoMenge(BigDecimal ePreisResultBruttoMenge) {
		this.EPreisResultBruttoMenge.setValue( ePreisResultBruttoMenge);
	}

	public DOBigDecimal getEPreisResultBruttoMenge() {
		return EPreisResultBruttoMenge;
	}

	public void setMengeNetto(BigDecimal mengeNetto) {
		this.mengeNetto.setValue( mengeNetto);
	}

	public DOBigDecimal getMengeNetto() {
		return mengeNetto;
	}

	
	
	
	
	public DOLong getIdVposKon() {
		return this.idVposKon;
	}

	public void setIdVposKon(Long idVposKon) {
		this.idVposKon.setValue( idVposKon) ;
	}

	public DOLong getIdVposStd() {
		return this.idVposStd;
	}

	public void setIdVposStd(Long idVposStd) {
		this.idVposStd.setValue( idVposStd) ;
	}

	public DOString getAbrechenbar() {
		return this.abrechenbar;
	}

	public void setAbrechenbar(String abrechenbar) {
		this.abrechenbar.setValue( abrechenbar) ;
	}

	public DOString getAbgerechnet() {
		return this.abgerechnet;
	}

	public void setAbgerechnet(String abgerechnet) {
		this.abgerechnet.setValue( abgerechnet) ;
	}

	public DOString getKontraktzwang() {
		return this.kontraktzwang;
	}

	public void setKontraktzwang(String kontraktzwang) {
		this.kontraktzwang.setValue( kontraktzwang) ;
	}

	public DOString getKontraktzwangAusVon() {
		return this.kontraktzwangAusVon;
	}

	public void setKontraktzwangAusVon(String kontraktzwangAusVon) {
		this.kontraktzwangAusVon.setValue( kontraktzwangAusVon) ;
	}

	public DOString getKontraktzwangAusGrund() {
		return this.kontraktzwangAusGrund;
	}

	public void setKontraktzwangAusGrund(String kontraktzwangAusGrund) {
		this.kontraktzwangAusGrund.setValue( kontraktzwangAusGrund) ;
	}

	public DODate getKontraktzwangAusAm() {
		return this.kontraktzwangAusAm;
	}

	public void setKontraktzwangAusAm(Date kontraktzwangAusAm) {
		this.kontraktzwangAusAm.setValue( kontraktzwangAusAm) ;
	}

	public DODate getLeistungsdatum() {
		return this.leistungsdatum;
	}

	public void setLeistungsdatum(Date leistungsdatum) {
		this.leistungsdatum.setValue( leistungsdatum) ;
	}

	public DOString getPostennummer() {
		return this.postennummer;
	}

	public void setPostennummer(String postennummer) {
		this.postennummer.setValue( postennummer) ;
	}

	public DOBigDecimal getSteuersatz() {
		return this.steuersatz;
	}

	public void setSteuersatz(BigDecimal steuersatz) {
		this.steuersatz.setValue( steuersatz) ;
	}

	public DOString getEuSteuerVermerk() {
		return this.euSteuerVermerk;
	}

	public void setEuSteuerVermerk(String euSteuerVermerk) {
		this.euSteuerVermerk.setValue( euSteuerVermerk) ;
	}

	public DOString getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung.setValue( bemerkung) ;
	}

	public DOString getBemerkungSachbearbeiter() {
		return this.bemerkungSachbearbeiter;
	}

	public void setBemerkungSachbearbeiter(String bemerkungSachbearbeiter) {
		this.bemerkungSachbearbeiter.setValue( bemerkungSachbearbeiter) ;
	}


	public DOString getBuchungsnummer() {
		return this.buchungsnummer;
	}

	public void setBuchungsnummer(String buchungsnummer) {
		this.buchungsnummer.setValue( buchungsnummer) ;
	}

	public DOString getNotifikationNr() {
		return this.notifikationNr;
	}

	public void setNotifikationNr(String notifikationNr) {
		this.notifikationNr.setValue( notifikationNr) ;
	}

	public DOString getPruefungMenge() {
		return this.pruefungMenge;
	}

	public void setPruefungMenge(String pruefungMenge) {
		this.pruefungMenge.setValue( pruefungMenge) ;
	}

	public DODate getPruefungMengeAm() {
		return this.pruefungMengeAm;
	}

	public void setPruefungMengeAm(Date pruefungMengeAm) {
		this.pruefungMengeAm.setValue( pruefungMengeAm) ;
	}

	public DOString getPruefungMengeVon() {
		return this.pruefungMengeVon;
	}

	public void setPruefungMengeVon(String pruefungMengeVon) {
		this.pruefungMengeVon.setValue( pruefungMengeVon) ;
	}


	public DOString getArtbez1() {
		return this.artbez1;
	}

	public void setArtbez1(String artbez1) {
		this.artbez1.setValue( artbez1) ;
	}

	public DOString getArtbez2() {
		return this.artbez2;
	}

	public void setArtbez2(String artbez2) {
		this.artbez2.setValue( artbez2) ;
	}

	public DOString getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted.setValue( deleted) ;
	}

	public DODate getDelDate() {
		return this.delDate;
	}

	public void setDelDate(Date delDate) {
		this.delDate.setValue( delDate) ;
	}

	public DOString getDelGrund() {
		return this.delGrund;
	}

	public void setDelGrund(String delGrund) {
		this.delGrund.setValue( delGrund) ;
	}

	public DOString getDelKuerzel() {
		return this.delKuerzel;
	}

	public void setDelKuerzel(String delKuerzel) {
		this.delKuerzel.setValue( delKuerzel) ;
	}

	public DOString getLieferinfoTpa() {
		return this.lieferinfoTpa;
	}

	public void setLieferinfoTpa(String lieferinfoTpa) {
		this.lieferinfoTpa.setValue( lieferinfoTpa) ;
	}

	public DOString getPreisermittlung() {
		return this.preisermittlung;
	}

	public void setPreisermittlung(String preisermittlung) {
		this.preisermittlung.setValue( preisermittlung) ;
	}

	public DOString getNationalerAbfallCode() {
		return this.nationalerAbfallCode;
	}

	public void setNationalerAbfallCode(String nationalerAbfallCode) {
		this.nationalerAbfallCode.setValue( nationalerAbfallCode) ;
	}

	public DOString getOrdnungsnummerCmr() {
		return this.ordnungsnummerCmr;
	}

	public void setOrdnungsnummerCmr(String ordnungsnummerCmr) {
		this.ordnungsnummerCmr.setValue( ordnungsnummerCmr) ;
	}

	public DOString getZeitstempel() {
		return this.zeitstempel;
	}

	public void setZeitstempel(String zeitstempel) {
		this.zeitstempel.setValue( zeitstempel) ;
	}

	public DOString getSetzkastenKomplett() {
		return this.setzkastenKomplett;
	}

	public void setSetzkastenKomplett(String setzkastenKomplett) {
		this.setzkastenKomplett.setValue( setzkastenKomplett) ;
	}

	public DOString getStorniert() {
		return this.storniert;
	}

	public void setStorniert(String storniert) {
		this.storniert.setValue( storniert) ;
	}

	public DODate getStorniertAm() {
		return this.storniertAm;
	}

	public void setStorniertAm(Date storniertAm) {
		this.storniertAm.setValue( storniertAm) ;
	}

	public DOString getStorniertVon() {
		return this.storniertVon;
	}

	public void setStorniertVon(String storniertVon) {
		this.storniertVon.setValue( storniertVon) ;
	}

	public DOString getStorniertGrund() {
		return this.storniertGrund;
	}

	public void setStorniertGrund(String storniertGrund) {
		this.storniertGrund.setValue( storniertGrund) ;
	}

	public DOLong getPosnr() {
		return this.posnr;
	}

	public void setPosnr(Long posnr) {
		this.posnr.setValue( posnr) ;
	}
/*
	private DOLong idTypLagerStart = new DOLong("ID_TYP_LAGER_START");
	private DOString attribLagerStart = new DOString("ATTRIB_LAGER_START");
	private DOLong idTypLagerZiel = new DOLong("ID_TYP_LAGER_ZIEL");
	private DOString attribLagerZiel = new DOString("ATTRIB_LAGER_ZIEL");
*/
		
	public DOString getErzeugtVon() {
		return this.erzeugtvon;
	}

	public void setErzeugtVon(String erzeugtvon) {
		this.erzeugtvon.setValue( erzeugtvon );
	}
	
	public DODate getErzeugtAm() {
		return this.erzeugtam;
	}

	public void setErzeugtAm(Date erzeugtam) {
		this.erzeugtam.setValue( erzeugtam );
	}
	


	
	public DOLong getIdLagerKonto() {
		return this.idLagerKonto;
	}

	public void setIdLagerKonto(Long idLagerKonto) {
		this.idLagerKonto.setValue( idLagerKonto) ;
	}
	
	public DOLong getIdZahlungsbedingungen() {
		return this.idZahlungsbedingungen;
	}

	public void setIdZahlungsbedingungen(Long idZahlungsbed) {
		this.idZahlungsbedingungen.setValue( idZahlungsbed) ;
	}
	
	public DOString getLieferbedingungen() {
		return this.lieferbedingungen;
	}

	public void setLieferbedingungen(String lieferBed) {
		this.lieferbedingungen.setValue( lieferBed) ;
	}
	
	public DOLong getIdLieferbedingungen() {
		return this.idLieferbedingungen;
	}

	public void setIdLieferbedingungen(Long idLieferbedingungen) {
		this.idLieferbedingungen.setValue(idLieferbedingungen);
	}

	//
	// Kostenstruktur anpassen
	//
	public Vector<REC_Bewegung_Atom_Kosten> getRecKosten() {
		return this.vRecKosten;
	}

	
	public void setRecKosten(Vector<REC_Bewegung_Atom_Kosten> vRecKosten) {
		this.vRecKosten = vRecKosten;
	}

	public void addRecKosten( REC_Bewegung_Atom_Kosten recKosten){
		this.vRecKosten.add(recKosten);
	}
	
	
	public DOLong getIdVposTpaFuhre() {
		return this.idVposTpaFuhre;
	}

	public void setIdVposTpaFuhre(Long idVposTpaFuhre) {
		this.idVposTpaFuhre.setValue( idVposTpaFuhre) ;
	}
	

	
	MySqlStatementBuilder m_stmtBuilder = new MySqlStatementBuilder("JT_BEWEGUNG_ATOM");
	
	
	/**
	 * gibt das Insertstatement für dieses Bewegungsobjekt zurück
	 * @author manfred
	 * @date   07.08.2012
	 * @return
	 */
	public String getSQLInsert(){
		String sInsert = null;
		
//		private JtBewegungsvektor jtBewegungsvektor );
//		
//		private JtBewegung		  jtBewegung );

		AddStatement ( idBewegung );
		AddStatement ( idBewegung_vektor );
		AddStatement ( idBewegung_vektor_pos);
		AddStatement ( idBewegung_atom );
		AddStatement ( idMandant );
		AddStatement ( letzteAenderung );
		AddStatement ( geaendertVon );
		AddStatement ( idArtikelBez );
		AddStatement ( idArtikel );
		AddStatement ( planmenge );
		AddStatement ( menge );
		
		// 2013-09-10
		AddStatement ( Gesamtpreis );
		AddStatement ( GPreisAbzMenge );
		AddStatement ( GPreisAbzAufNettomenge );
		AddStatement ( GPreisAbzVorauszahlung );
		AddStatement ( EPreisResultBruttoMenge );
		AddStatement ( mengeNetto );
		
		AddStatement ( abzugMenge );
		AddStatement ( EPreis );
		AddStatement ( EPreisResultNettoMge );
		AddStatement ( idVposKon );
		AddStatement ( idVposStd );
		AddStatement ( abrechenbar );
		AddStatement ( abgerechnet );
		AddStatement ( kontraktzwang );
		AddStatement ( kontraktzwangAusVon );
		AddStatement ( kontraktzwangAusGrund );
		AddStatement ( kontraktzwangAusAm );
		AddStatement ( leistungsdatum );

		AddStatement ( postennummer );
		AddStatement ( steuersatz );
		AddStatement ( euSteuerVermerk );
		AddStatement ( bemerkung );
		AddStatement ( bemerkungSachbearbeiter );

		AddStatement ( buchungsnummer );
		AddStatement ( notifikationNr );
		AddStatement ( pruefungMenge );
		AddStatement ( pruefungMengeAm );
		AddStatement ( pruefungMengeVon );
		
		AddStatement ( artbez1 );
		AddStatement ( artbez2 );
		AddStatement ( deleted );
		AddStatement ( delDate );
		AddStatement ( delGrund );
		AddStatement ( delKuerzel );
		AddStatement ( lieferinfoTpa );
		AddStatement ( preisermittlung );
		AddStatement ( nationalerAbfallCode );
		AddStatement ( ordnungsnummerCmr );
		AddStatement ( zeitstempel );
		AddStatement ( setzkastenKomplett );
		AddStatement ( storniert );
		AddStatement ( storniertAm );
		AddStatement ( storniertVon );
		AddStatement ( storniertGrund );
		
		AddStatement ( posnr );
		
		AddStatement ( erzeugtvon );
		AddStatement ( erzeugtam );

		// 2013-09-13
		AddStatement ( idLagerKonto );
		
		// 2013-09-17
		AddStatement ( lieferbedingungen );
		AddStatement ( idZahlungsbedingungen );
		
		//32013-11-25
		AddStatement ( idLieferbedingungen );
		
		// 2017-10-26
		AddStatement(idVposTpaFuhre);
		
	    sInsert = m_stmtBuilder.get_CompleteInsertString("JT_BEWEGUNG_ATOM", bibE2.cTO());
		return sInsert;
	}
	
	
	
	private void AddStatement(DataObject data){
		try {
			m_stmtBuilder.addSQL_Paar(data.Name(), data.Value());
		} catch (myException e) {
			// 
			DEBUG.System_println("JtBewegung::AddStatement Fehler beim erstellen des Wertes für " + data.Name(), DEBUG.DEBUG_FLAG_DIVERS1);
		}
	}



	
}
