package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.LOGIC.CONVERT_FROM_FUHRE;

// Generated 27.07.2012 10:12:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Vector;

import panter.gmbh.Echo2.bibE2;
import panter.gmbh.basics4project.DEBUG;
import panter.gmbh.indep.dataTools.MySqlStatementBuilder;
import panter.gmbh.indep.exceptions.myException;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DODate;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOLong;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOString;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DataObject;

/**
 * JtBewegungsvektor generated by hbm2java
 */
public class JtBewegung_Vektor_Pos implements java.io.Serializable {

//	private JtBewegung 			jtBewegung;
	private JtBewegung_Vektor 	jtBewegung_Vektor; 
	
	private DOString idBewegung_Vektor_Pos = new DOString("ID_BEWEGUNG_VEKTOR_POS",null,"");

	private DOString idBewegung_Vektor 		= new DOString("ID_BEWEGUNG_VEKTOR",null,"");
//	private DOString idBewegung 			= new DOString("ID_BEWEGUNG",null,"");

	private DOLong posnr 					= new DOLong("POSNR");
	
	private DOLong idMandant 				= new DOLong("ID_MANDANT");
	
	private DOString geaendertVon 			= new DOString("GEAENDERT_VON");
	private DODate letzte_aenderung 		= new DODate("LETZTE_AENDERUNG");
	private DOString erzeugtvon 			= new DOString("ERZEUGT_VON");
	private DODate erzeugtam 				= new DODate("ERZEUGT_AM");
	
//	private DOString istWareneingang 			= new DOString("IST_WARENEINGANG");
	
	



	private Vector<JtBewegung_Atom> jtBewegungsatoms = new Vector<JtBewegung_Atom>(0);

	public JtBewegung_Vektor_Pos() {
	}
	
	/**
	 * legt eine neue Vektor-Position aus einem bestehenden Vektor an
	 * setzt den Mandanten, die Änderungsdaten und die Vektor-Pos-ID
	 * 
	 * @author manfred
	 * @date   10.12.2013
	 * @param vec
	 */
	public JtBewegung_Vektor_Pos(JtBewegung_Vektor vec){
		geaendertVon = vec.getGeaendertVon();
		letzte_aenderung = vec.getLetzteAenderung();
		erzeugtvon = vec.getErzeugtVon();
		erzeugtam = vec.getErzeugtAm();
		idMandant = vec.getIdMandant();
		jtBewegung_Vektor = vec;
		
		 
		idBewegung_Vektor.setValue("SEQ_BEWEGUNG_VEKTOR.CURRVAL");
		
		idBewegung_Vektor_Pos.setValue( "SEQ_BEWEGUNG_VEKTOR_POS.NEXTVAL" );
		
		
		
	}

	public JtBewegung_Vektor_Pos(
			String idBewegungsvektorPos, 
			Long idMandant,
			String idVektor, 
			Long posnr
//			, String ist_Wareneingang
			) {
		
		this.idBewegung_Vektor.setValue( idBewegungsvektorPos );
		this.idMandant.setValue( idMandant );
//		this.istWareneingang.setValue(ist_Wareneingang);
		
		this.posnr.setValue( posnr );
	}


	public DOString getIdBewegung_Vektor_Pos() {
		return idBewegung_Vektor_Pos;
	}

	public void setIdBewegung_Vektor_Pos(String idBewegung_Vektor_Pos) {
		this.idBewegung_Vektor_Pos.setValue(idBewegung_Vektor_Pos);
	}

	
	public DOString getIdBewegungsvektor() {
		return this.idBewegung_Vektor;
	}

	public void setIdBewegungsvektor(String idBewegungsvektor) {
		this.idBewegung_Vektor.setValue( idBewegungsvektor );
	}

//	public DOString getIstWareneingang() {
//		return istWareneingang;
//	}
//
//	public void setIstWareneingang(String istWareneingang) {
//		this.istWareneingang.setValue(istWareneingang);
//	}
	
	
	
//	public DOString getIdBewegung() {
//		return this.idBewegung;
//	}
//
//	public void setIdBewegung(String idBewegung) {
//		this.idBewegung.setValue( idBewegung);
//	}
//
//	
//	public JtBewegung getJtBewegung() {
//		return this.jtBewegung;
//	}
//
//	public void setJtBewegung(JtBewegung jtBewegung) {
//		this.jtBewegung = jtBewegung;
//	}

	public void setJtBewegung_Vektor(JtBewegung_Vektor jtBewegung_Vektor) {
		this.jtBewegung_Vektor = jtBewegung_Vektor;
	}

	public JtBewegung_Vektor getJtBewegung_Vektor() {
		return jtBewegung_Vektor;
	}
	
	
	public DOLong getIdMandant() {
		return this.idMandant;
	}

	public void setIdMandant(long idMandant) {
		this.idMandant.setValue( idMandant );
	}

	public DODate getLetzteAenderung() {
		return this.letzte_aenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzte_aenderung.setValue( letzteAenderung );
	}

	public DOString getGeaendertVon() {
		return this.geaendertVon;
	}

	public void setGeaendertVon(String geaendertVon) {
		this.geaendertVon.setValue( geaendertVon );
	}



	public DOLong getPosnr() {
		return this.posnr;
	}

	public void setPosnr(Long posnr) {
		this.posnr.setValue( posnr );
	}

	
	public Vector<JtBewegung_Atom> getJtBewegungsatoms() {
		return this.jtBewegungsatoms;
	}

	public void setJtBewegungsatoms(Vector<JtBewegung_Atom> jtBewegungsatoms) {
		this.jtBewegungsatoms = jtBewegungsatoms;
	}
	
	public DOString getErzeugtVon() {
		return this.erzeugtvon;
	}

	public void setErzeugtVon(String erzeugtvon) {
		this.erzeugtvon.setValue( erzeugtvon );
	}
	
	public DODate getErzeugtAm() {
		return this.erzeugtam;
	}

	public void setErzeugtAm(Date erzeugtam) {
		this.erzeugtam.setValue( erzeugtam );
	}


	
	MySqlStatementBuilder m_stmtBuilder = new MySqlStatementBuilder("JT_BEWEGUNG_VEKTOR_POS");
	
	
	/**
	 * gibt das Insertstatement für dieses Bewegungsobjekt zurück
	 * @author manfred
	 * @date   07.08.2012
	 * @return
	 */
	public String getSQLInsert(){
		String sInsert = null;
		
		AddStatement ( idBewegung_Vektor_Pos );

		AddStatement ( idMandant );
//		AddStatement ( idBewegung );
		AddStatement ( idBewegung_Vektor );

		AddStatement ( posnr );
//		AddStatement ( istWareneingang );
		AddStatement ( letzte_aenderung);
		AddStatement ( geaendertVon );
		AddStatement ( erzeugtvon );
		AddStatement ( erzeugtam );

	    sInsert = m_stmtBuilder.get_CompleteInsertString("JT_BEWEGUNG_VEKTOR_POS", bibE2.cTO());
		return sInsert;
	}
	
	
	
	private void AddStatement(DataObject data){
		try {
			m_stmtBuilder.addSQL_Paar(data.Name(), data.Value());
		} catch (myException e) {
			// 
			DEBUG.System_println("JtBewegung::AddStatement Fehler beim erstellen des Wertes für " + data.Name(), DEBUG.DEBUG_FLAG_DIVERS1);
		}
	}


	

}
