package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.LOGIC.CONVERT_FROM_FUHRE;

// Generated 27.07.2012 10:12:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.Vector;

import panter.gmbh.Echo2.bibE2;
import panter.gmbh.basics4project.DEBUG;
import panter.gmbh.basics4project.DB_RECORDS.RECORD_VPOS_TPA_FUHRE_ORT;
import panter.gmbh.indep.dataTools.MySqlStatementBuilder;
import panter.gmbh.indep.exceptions.myException;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOBigDecimal;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DODate;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOLong;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOString;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DataObject;

/**
 * JtBewegungsvektor generated by hbm2java
 */
public class JtBewegung_Vektor implements java.io.Serializable {

	private JtBewegung jtBewegung;
	private DOString   idBewegung = new DOString("ID_BEWEGUNG",null,"");
		private DOString idBewegung_Vektor =  new DOString("ID_BEWEGUNG_VEKTOR",null,"");
	
	private DOLong idMandant =  new DOLong("ID_MANDANT");
	private DODate letzteAenderung =  new DODate("LETZTE_AENDERUNG");
	private DOString geaendertVon = new DOString("GEAENDERT_VON");
	private DOString status = new DOString("STATUS");
	private DODate storniertAm =  new DODate("STORNIERT_AM");
	private DOString storniertVon = new DOString("STORNIERT_VON");
	private DOString storniertGrund = new DOString("STORNIERT_GRUND");
	private DOString abgeschlossenVon = new DOString("ABGESCHLOSSEN_VON");
	private DODate abgeschlossenAm =  new DODate("ABGESCHLOSSEN_AM");
	private DOString variante = new DOString("VARIANTE");
	private DOLong idAdresseStartLogistik =  new DOLong("ID_ADRESSE_START_LOGISTIK");
	private DODate LDatumVon =  new DODate("L_DATUM_VON");
	private DODate LDatumBis =  new DODate("L_DATUM_BIS");
	private DODate ADatumVon =  new DODate("A_DATUM_VON");
	private DODate ADatumBis =  new DODate("A_DATUM_BIS");
	private DOString laendercodeTransit1 = new DOString("LAENDERCODE_TRANSIT1");
	private DOString laendercodeTransit2 = new DOString("LAENDERCODE_TRANSIT2");
	private DOString laendercodeTransit3 = new DOString("LAENDERCODE_TRANSIT3");
	private DOString warenklasse = new DOString("WARENKLASSE");
	private DOLong idAdresseFremdware =  new DOLong("ID_ADRESSE_FREMDWARE");
	private DOLong idUmaKontrakt =  new DOLong("ID_UMA_KONTRAKT");
	private DOString transportmittel = new DOString("TRANSPORTMITTEL");
	private DOString transportkennzeichen = new DOString("TRANSPORTKENNZEICHEN");
	private DOString anhaengerkennzeichen = new DOString("ANHAENGERKENNZEICHEN");
	private DOLong idEakCode =  new DOLong("ID_EAK_CODE");
	private DOString printEuAmtsblatt = new DOString("PRINT_EU_AMTSBLATT");
	private DOBigDecimal euBlattMenge = new DOBigDecimal("EU_BLATT_MENGE");
	private DOBigDecimal euBlattVolumen = new DOBigDecimal("EU_BLATT_VOLUMEN");
	private DODate avvAusstellungDatum =  new DODate("AVV_AUSSTELLUNG_DATUM");
	private DOString bemerkung = new DOString("BEMERKUNG");
	private DOString bemerkungSachbearbeiter = new DOString("BEMERKUNG_SACHBEARBEITER");
	private DOString deleted = new DOString("DELETED");
	private DODate delDate =  new DODate("DEL_DATE");
	private DOString delGrund = new DOString("DEL_GRUND");
	private DOString delKuerzel = new DOString("DEL_KUERZEL");
	private DOString ekVkZuordZwang = new DOString("EK_VK_ZUORD_ZWANG");
	private DOLong idAdresseSpedition =  new DOLong("ID_ADRESSE_SPEDITION");
	private DOString zeitstempel = new DOString("ZEITSTEMPEL");
	private DOLong posnr =  new DOLong("POSNR");
	
	
	private DOString erzeugtvon = new DOString("ERZEUGT_VON");
	private DODate erzeugtam = new DODate("ERZEUGT_AM");

	private Vector<JtBewegung_Vektor_Pos> jtBewegungVektorPos = new Vector<JtBewegung_Vektor_Pos>();

	
	public JtBewegung_Vektor() {
	}

	public JtBewegung_Vektor(String idBewegungsvektor, Long idMandant,Long posnr) {
		
		this.idBewegung_Vektor.setValue( idBewegungsvektor );
		this.idMandant.setValue( idMandant );
		this.posnr.setValue( posnr );
	}

	
	/**
	 * Erzeugt eine Kopie mit den grundlegenden Daten des Vektors 
	 * für die Erzeugung von Vektoren für Fuhrenorte
	 * @author manfred
	 * @date   16.12.2013
	 * @param o
	 * @throws myException 
	 */
	public JtBewegung_Vektor (JtBewegung_Vektor o) throws myException {
		
		this.idBewegung.setValue( o.idBewegung.ValuePlain());
		this.setJtBewegung(o.jtBewegung);
//		this.idBewegung_Vektor.setValue( o.idBewegung_Vektor.ValuePlain());
		this.idMandant.setValue( o.idMandant.ValuePlain());

		this.abgeschlossenAm.setValue( o.abgeschlossenAm.Value_ISO());
		this.letzteAenderung.setValue( o.letzteAenderung.Value_ISO());
		this.geaendertVon.setValue( o.geaendertVon.ValuePlain()); 
		this.status.setValue( o.status.ValuePlain());
		this.storniertAm.setValue( o.storniertAm.Value_ISO());
		this.storniertVon.setValue( o.storniertVon.ValuePlain());
		this.storniertGrund.setValue( o.storniertGrund.ValuePlain());
		this.abgeschlossenVon.setValue( o.abgeschlossenVon.ValuePlain());
		this.abgeschlossenAm.setValue( o.abgeschlossenAm.Value_ISO());
		this.variante.setValue( o.variante.ValuePlain());
		this.idAdresseStartLogistik.setValue( o.idAdresseStartLogistik.ValuePlain());
		this.LDatumVon.setValue( o.LDatumVon.Value_ISO());
		this.LDatumBis.setValue( o.LDatumBis.Value_ISO());
		this.ADatumVon.setValue( o.ADatumVon.Value_ISO());                                                                                                  
		this.ADatumBis.setValue( o.ADatumBis.Value_ISO());
		this.warenklasse.setValue( o.warenklasse.ValuePlain());
		this.idAdresseFremdware.setValue( o.idAdresseFremdware.ValuePlain());
		this.idUmaKontrakt.setValue(o.idUmaKontrakt.ValuePlain());
		this.transportmittel.setValue( o.transportmittel.ValuePlain());
		this.transportkennzeichen.setValue( o.transportkennzeichen.ValuePlain());
		this.anhaengerkennzeichen.setValue( o.anhaengerkennzeichen.ValuePlain());
		this.bemerkungSachbearbeiter.setValue( o.bemerkungSachbearbeiter.ValuePlain());
		this.deleted.setValue( o.deleted.ValuePlain());
		this.delDate.setValue( o.delDate.Value_ISO());
		this.delGrund.setValue( o.delGrund.ValuePlain());
		this.delKuerzel.setValue( o.delKuerzel.ValuePlain());
		this.ekVkZuordZwang.setValue( o.ekVkZuordZwang.ValuePlain());
		this.idAdresseSpedition.setValue( o.idAdresseSpedition.ValuePlain());
		this.zeitstempel.setValue( o.zeitstempel.ValuePlain());
		this.erzeugtvon.setValue( o.erzeugtvon.ValuePlain());
		this.erzeugtam.setValue( o.erzeugtam.Value_ISO());

// werden in Fuhrenorten explizit gesetzt		
//		this.laendercodeTransit1 = o.laendercodeTransit1;
//		this.laendercodeTransit2 = o.laendercodeTransit2;
//		this.laendercodeTransit3 = o.laendercodeTransit3;
//		this.idEakCode = o.idEakCode;
//		this.printEuAmtsblatt = o.printEuAmtsblatt;
//		this.euBlattMenge = o.euBlattMenge;
//		this.euBlattVolumen = o.euBlattVolumen;
//		this.avvAusstellungDatum = o.avvAusstellungDatum;
//		this.bemerkung = o.bemerkung;
//		this.posnr = o.posnr.ValuePlain());
	}
	
	

	/**
	 * Setzt die fehlenden Daten aus den Fuhrenorten
	 * @author manfred
	 * @date   16.12.2013
	 * @param oOrt
	 */
	public void setFuhrenOrt_Werte(RECORD_VPOS_TPA_FUHRE_ORT oOrt){
		
		try {
			this.laendercodeTransit1.setValue(oOrt.get_LAENDERCODE_TRANSIT1_cUF());
			this.laendercodeTransit2.setValue(oOrt.get_LAENDERCODE_TRANSIT2_cUF());
			this.laendercodeTransit3.setValue(oOrt.get_LAENDERCODE_TRANSIT2_cUF());
			this.idEakCode.setValue(oOrt.get_ID_EAK_CODE_cUF());
			this.printEuAmtsblatt.setValue(oOrt.get_PRINT_EU_AMTSBLATT_cUF());
			this.euBlattMenge.setValue(oOrt.get_EU_BLATT_MENGE_cUF());
			this.euBlattVolumen.setValue(oOrt.get_EU_BLATT_VOLUMEN_cUF());
			this.avvAusstellungDatum.setValue(oOrt.get_AVV_AUSSTELLUNG_DATUM_cUF());
			this.bemerkung.setValue(oOrt.get_BEMERKUNG_cUF());
			
			this.deleted.setValue( oOrt.get_DEL_DATE_cUF_NN("-").equals("-") ? null : "Y" );
			this.delDate.setValue(  bibDate.String2Date(oOrt.get_DEL_DATE_cUF()));
			this.delGrund.setValue( oOrt.get_DEL_GRUND_cUF());
			this.delKuerzel.setValue( oOrt.get_DEL_KUERZEL_cUF());
			
		} catch (myException e) {
			e.printStackTrace();
		}
	}
	
	

	public DOString getIdBewegungsvektor() {
		return this.idBewegung_Vektor;
	}

	public void setIdBewegungsvektor(String idBewegungsvektor) {
		this.idBewegung_Vektor.setValue( idBewegungsvektor );
	}

	public DOString getIdBewegung() {
		return this.idBewegung;
	}

	public void setIdBewegung(String idBewegung) {
		this.idBewegung.setValue( idBewegung);
	}
	
	public JtBewegung getJtBewegung() {
		return this.jtBewegung;
	}

	public void setJtBewegung(JtBewegung jtBewegung) {
		this.jtBewegung = jtBewegung;
	}

	public DOLong getIdMandant() {
		return this.idMandant;
	}

	public void setIdMandant(long idMandant) {
		this.idMandant.setValue( idMandant );
	}

	public DODate getLetzteAenderung() {
		return this.letzteAenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung.setValue( letzteAenderung );
	}

	public DOString getGeaendertVon() {
		return this.geaendertVon;
	}

	public void setGeaendertVon(String geaendertVon) {
		this.geaendertVon.setValue( geaendertVon );
	}

	public DOString getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status.setValue( status );
	}

	public DODate getStorniertAm() {
		return this.storniertAm;
	}

	public void setStorniertAm(Date storniertAm) {
		this.storniertAm.setValue( storniertAm );
	}

	public DOString getStorniertVon() {
		return this.storniertVon;
	}

	public void setStorniertVon(String storniertVon) {
		this.storniertVon.setValue( storniertVon );
	}

	public DOString getStorniertGrund() {
		return this.storniertGrund;
	}

	public void setStorniertGrund(String storniertGrund) {
		this.storniertGrund.setValue( storniertGrund );
	}

	public DOString getAbgeschlossenVon() {
		return this.abgeschlossenVon;
	}

	public void setAbgeschlossenVon(String abgeschlossenVon) {
		this.abgeschlossenVon.setValue( abgeschlossenVon );
	}

	public DODate getAbgeschlossenAm() {
		return this.abgeschlossenAm;
	}

	public void setAbgeschlossenAm(Date abgeschlossenAm) {
		this.abgeschlossenAm.setValue( abgeschlossenAm );
	}

	public DOString getVariante() {
		return this.variante;
	}

	public void setVariante(String variante) {
		this.variante.setValue( variante );
	}

	public DOLong getIdAdresseStartLogistik() {
		return this.idAdresseStartLogistik;
	}

	public void setIdAdresseStartLogistik(Long idAdresseStartLogistik) {
		this.idAdresseStartLogistik.setValue( idAdresseStartLogistik );
	}

	public DODate getLDatumVon() {
		return this.LDatumVon;
	}

	public void setLDatumVon(Date LDatumVon) {
		this.LDatumVon.setValue( LDatumVon );
	}

	public DODate getLDatumBis() {
		return this.LDatumBis;
	}

	public void setLDatumBis(Date LDatumBis) {
		this.LDatumBis.setValue( LDatumBis );
	}

	public DODate getADatumVon() {
		return this.ADatumVon;
	}

	public void setADatumVon(Date ADatumVon) {
		this.ADatumVon.setValue( ADatumVon );
	}

	public DODate getADatumBis() {
		return this.ADatumBis;
	}

	public void setADatumBis(Date ADatumBis) {
		this.ADatumBis.setValue( ADatumBis );
	}

	public DOString getLaendercodeTransit1() {
		return this.laendercodeTransit1;
	}

	public void setLaendercodeTransit1(String laendercodeTransit1) {
		this.laendercodeTransit1.setValue( laendercodeTransit1 );
	}

	public DOString getLaendercodeTransit2() {
		return this.laendercodeTransit2;
	}

	public void setLaendercodeTransit2(String laendercodeTransit2) {
		this.laendercodeTransit2.setValue( laendercodeTransit2 );
	}

	public DOString getLaendercodeTransit3() {
		return this.laendercodeTransit3;
	}

	public void setLaendercodeTransit3(String laendercodeTransit3) {
		this.laendercodeTransit3.setValue( laendercodeTransit3 );
	}

	public DOString getWarenklasse() {
		return this.warenklasse;
	}

	public void setWarenklasse(String warenklasse) {
		this.warenklasse.setValue( warenklasse );
	}

	public DOLong getIdAdresseFremdware() {
		return this.idAdresseFremdware;
	}

	public void setIdAdresseFremdware(Long idAdresseFremdware) {
		this.idAdresseFremdware.setValue( idAdresseFremdware );
	}

	public DOLong getIdUmaKontrakt() {
		return this.idUmaKontrakt;
	}

	public void setIdUmaKontrakt(Long idUmaKontrakt) {
		this.idUmaKontrakt.setValue( idUmaKontrakt );
	}

	public DOString getTransportmittel() {
		return this.transportmittel;
	}

	public void setTransportmittel(String transportmittel) {
		this.transportmittel.setValue( transportmittel );
	}

	public DOString getTransportkennzeichen() {
		return this.transportkennzeichen;
	}

	public void setTransportkennzeichen(String transportkennzeichen) {
		this.transportkennzeichen.setValue( transportkennzeichen );
	}

	public DOString getAnhaengerkennzeichen() {
		return this.anhaengerkennzeichen;
	}

	public void setAnhaengerkennzeichen(String anhaengerkennzeichen) {
		this.anhaengerkennzeichen.setValue( anhaengerkennzeichen );
	}

	public DOLong getIdEakCode() {
		return this.idEakCode;
	}

	public void setIdEakCode(Long idEakCode) {
		this.idEakCode.setValue( idEakCode );
	}

	public DOString getPrintEuAmtsblatt() {
		return this.printEuAmtsblatt;
	}

	public void setPrintEuAmtsblatt(String printEuAmtsblatt) {
		this.printEuAmtsblatt.setValue( printEuAmtsblatt );
	}

	public DOBigDecimal getEuBlattMenge() {
		return this.euBlattMenge;
	}

	public void setEuBlattMenge(BigDecimal euBlattMenge) {
		this.euBlattMenge.setValue( euBlattMenge );
	}

	public DOBigDecimal getEuBlattVolumen() {
		return this.euBlattVolumen;
	}

	public void setEuBlattVolumen(BigDecimal euBlattVolumen) {
		this.euBlattVolumen.setValue( euBlattVolumen );
	}

	public DODate getAvvAusstellungDatum() {
		return this.avvAusstellungDatum;
	}

	public void setAvvAusstellungDatum(Date avvAusstellungDatum) {
		this.avvAusstellungDatum.setValue( avvAusstellungDatum );
	}

	public DOString getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung.setValue( bemerkung );
	}

	public DOString getBemerkungSachbearbeiter() {
		return this.bemerkungSachbearbeiter;
	}

	public void setBemerkungSachbearbeiter(String bemerkungSachbearbeiter) {
		this.bemerkungSachbearbeiter.setValue( bemerkungSachbearbeiter );
	}

	public DOString getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted.setValue( deleted );
	}

	public DODate getDelDate() {
		return this.delDate;
	}

	public void setDelDate(Date delDate) {
		this.delDate.setValue( delDate );
	}

	public DOString getDelGrund() {
		return this.delGrund;
	}

	public void setDelGrund(String delGrund) {
		this.delGrund.setValue( delGrund );
	}

	public DOString getDelKuerzel() {
		return this.delKuerzel;
	}

	public void setDelKuerzel(String delKuerzel) {
		this.delKuerzel.setValue( delKuerzel );
	}

	public DOString getEkVkZuordZwang() {
		return this.ekVkZuordZwang;
	}

	public void setEkVkZuordZwang(String ekVkZuordZwang) {
		this.ekVkZuordZwang.setValue( ekVkZuordZwang );
	}

	public DOLong getIdAdresseSpedition() {
		return this.idAdresseSpedition;
	}

	public void setIdAdresseSpedition(Long idAdresseSpedition) {
		this.idAdresseSpedition.setValue( idAdresseSpedition );
	}

	public DOString getZeitstempel() {
		return this.zeitstempel;
	}

	public void setZeitstempel(String zeitstempel) {
		this.zeitstempel.setValue( zeitstempel );
	}


	public DOLong getPosnr() {
		return this.posnr;
	}

	public void setPosnr(Long posnr) {
		this.posnr.setValue( posnr );
	}

	public Vector<JtBewegung_Vektor_Pos> getJtBewegungVektorPoss() {
		return this.jtBewegungVektorPos;
	}

	public void setJtBewegungVektorPoss(Vector<JtBewegung_Vektor_Pos> jtBewegungVektorPoss) {
		this.jtBewegungVektorPos = jtBewegungVektorPoss;
	}
	
	public DOString getErzeugtVon() {
		return this.erzeugtvon;
	}

	public void setErzeugtVon(String erzeugtvon) {
		this.erzeugtvon.setValue( erzeugtvon );
	}
	
	public DODate getErzeugtAm() {
		return this.erzeugtam;
	}

	public void setErzeugtAm(Date erzeugtam) {
		this.erzeugtam.setValue( erzeugtam );
	}


	
	MySqlStatementBuilder m_stmtBuilder = new MySqlStatementBuilder("JT_BEWEGUNG_VEKTOR");
	
	
	/**
	 * gibt das Insertstatement für dieses Bewegungsobjekt zurück
	 * @author manfred
	 * @date   07.08.2012
	 * @return
	 */
	public String getSQLInsert(){
		String sInsert = null;
		
		AddStatement ( idBewegung );
		AddStatement ( idBewegung_Vektor );
		AddStatement ( idMandant );
		AddStatement ( letzteAenderung );
		AddStatement ( geaendertVon );
		AddStatement ( status );
		AddStatement ( storniertAm );
		AddStatement ( storniertVon );
		AddStatement ( storniertGrund );
		AddStatement ( abgeschlossenVon );
		AddStatement ( abgeschlossenAm );
		AddStatement ( variante );
		AddStatement ( idAdresseStartLogistik );
		AddStatement ( LDatumVon );
		AddStatement ( LDatumBis );
		AddStatement ( ADatumVon );
		AddStatement ( ADatumBis );
		AddStatement ( laendercodeTransit1 );
		AddStatement ( laendercodeTransit2 );
		AddStatement ( laendercodeTransit3 );
		AddStatement ( warenklasse );
		AddStatement ( idAdresseFremdware );
		AddStatement ( idUmaKontrakt );
		AddStatement ( transportmittel );
		AddStatement ( transportkennzeichen );
		AddStatement ( anhaengerkennzeichen );
		AddStatement ( idEakCode );
		AddStatement ( printEuAmtsblatt );
		AddStatement ( euBlattMenge );
		AddStatement ( euBlattVolumen );
		AddStatement ( avvAusstellungDatum );
		AddStatement ( bemerkung );
		AddStatement ( bemerkungSachbearbeiter );
		AddStatement ( deleted );
		AddStatement ( delDate );
		AddStatement ( delGrund );
		AddStatement ( delKuerzel );
		AddStatement ( ekVkZuordZwang );
		AddStatement ( idAdresseSpedition );
		AddStatement ( zeitstempel );
		AddStatement ( posnr );
		
		AddStatement ( erzeugtvon );
		AddStatement ( erzeugtam );

	    sInsert = m_stmtBuilder.get_CompleteInsertString("JT_BEWEGUNG_VEKTOR", bibE2.cTO());
		return sInsert;
	}
	
	
	
	private void AddStatement(DataObject data){
		try {
			m_stmtBuilder.addSQL_Paar(data.Name(), data.Value());
		} catch (myException e) {
			// 
			DEBUG.System_println("JtBewegung::AddStatement Fehler beim erstellen des Wertes für " + data.Name(), DEBUG.DEBUG_FLAG_DIVERS1);
		}
	}
	

}
