package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.LOGIC.CONVERT_FROM_FUHRE;

// Generated 27.07.2012 10:12:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.Vector;

import panter.gmbh.Echo2.bibE2;
import panter.gmbh.basics4project.DEBUG;
import panter.gmbh.basics4project.DB_RECORDS.RECORD_VPOS_TPA_FUHRE;
import panter.gmbh.indep.dataTools.MySqlStatementBuilder;
import panter.gmbh.indep.exceptions.myException;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DODate;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOLong;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOString;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DataObject;

/**
 * JtBewegung generated by hbm2java
 */
public class JtBewegung implements java.io.Serializable {

	private DOString idBewegung = new DOString("ID_BEWEGUNG",null,"");
	
	private DOLong idMandant = new DOLong("ID_MANDANT");
	private DODate letzteAenderung = new DODate("LETZTE_AENDERUNG");
	private DOString geaendertVon = new DOString("GEAENDERT_VON");
	private DOLong ipVposTpaNg =    new DOLong("ID_VPOS_TPA_NG");
	private DOLong idVposTpaFuhre = new DOLong("ID_VPOS_TPA_FUHRE");
	private DOString fahrplanSatz = new DOString("FAHRPLAN_SATZ");
	private DOString bemerkung = new DOString("BEMERKUNG");
	private DOString bemerkungSachbearbeiter = new DOString("BEMERKUNG_SACHBEARBEITER");
	private DODate anrufdatumFp= new DODate("ANRUFDATUM_FP");
	private DOString anruferFp = new DOString("ANRUFER_FP");
	private DOLong anzahlContainerFp = new DOLong("ANZAHL_CONTAINER_FP");
	private DOString bemerkungStartFp = new DOString("BEMERKUNG_START_FP");
	private DOString bemerkungZielFp = new DOString("BEMERKUNG_ZIEL_FP");
	private DODate datFahrplanFp= new DODate("DAT_FAHRPLAN_FP");
	private DODate datVorgemerktEndeFp= new DODate("DAT_VORGEMERKT_ENDE_FP");
	private DODate datVorgemerktFp= new DODate("DAT_VORGEMERKT_FP");
	private DOString eanCodeFp = new DOString("EAN_CODE_FP");
	private DOString erfasserFp = new DOString("ERFASSER_FP");
	private DOString fahrerFp = new DOString("FAHRER_FP");
	private DOLong fahrplangruppeFp = new DOLong("FAHRPLANGRUPPE_FP");
	private DOString fahrtAnfangFp = new DOString("FAHRT_ANFANG_FP");
	private DOString fahrtEndeFp = new DOString("FAHRT_ENDE_FP");
	private DOLong idContainertypFp = new DOLong("ID_CONTAINERTYP_FP");
	private DOLong idMaschinenAnhFp = new DOLong("ID_MASCHINEN_ANH_FP");
	private DOLong idMaschinenLkwFp = new DOLong("ID_MASCHINEN_LKW_FP");
	private DOString istGeplantFp = new DOString("IST_GEPLANT_FP");
	private DOLong sortierungFp = new DOLong("SORTIERUNG_FP");
	private DOString taetigkeitFp = new DOString("TAETIGKEIT_FP");
	private DODate ladeDatumVon= new DODate("LADE_DATUM_VON");
	private DODate ladeDatumBis= new DODate("LADE_DATUM_BIS");
	private DODate abladeDatumVon= new DODate("ABLADE_DATUM_VON");
	private DODate abladeDatumBis= new DODate("ABLADE_DATUM_BIS");
	private DOString deleted = new DOString("DELETED");
	private DODate delDate= new DODate("DEL_DATE");
	private DOString delGrund = new DOString("DEL_GRUND");
	private DOString delKuerzel = new DOString("DEL_KUERZEL");
	private DOString zeitstempel = new DOString("ZEITSTEMPEL");
	
	private DOString erzeugtvon = new DOString("ERZEUGT_VON");
	private DODate erzeugtam = new DODate("ERZEUGT_AM");
	
	private DOString istLagerbuchungAlt = new DOString("IST_LAGERBUCHUNG_ALT");
	
	private Vector<JtBewegung_Vektor> jtBewegungsvektors = new Vector<JtBewegung_Vektor>(0);

	public JtBewegung() {
	}

	public JtBewegung(String idBewegung, Long idMandant) {
		this.idBewegung.setValue( idBewegung );
		this.idMandant.setValue( idMandant );
	}

	
	/**
	 * Erzeugt ein JtBewegung - Objekt aus einer Fuhre
	 * 
	 * @author manfred
	 * @date   07.08.2012
	 * @param o
	 * @throws myException
	 */
	public JtBewegung( RECORD_VPOS_TPA_FUHRE o ) throws myException{
		this ();
		
		this.setIdBewegung("SEQ_BEWEGUNG.NEXTVAL");
		
		this.setAbladeDatumVon(bibDate.String2Date(o.get_DATUM_ANLIEFERUNG_cUF()));
		this.setLadeDatumVon(bibDate.String2Date(o.get_DATUM_ABHOLUNG_cUF()));
		
		this.setLadeDatumBis(bibDate.String2Date(o.get_DATUM_ABHOLUNG_ENDE_cUF()));
		this.setAnrufdatumFp(bibDate.String2Date(o.get_ANRUFDATUM_FP_cUF()));
		
		this.setDelDate(bibDate.String2Date(o.get_DEL_DATE_cUF()));
		this.setAnrufdatumFp(bibDate.String2Date(o.get_ANRUFDATUM_FP_cUF()));
		this.setAbladeDatumBis(bibDate.String2Date(o.get_DATUM_ANLIEFERUNG_ENDE_cUF()));

		this.setAnruferFp(o.get_ANRUFER_FP_cUF());
		this.setAnzahlContainerFp(new Short( o.get_ANZAHL_CONTAINER_FP_dValue(null).shortValue()) );
		
		this.setBemerkung(o.get_BEMERKUNG_cUF());
		this.setBemerkungSachbearbeiter(o.get_BEMERKUNG_SACHBEARBEITER_cUF());
		this.setDeleted(o.get_DELETED_cUF());
		this.setDelGrund(o.get_DEL_GRUND_cUF());
		this.setDelKuerzel(o.get_DEL_KUERZEL_cUF());
		
		this.setZeitstempel(o.get_ZEITSTEMPEL_cUF());
		
		this.setBemerkungStartFp(o.get_BEMERKUNG_START_FP_cUF());
		this.setBemerkungZielFp(o.get_BEMERKUNG_ZIEL_FP_cUF());
		
		this.setDatFahrplanFp(bibDate.String2Date(o.get_DAT_FAHRPLAN_FP_cUF()));
		this.setDatVorgemerktEndeFp(bibDate.String2Date(o.get_DAT_VORGEMERKT_ENDE_FP_cUF()));
		this.setDatVorgemerktFp(bibDate.String2Date(o.get_DAT_VORGEMERKT_FP_cUF()));
		this.setEanCodeFp(o.get_EAN_CODE_FP_cUF());
		this.setErfasserFp(o.get_ERFASSER_FP_cUF());
		this.setFahrerFp(o.get_FAHRER_FP_cUF());
		this.setFahrplangruppeFp(o.get_FAHRPLANGRUPPE_FP_lValue(null));
		this.setFahrplanSatz(o.get_FUHRE_AUS_FAHRPLAN_cUF());
		this.setFahrtAnfangFp(o.get_FAHRT_ANFANG_FP_cUF());
		this.setFahrtEndeFp(o.get_FAHRT_ENDE_FP_cUF());
		
		this.setIdContainertypFp(o.get_ID_CONTAINERTYP_FP_lValue(null));
		this.setIdMandant(o.get_ID_MANDANT_lValue(null));
		this.setIdMaschinenAnhFp(o.get_ID_MASCHINEN_ANH_FP_lValue(null));
		this.setIdMaschinenLkwFp(o.get_ID_MASCHINEN_LKW_FP_lValue(null));
		this.setIdVposTpaFuhre(o.get_ID_VPOS_TPA_FUHRE_lValue(null));
		this.setIpVposTpaNg(null);
		
		this.setIstGeplantFp(o.get_IST_GEPLANT_FP_cUF());
		this.setSortierungFp(o.get_SORTIERUNG_FP_lValue(null));
		this.setTaetigkeitFp(o.get_TAETIGKEIT_FP_cUF());
		this.setZeitstempel(o.get_ZEITSTEMPEL_cUF());

		
		this.setErzeugtAm(bibDate.String2Date(o.get_ERZEUGT_AM_cUF()));
		this.setErzeugtVon(o.get_ERZEUGT_VON_cUF());
		this.setLetzteAenderung(bibDate.String2Date(o.get_LETZTE_AENDERUNG_cUF()));
		this.setGeaendertVon(o.get_GEAENDERT_VON_cUF());
		
	}
	
	
	
	
	
	public DOString getIdBewegung() {
		return this.idBewegung;
	}

	public void setIdBewegung(String idBewegung) {
		this.idBewegung.setValue( idBewegung );
	}

	public DOLong getIdMandant() {
		return this.idMandant;
	}

	public void setIdMandant(Long idMandant) {
		this.idMandant.setValue( idMandant );
	}

	public DODate getLetzteAenderung() {
		return this.letzteAenderung;
	}

	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung.setValue( letzteAenderung );
	}

	public DOString getGeaendertVon() {
		return this.geaendertVon;
	}

	public void setGeaendertVon(String geaendertVon) {
		this.geaendertVon.setValue( geaendertVon );
	}

	public DOLong getIpVposTpaNg() {
		return this.ipVposTpaNg;
	}

	public void setIpVposTpaNg(Long ipVposTpaNg) {
		this.ipVposTpaNg.setValue( ipVposTpaNg );
	}

	public DOLong getIdVposTpaFuhre() {
		return this.idVposTpaFuhre;
	}

	public void setIdVposTpaFuhre(Long idVposTpaFuhre) {
		this.idVposTpaFuhre.setValue( idVposTpaFuhre );
	}

	public DOString getFahrplanSatz() {
		return this.fahrplanSatz;
	}

	public void setFahrplanSatz(String fahrplanSatz) {
		this.fahrplanSatz.setValue( fahrplanSatz );
	}

	public DOString getBemerkung() {
		return this.bemerkung;
	}

	public void setBemerkung(String bemerkung) {
		this.bemerkung.setValue( bemerkung );
	}

	public DOString getBemerkungSachbearbeiter() {
		return this.bemerkungSachbearbeiter;
	}

	public void setBemerkungSachbearbeiter(String bemerkungSachbearbeiter) {
		this.bemerkungSachbearbeiter.setValue( bemerkungSachbearbeiter );
	}

	public DODate getAnrufdatumFp() {
		return this.anrufdatumFp;
	}

	public void setAnrufdatumFp(Date anrufdatumFp) {
		this.anrufdatumFp.setValue( anrufdatumFp );
	}

	public DOString getAnruferFp() {
		return this.anruferFp;
	}

	public void setAnruferFp(String anruferFp) {
		this.anruferFp.setValue( anruferFp);
	}

	public DOLong getAnzahlContainerFp() {
		return this.anzahlContainerFp;
	}

	public void setAnzahlContainerFp(Short anzahlContainerFp) {
		this.anzahlContainerFp.setValue( anzahlContainerFp );
	}

	public DOString getBemerkungStartFp() {
		return this.bemerkungStartFp;
	}

	public void setBemerkungStartFp(String bemerkungStartFp) {
		this.bemerkungStartFp.setValue( bemerkungStartFp );
	}

	public DOString getBemerkungZielFp() {
		return this.bemerkungZielFp;
	}

	public void setBemerkungZielFp(String bemerkungZielFp) {
		this.bemerkungZielFp.setValue( bemerkungZielFp );
	}

	public DODate getDatFahrplanFp() {
		return this.datFahrplanFp;
	}

	public void setDatFahrplanFp(Date datFahrplanFp) {
		this.datFahrplanFp.setValue( datFahrplanFp );
	}

	public DODate getDatVorgemerktEndeFp() {
		return this.datVorgemerktEndeFp;
	}

	public void setDatVorgemerktEndeFp(Date datVorgemerktEndeFp) {
		this.datVorgemerktEndeFp.setValue( datVorgemerktEndeFp );
	}

	public DODate getDatVorgemerktFp() {
		return this.datVorgemerktFp;
	}

	public void setDatVorgemerktFp(Date datVorgemerktFp) {
		this.datVorgemerktFp.setValue( datVorgemerktFp );
	}

	public DOString getEanCodeFp() {
		return this.eanCodeFp;
	}

	public void setEanCodeFp(String eanCodeFp) {
		this.eanCodeFp.setValue( eanCodeFp );
	}

	public DOString getErfasserFp() {
		return this.erfasserFp;
	}

	public void setErfasserFp(String erfasserFp) {
		this.erfasserFp.setValue( erfasserFp );
	}

	public DOString getFahrerFp() {
		return this.fahrerFp;
	}

	public void setFahrerFp(String fahrerFp) {
		this.fahrerFp.setValue( fahrerFp );
	}

	public DOLong getFahrplangruppeFp() {
		return this.fahrplangruppeFp;
	}

	public void setFahrplangruppeFp(Long fahrplangruppeFp) {
		this.fahrplangruppeFp.setValue( fahrplangruppeFp );
	}

	public DOString getFahrtAnfangFp() {
		return this.fahrtAnfangFp;
	}

	public void setFahrtAnfangFp(String fahrtAnfangFp) {
		this.fahrtAnfangFp.setValue( fahrtAnfangFp );
	}

	public DOString getFahrtEndeFp() {
		return this.fahrtEndeFp;
	}

	public void setFahrtEndeFp(String fahrtEndeFp) {
		this.fahrtEndeFp.setValue( fahrtEndeFp );
	}

	public DOLong getIdContainertypFp() {
		return this.idContainertypFp;
	}

	public void setIdContainertypFp(Long idContainertypFp) {
		this.idContainertypFp.setValue( idContainertypFp );
	}

	public DOLong getIdMaschinenAnhFp() {
		return this.idMaschinenAnhFp;
	}

	public void setIdMaschinenAnhFp(Long idMaschinenAnhFp) {
		this.idMaschinenAnhFp.setValue( idMaschinenAnhFp );
	}

	public DOLong getIdMaschinenLkwFp() {
		return this.idMaschinenLkwFp;
	}

	public void setIdMaschinenLkwFp(Long idMaschinenLkwFp) {
		this.idMaschinenLkwFp.setValue( idMaschinenLkwFp );
	}

	public DOString getIstGeplantFp() {
		return this.istGeplantFp;
	}

	public void setIstGeplantFp(String istGeplantFp) {
		this.istGeplantFp.setValue( istGeplantFp );
	}

	public DOLong getSortierungFp() {
		return this.sortierungFp;
	}

	public void setSortierungFp(Long sortierungFp) {
		this.sortierungFp.setValue( sortierungFp );
	}

	public DOString getTaetigkeitFp() {
		return this.taetigkeitFp;
	}

	public void setTaetigkeitFp(String taetigkeitFp) {
		this.taetigkeitFp.setValue( taetigkeitFp );
	}

	public DODate getLadeDatumVon() {
		return this.ladeDatumVon;
	}

	public void setLadeDatumVon(Date ladeDatumVon) {
		this.ladeDatumVon.setValue( ladeDatumVon );
	}

	public DODate getLadeDatumBis() {
		return this.ladeDatumBis;
	}

	public void setLadeDatumBis(Date ladeDatumBis) {
		this.ladeDatumBis.setValue( ladeDatumBis );
	}

	public DODate getAbladeDatumVon() {
		return this.abladeDatumVon;
	}

	public void setAbladeDatumVon(Date abladeDatumVon) {
		this.abladeDatumVon.setValue( abladeDatumVon );
	}

	public DODate getAbladeDatumBis() {
		return this.abladeDatumBis;
	}

	public void setAbladeDatumBis(Date abladeDatumBis) {
		this.abladeDatumBis.setValue( abladeDatumBis );
	}

	public DOString getDeleted() {
		return this.deleted;
	}

	public void setDeleted(String deleted) {
		this.deleted.setValue( deleted );
	}

	public DODate getDelDate() {
		return this.delDate;
	}

	public void setDelDate(Date delDate) {
		this.delDate.setValue( delDate );
	}

	public DOString getDelGrund() {
		return this.delGrund;
	}

	public void setDelGrund(String delGrund) {
		this.delGrund.setValue( delGrund );
	}

	public DOString getDelKuerzel() {
		return this.delKuerzel;
	}

	public void setDelKuerzel(String delKuerzel) {
		this.delKuerzel.setValue( delKuerzel );
	}

	public DOString getZeitstempel() {
		return this.zeitstempel;
	}

	public void setZeitstempel(String zeitstempel) {
		this.zeitstempel.setValue( zeitstempel );
	}

	public Vector<JtBewegung_Vektor> getJtBewegungsvektors() {
		return this.jtBewegungsvektors;
	}

	public void setJtBewegungsvektors(Vector<JtBewegung_Vektor> jtBewegungsvektors) {
		this.jtBewegungsvektors = jtBewegungsvektors;
	}
	
	public DOString getIstLagerbuchungAlt() {
		return this.istLagerbuchungAlt;
	}

	public void setIstLagerbuchungAlt(String istLagerbuchungAlt) {
		this.istLagerbuchungAlt.setValue( istLagerbuchungAlt );
	}
	
	
	public DOString getErzeugtVon() {
		return this.erzeugtvon;
	}

	public void setErzeugtVon(String erzeugtvon) {
		this.erzeugtvon.setValue( erzeugtvon );
	}
	
	public DODate getErzeugtAm() {
		return this.erzeugtam;
	}

	public void setErzeugtAm(Date erzeugtam) {
		this.erzeugtam.setValue( erzeugtam );
	}
	
	
	
	MySqlStatementBuilder m_stmtBuilder = new MySqlStatementBuilder("JT_BEWEGUNG");
	
	
	/**
	 * gibt das Insertstatement für dieses Bewegungsobjekt zurück
	 * @author manfred
	 * @date   07.08.2012
	 * @return
	 */
	public String getSQLInsert(){
		String sInsert = null;

		AddStatement (  idBewegung );
		AddStatement (  idMandant );
		AddStatement (  letzteAenderung );
		AddStatement (  geaendertVon );
		AddStatement (  ipVposTpaNg );
		AddStatement (  idVposTpaFuhre );
		AddStatement (  fahrplanSatz );
		AddStatement (  bemerkung );
		AddStatement (  bemerkungSachbearbeiter );
		AddStatement (  anrufdatumFp);
		AddStatement (  anruferFp );
		AddStatement (  anzahlContainerFp );
		AddStatement (  bemerkungStartFp );
		AddStatement (  bemerkungZielFp );
		AddStatement (  datFahrplanFp);
		AddStatement (  datVorgemerktEndeFp);
		AddStatement (  datVorgemerktFp);
		AddStatement (  eanCodeFp );
		AddStatement (  erfasserFp );
		AddStatement (  fahrerFp );
		AddStatement (  fahrplangruppeFp );
		AddStatement (  fahrtAnfangFp );
		AddStatement (  fahrtEndeFp );
		AddStatement (  idContainertypFp );
		AddStatement (  idMaschinenAnhFp );
		AddStatement (  idMaschinenLkwFp );
		AddStatement (  istGeplantFp );
		AddStatement (  sortierungFp );
		AddStatement (  taetigkeitFp );
		AddStatement (  ladeDatumVon);
		AddStatement (  ladeDatumBis);
		AddStatement (  abladeDatumVon);
		AddStatement (  abladeDatumBis);
		AddStatement (  deleted );
		AddStatement (  delDate);
		AddStatement (  delGrund );
		AddStatement (  delKuerzel );
		AddStatement (  zeitstempel );
		AddStatement (  istLagerbuchungAlt );
		
		AddStatement (  erzeugtvon );
		AddStatement (  erzeugtam );

			    
	    sInsert = m_stmtBuilder.get_CompleteInsertString("JT_Bewegung", bibE2.cTO());
		return sInsert;
	}
	
	
	
	private void AddStatement(DataObject data){
		try {
			m_stmtBuilder.addSQL_Paar(data.Name(), data.Value());
		} catch (myException e) {
			// 
			DEBUG.System_println("JtBewegung::AddStatement Fehler beim erstellen des Wertes für " + data.Name(), DEBUG.DEBUG_FLAG_DIVERS1);
		}
	}

}
