package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.LOGIC.CONVERT_FROM_FUHRE;

// Generated 27.07.2012 10:12:13 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import panter.gmbh.Echo2.bibE2;
import panter.gmbh.basics4project.DEBUG;
import panter.gmbh.indep.dataTools.MySqlStatementBuilder;
import panter.gmbh.indep.exceptions.myException;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOBigDecimal;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DODate;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOLong;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DOString;
import rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.DataObject;

/**
 * JtBewegungsatom generated by hbm2java
 */
public class JtBewegung_Station implements java.io.Serializable {

	private DOString idBewegung_Station = new DOString("ID_BEWEGUNG_STATION",null,"");
	
	private DOLong idMandant = new DOLong("ID_MANDANT");
	
	private DODate letzteAenderung = new DODate("LETZTE_AENDERUNG");
	private DOString geaendertVon = new DOString("GEAENDERT_VON");
	
	private DOLong   IDAdresse = new DOLong("ID_ADRESSE");
	private DOString IDBewegungAtom =  new DOString("ID_BEWEGUNG_ATOM",null,"");

	private DOLong 	 Mengenvorzeichen = new DOLong("MENGENVORZEICHEN");
	
	private DOBigDecimal Kontrollmenge = new DOBigDecimal("KONTROLLMENGE");
	private DOString Wiegekartenkenner = new DOString("WIEGEKARTENKENNER");
	
	private DOString Name1 = new DOString("NAME1");
	private DOString Name2 = new DOString("NAME2");
	private DOString Name3 = new DOString("NAME3");
	private DOString Strasse = new DOString("STRASSE");
	private DOString Hausnummer = new DOString("HAUSNUMMER");
	private DOString Laendercode = new DOString("LAENDERCODE");
	private DOString Plz = new DOString("PLZ");
	private DOString Ort = new DOString("ORT");
	private DOString Ortzusatz = new DOString("ORTZUSATZ");
	private DOString Oeffnungszeiten = new DOString("OEFFNUNGSZEITEN");
	private DOString Bestellnummer = new DOString("BESTELLNUMMER");
	private DOString Telefon = new DOString("TELEFON");
	private DOString Fax = new DOString("FAX");
	
	private DOString erzeugtvon = new DOString("ERZEUGT_VON");
	private DODate erzeugtam = new DODate("ERZEUGT_AM");

	private DOLong   IDWiegekarte = new DOLong("ID_WIEGEKARTE");
	private DOLong   IDAdresseBesitzer = new DOLong("ID_ADRESSE_BESITZER");
	private DOLong   IDAdresseBasis = new DOLong("ID_ADRESSE_BASIS");
	
	
	public JtBewegung_Station() {
	}

	public JtBewegung_Station(String idBewegungstation, Long idMandant,	Long Mengenvorzeichen) {
		this.idBewegung_Station.setValue( idBewegungstation );
		this.idMandant.setValue( idMandant );
		this.Mengenvorzeichen.setValue( Mengenvorzeichen );
	}

	
	/**
	 * Erzeugt eine Station und verbindet sie gleich mit dem Atom
	 * Ausserdem werden die Erzeugt und geändert-Werte übernommen.
	 * @author manfred
	 * @date   21.05.2013
	 * @param oAtom
	 */
	public JtBewegung_Station(JtBewegung_Atom oAtom, long Mengenvorzeichen){
		oAtom.addJtBewegungstation(this);
		this.setIdMandant(oAtom.getIdMandant().lValue);
		this.setErzeugtam(oAtom.getErzeugtAm().dValue);
		this.setErzeugtvon(oAtom.getErzeugtVon().sValue);
		this.setGeaendertVon(oAtom.getGeaendertVon().sValue);
		this.setLetzteAenderung(oAtom.getLetzteAenderung().dValue);
		this.setIdBewegung_Station("SEQ_BEWEGUNG_STATION.NEXTVAL");
		this.setIDBewegungAtom("SEQ_BEWEGUNG_ATOM.CURRVAL");
		this.setMengenvorzeichen(Mengenvorzeichen);
	}
	
	
	/**
	 * @param iDAdresse the iDAdresse to set
	 */
	public void setIDAdresse(Long iDAdresse) {
		IDAdresse.setValue(iDAdresse);
	}

	/**
	 * @return the iDAdresse
	 */
	public DOLong getIDAdresse() {
		return IDAdresse;
	}

	/**
	 * @param iDAdresseBesitzer the iDAdresseBesitzer to set
	 */
	public void setIDAdresseBesitzer(Long iDAdresseBesitzer) {
		IDAdresseBesitzer.setValue(iDAdresseBesitzer);
	}

	/**
	 * @return the iDAdresseBesitzer
	 */
	public DOLong getIDAdresseBesitzer() {
		return IDAdresseBesitzer;
	}
	
	
	/**
	 * @param iDAdresseBasis the iDAdresseBasis to set
	 */
	public void setIDAdresseBasis(Long iDAdresseBasis) {
		IDAdresseBasis.setValue(iDAdresseBasis);
	}

	/**
	 * @return the iDAdresseBesitzer
	 */
	public DOLong getIDAdresseBasis() {
		return IDAdresseBasis;
	}
	
	
	/**
	 * @param iDBewegungAtom the iDBewegungAtom to set
	 */
	public void setIDBewegungAtom(String iDBewegungAtom) {
		IDBewegungAtom.setValue(iDBewegungAtom) ;
	}

	/**
	 * @return the iDBewegungAtom
	 */
	public DOString getIDBewegungAtom() {
		return IDBewegungAtom;
	}

	/**
	 * @return the idBewegung_Station
	 */
	public DOString getIdBewegung_Station() {
		return idBewegung_Station;
	}

	/**
	 * @param idBewegung_Station the idBewegung_Station to set
	 */
	public void setIdBewegung_Station(String idBewegung_Station) {
		this.idBewegung_Station.setValue(idBewegung_Station);
	}

	/**
	 * @return the idMandant
	 */
	public DOLong getIdMandant() {
		return idMandant;
	}

	/**
	 * @param idMandant the idMandant to set
	 */
	public void setIdMandant(Long idMandant) {
		this.idMandant.setValue(idMandant);
	}

	/**
	 * @return the letzteAenderung
	 */
	public DODate getLetzteAenderung() {
		return letzteAenderung;
	}

	/**
	 * @param letzteAenderung the letzteAenderung to set
	 */
	public void setLetzteAenderung(Date letzteAenderung) {
		this.letzteAenderung.setValue(letzteAenderung);
	}

	/**
	 * @return the geaendertVon
	 */
	public DOString getGeaendertVon() {
		return geaendertVon;
	}

	/**
	 * @param geaendertVon the geaendertVon to set
	 */
	public void setGeaendertVon(String geaendertVon) {
		this.geaendertVon.setValue(geaendertVon);
	}

	public DOBigDecimal getKontrollmenge() {
		return this.Kontrollmenge;
	}

	public void setKontrollmenge(BigDecimal kontrollmenge) {
		this.Kontrollmenge.setValue( kontrollmenge) ;
	}

	
	/**
	 * @return the wiegekartenKenner
	 */
	public DOString getWiegekartenKenner() {
		return Wiegekartenkenner;
	}

	/**
	 * @param wiegekartenKenner the wiegekartenKenner to set
	 */
	public void setWiegekartenKenner(String wiegekartenKenner) {
		Wiegekartenkenner.setValue(wiegekartenKenner);
	}

	/**
	 * @return the mengenvorzeichen
	 */
	public DOLong getMengenvorzeichen() {
		return Mengenvorzeichen;
	}

	/**
	 * @param mengenvorzeichen the mengenvorzeichen to set
	 */
	public void setMengenvorzeichen(Long mengenvorzeichen) {
		Mengenvorzeichen.setValue( mengenvorzeichen);
	}

	/**
	 * @return the name1
	 */
	public DOString getName1() {
		return Name1;
	}

	/**
	 * @param name1 the name1 to set
	 */
	public void setName1(String name1) {
		Name1.setValue(name1);
	}

	/**
	 * @return the name2
	 */
	public DOString getName2() {
		return Name2;
	}

	/**
	 * @param name2 the name2 to set
	 */
	public void setName2(String name2) {
		Name2.setValue(name2);
	}

	/**
	 * @return the name3
	 */
	public DOString getName3() {
		return Name3;
	}

	/**
	 * @param name3 the name3 to set
	 */
	public void setName3(String name3) {
		Name3.setValue(name3);
	}

	/**
	 * @return the strasse
	 */
	public DOString getStrasse() {
		return Strasse;
	}

	/**
	 * @param strasse the strasse to set
	 */
	public void setStrasse(String strasse) {
		Strasse.setValue(strasse);
	}

	/**
	 * @return the hausnummer
	 */
	public DOString getHausnummer() {
		return Hausnummer;
	}

	/**
	 * @param hausnummer the hausnummer to set
	 */
	public void setHausnummer(String hausnummer) {
		Hausnummer.setValue(hausnummer);
	}

	/**
	 * @return the laendercode
	 */
	public DOString getLaendercode() {
		return Laendercode;
	}

	/**
	 * @param laendercode the laendercode to set
	 */
	public void setLaendercode(String laendercode) {
		Laendercode.setValue(laendercode);
	}

	/**
	 * @return the plz
	 */
	public DOString getPlz() {
		return Plz;
	}

	/**
	 * @param plz the plz to set
	 */
	public void setPlz(String plz) {
		Plz.setValue(plz);
	}

	/**
	 * @return the ort
	 */
	public DOString getOrt() {
		return Ort;
	}

	/**
	 * @param ort the ort to set
	 */
	public void setOrt(String ort) {
		Ort.setValue(ort);
	}

	/**
	 * @return the ortzusatz
	 */
	public DOString getOrtzusatz() {
		return Ortzusatz;
	}

	/**
	 * @param ortzusatz the ortzusatz to set
	 */
	public void setOrtzusatz(String ortzusatz) {
		Ortzusatz.setValue(ortzusatz);
	}

	/**
	 * @return the oeffnungszeiten
	 */
	public DOString getOeffnungszeiten() {
		return Oeffnungszeiten;
	}

	/**
	 * @param oeffnungszeiten the oeffnungszeiten to set
	 */
	public void setOeffnungszeiten(String oeffnungszeiten) {
		Oeffnungszeiten.setValue(oeffnungszeiten);
	}

	/**
	 * @return the bestellnummer
	 */
	public DOString getBestellnummer() {
		return Bestellnummer;
	}

	/**
	 * @param bestellnummer the bestellnummer to set
	 */
	public void setBestellnummer(String bestellnummer) {
		Bestellnummer.setValue(bestellnummer);
	}

	/**
	 * @return the telefon
	 */
	public DOString getTelefon() {
		return Telefon;
	}

	/**
	 * @param telefon the telefon to set
	 */
	public void setTelefon(String telefon) {
		Telefon.setValue(telefon);
	}

	/**
	 * @return the fax
	 */
	public DOString getFax() {
		return Fax;
	}

	/**
	 * @param fax the fax to set
	 */
	public void setFax(String fax) {
		Fax.setValue(fax);
	}

	/**
	 * @return the erzeugtvon
	 */
	public DOString getErzeugtvon() {
		return erzeugtvon;
	}

	/**
	 * @param erzeugtvon the erzeugtvon to set
	 */
	public void setErzeugtvon(String erzeugtvon) {
		this.erzeugtvon.setValue( erzeugtvon);
	}

	/**
	 * @return the erzeugtam
	 */
	public DODate getErzeugtam() {
		return erzeugtam;
	}

	/**
	 * @param erzeugtam the erzeugtam to set
	 */
	public void setErzeugtam(Date erzeugtam) {
		this.erzeugtam.setValue(erzeugtam);
	}

	/**
	 * @param iDWiegekarte the iDWiegekarte to set
	 */
	public void setIDWiegekarte(Long iDWiegekarte) {
		IDWiegekarte.setValue( iDWiegekarte);
	}
	
	/**
	 * @return the iDWiegekarte
	 */
	public DOLong getIDWiegekarte() {
		return IDWiegekarte;
	}
	
	
	/**
	 * @return the m_stmtBuilder
	 */
	public MySqlStatementBuilder getM_stmtBuilder() {
		return m_stmtBuilder;
	}

	/**
	 * @param m_stmtBuilder the m_stmtBuilder to set
	 */
	public void setM_stmtBuilder(MySqlStatementBuilder m_stmtBuilder) {
		this.m_stmtBuilder = m_stmtBuilder;
	}




	MySqlStatementBuilder m_stmtBuilder = new MySqlStatementBuilder("JT_BEWEGUNG_STATION");
	
	
	/**
	 * gibt das Insertstatement für dieses Bewegungsobjekt zurück
	 * @author manfred
	 * @date   07.08.2012
	 * @return
	 */
	public String getSQLInsert(){
		String sInsert = null;
		
		AddStatement ( idMandant );
		AddStatement ( letzteAenderung );
		AddStatement ( geaendertVon );
		AddStatement ( erzeugtvon );
		AddStatement ( erzeugtam );

		AddStatement ( idBewegung_Station );
		AddStatement ( IDBewegungAtom );
		AddStatement ( IDAdresse );
		
		AddStatement ( Mengenvorzeichen );
		AddStatement ( Kontrollmenge );
		AddStatement ( Wiegekartenkenner );
		AddStatement ( IDWiegekarte );
		
		AddStatement ( Name1 );
		AddStatement ( Name2 );
		AddStatement ( Name3 );
		AddStatement ( Strasse );
		AddStatement ( Hausnummer );
		AddStatement ( Laendercode );
		AddStatement ( Plz );
		AddStatement ( Ort );
		AddStatement ( Ortzusatz );
		AddStatement ( Oeffnungszeiten );
		AddStatement ( Bestellnummer );
		AddStatement ( Telefon );
		AddStatement ( Fax );
		
		AddStatement ( IDAdresseBesitzer );
		AddStatement ( IDAdresseBasis );
			    
	    sInsert = m_stmtBuilder.get_CompleteInsertString("JT_BEWEGUNG_STATION", bibE2.cTO());
		return sInsert;
	}
	
	
	
	private void AddStatement(DataObject data){
		try {
			m_stmtBuilder.addSQL_Paar(data.Name(), data.Value());
		} catch (myException e) {
			// 
			DEBUG.System_println("JtBewegungStation::AddStatement Fehler beim erstellen des Wertes für " + data.Name(), DEBUG.DEBUG_FLAG_DIVERS1);
		}
	}


	
}
