package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.LAGER.LAGER_INVENTUR;

public class ATOM_LAG_INV_CONST {
	public static String HASH_COL_ATOM_LAGERSALDO_OK = "SALDO_OK";
//	public static String HASH_COL_LAGERSALDO_MENGE = "SALDO_MENGE";
	public static String HASH_COL_ATOM_LAGERSALDO_DIFFERENZ = "SALDO_DIFF";
	
	public static String HASH_COL_ATOM_SETZKASTEN_NEU_AUFBAUEN = "NEUAUFBAU_SETZKASTEN";
}
