CREATE
OR
REPLACE TRIGGER #TRIGGERNAME#  AFTER
INSERT OR UPDATE OR DELETE ON #TABLENAME#
    FOR EACH ROW 

DECLARE
ID_MANDANT_ACTUAL  #TABLENAME#.ID_MANDANT%TYPE;
    
BEGIN

SELECT SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_MANDANT') INTO ID_MANDANT_ACTUAL FROM DUAL;

IF (ID_MANDANT_ACTUAL = #ID_MANDANT# ) THEN

IF INSERTING THEN


INSERT
INTO
    JT_TRIGGER_ACTION_LOG
    (
      ID_TRIGGER_ACTION_LOG
	  ,ID_MANDANT
      ,LETZTE_AENDERUNG
      ,ERZEUGT_AM
      ,TABLE_BASENAME
      ,TABLE_ID
      ,DB_ACTION_TYP
      ,FIELD_NAME
      ,VAL_BEFORE
      ,VAL_AFTER
      ,USER_ID
      ,ID_TRIGGER_ACTION_DEF
    )
    VALUES
    (
      SEQ_TRIGGER_ACTION_LOG.NEXTVAL
	  ,SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_MANDANT')
      ,SYSDATE
      ,SYSDATE
      ,'#TABLEBASENAME#'
      ,:NEW.ID_#TABLEBASENAME#
      ,'INSERT'
      ,NULL
      ,NULL
      ,NULL
      ,SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_USER')
      ,#ID_TRIGGER_ACTION_DEF#
    
    );

ELSIF UPDATING THEN
  
INSERT
INTO
    JT_TRIGGER_ACTION_LOG
    (
      ID_TRIGGER_ACTION_LOG
	  ,ID_MANDANT
      ,LETZTE_AENDERUNG
      ,ERZEUGT_AM
      ,TABLE_BASENAME
      ,TABLE_ID
      ,DB_ACTION_TYP
      ,FIELD_NAME
      ,VAL_BEFORE
      ,VAL_AFTER
      ,USER_ID
      ,ID_TRIGGER_ACTION_DEF
    )
    VALUES
    (
      SEQ_TRIGGER_ACTION_LOG.NEXTVAL
	  ,SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_MANDANT')
      ,SYSDATE
      ,SYSDATE
      ,'#TABLEBASENAME#'
      ,:NEW.ID_#TABLEBASENAME#
      ,'UPDATE'
      ,NULL
      ,NULL
      ,NULL
      ,SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_USER')
      ,#ID_TRIGGER_ACTION_DEF#
    
    );


ELSIF DELETING THEN

INSERT
INTO
    JT_TRIGGER_ACTION_LOG
    (
      ID_TRIGGER_ACTION_LOG
	  ,ID_MANDANT
      ,LETZTE_AENDERUNG
      ,ERZEUGT_AM
      ,TABLE_BASENAME
      ,TABLE_ID
      ,DB_ACTION_TYP
      ,FIELD_NAME
      ,VAL_BEFORE
      ,VAL_AFTER
      ,USER_ID
      ,ID_TRIGGER_ACTION_DEF
    )
    VALUES
    (
      SEQ_TRIGGER_ACTION_LOG.NEXTVAL
	  ,SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_MANDANT')
      ,SYSDATE
      ,SYSDATE
      ,'#TABLEBASENAME#'
      ,:NEW.ID_#TABLEBASENAME#
      ,'DELETE'
      ,NULL
      ,NULL
      ,NULL
      ,SYS_CONTEXT(PD_PACKAGE.GET_CONTEXT_NAME, 'ID_USER')
      ,#ID_TRIGGER_ACTION_DEF#
    
    );



END IF;
   
    
END IF;
    
END;