package panter.gmbh.Echo2.__BASIC_COMPONENTS.INFO_MAILS_AUS_MASKEN.AUFRUF;


public class MMC__CONST {
	public static String KEY_RETURNVALUE = "RETURNVALUE";
	public static String KEY_ERRORCODE = "ERRORCODE";
	
	public static String KEY_INFOMAIL_KLEMMBRETTKENNER4BETREFF = 	"INFOMAIL_KLEMMBRETTKENNER4BETREFF";
	public static String KEY_INFOMAIL_KLEMMBRETTKENNER4TEXT = 		"INFOMAIL_KLEMMBRETTKENNER4TEXT";
	public static String KEY_INFOMAIL_KENNER4ARCHIV = 				"INFOMAIL_KENNER4ARCHIV";
	
}
