package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.ATOM.UI.BEWEG;

import panter.gmbh.Echo2.MyE2_String;
import panter.gmbh.Echo2.bibE2;
import panter.gmbh.indep.dataTools.SQLField;
import panter.gmbh.indep.exceptions.myException;

public class B_LIST_SQLFIELD_ARTIKEL_FIRT_ATOM_FIRST_VEKTOR extends SQLField {

	public B_LIST_SQLFIELD_ARTIKEL_FIRT_ATOM_FIRST_VEKTOR() throws myException {
		super("(SELECT to_char(MENGE,'fm999g999g990d0','NLS_NUMERIC_CHARACTERS = '',.''')||' '||EIH.EINHEITKURZ||' '||A.ARTBEZ1 FROM JT_BEWEGUNG_VEKTOR V "+
				" INNER JOIN JT_BEWEGUNG_ATOM A ON (V.ID_BEWEGUNG_VEKTOR=A.ID_BEWEGUNG_VEKTOR) "+
				" INNER JOIN JT_ARTIKEL AR ON (A.ID_ARTIKEL=AR.ID_ARTIKEL) "+
				" INNER JOIN JT_EINHEIT EIH ON (AR.ID_EINHEIT=EIH.ID_EINHEIT) "+
				" WHERE V.ID_BEWEGUNG_VEKTOR = (SELECT MIN(VV.ID_BEWEGUNG_VEKTOR) FROM JT_BEWEGUNG_VEKTOR VV WHERE NVL(VV.DELETED,'N')='N' AND  VV.ID_BEWEGUNG=V.ID_BEWEGUNG) "+
				" AND   A.ID_BEWEGUNG_ATOM =    (SELECT MIN(AA.ID_BEWEGUNG_ATOM)    FROM JT_BEWEGUNG_ATOM AA      WHERE NVL(AA.DELETED,'N')='N' AND AA.ID_BEWEGUNG_VEKTOR=V.ID_BEWEGUNG_VEKTOR) "+
				" AND   NVL(A.DELETED,'N')='N' "+
				" AND   NVL(V.DELETED,'N')='N' "+
				" AND   V.ID_BEWEGUNG = JT_BEWEGUNG.ID_BEWEGUNG) ", 
				B__CONST.COLKEY_SORTE, new MyE2_String("Startsorte") , bibE2.get_CurrSession());
	}

}
