package rohstoff.Echo2BusinessLogic.FIBU_KONTEN.RULES_FILTER_BASED;

public class FKR_FB__CONST {
	
	public static String FELD_FILTER_BESCHREIBUNG = "FILTER_BESCHREIBUNG";
	
	public static String FELD_FULL_DAUGHTER_FILTER_AND = "FELD_FULL_DAUGHTER_FILTER_AND";
	
	public static String COMPONENT_NAME_STRINGED_CONDITION = "COMPONENT_NAME_STRINGED_CONDITION";
}
