package rohstoff.Echo2BusinessLogic.BEWEGUNG_NG.LAGER.LAGER_BEWEGUNG;

public class ATOM_LAG_CONST
{
	public static String HASH_BUTTON_SHOW_FUHRE = "BUTTON_SHOW_FUHRE";
	
	public static String HASH_COLUMN_MENGE_WE = "HASH_COLUMN_MENGE_WE";
	public static String HASH_COLUMN_MENGE_WA = "HASH_COLUMN_MENGE_WA";
	
	public static String HASH_COLUMN_SORTE_BEMERKUNG = "COLUMN_SORTE_BEMERKUNG";
	public static String HASH_COLUMN_FUHRE_FUHRENORT = "COLUMN_FUHRE_FUHRENORT";
	public static String HASH_COLUMN_FUHRE_KENNZEICHEN = "COLUMN_FUHRE_KENNZEICHEN";
	public static String HASH_COLUMN_ADRESS_ID = "COLUMN_ADRESS_ID";	
	public static String HASH_COLUMN_STORNO = "COLUMN_FUHRE_STORNO";
	public static String HASH_COLUMN_STATUS = "COLUMN_FUHRE_STATUS";	
	public static String HASH_COLUMN_NUMMERN = "COLUMN_NUMMERN";
	public static String HASH_COLUMN_NUMMERN_PAPIERE = "COLUMN_NUMMERN_PAPIERE";
	
	public static String HASH_FIELD_KONTRAKTNUMMER = "FIELD_KONTRAKTNUMMER";
	public static String HASH_FIELD_RECHNR = "FIELD_RECHNR";
	
	
	
	public static String HASH_LIST_BT_KOSTEN_ERFASSUNG = "HASH_LIST_BT_KOSTEN_ERFASSUNG";
	public static String HASH_COLUMN_KOSTEN_ERFASSUNG =  "HASH_COLUMN_KOSTEN_ERFASSUNG";
	
}
